- Makefile
Copy all tags from origin (some might not be needed scoped to this repo) but this is how oc has been compiled. Changes:
```
ldd oc
linux-vdso.so.1 (0x00007ffc710e0000)
libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f3f59961000)
libgpgme.so.11 => /lib64/libgpgme.so.11 (0x00007f3f59914000)
libassuan.so.0 => /lib64/libassuan.so.0 (0x00007f3f598fe000)
libgpg-error.so.0 => /lib64/libgpg-error.so.0 (0x00007f3f598db000)
libc.so.6 => /lib64/libc.so.6 (0x00007f3f59715000)
/lib64/ld-linux-x86-64.so.2 (0x00007f3f599b1000)
```
into
```
ldd oc
linux-vdso.so.1 (0x00007ffeccae7000)
libpthread.so.0 => /lib64/libpthread.so.0 (0x00007fc132ddd000)
libdl.so.2 => /lib64/libdl.so.2 (0x00007fc132dd7000)
libc.so.6 => /lib64/libc.so.6 (0x00007fc132c11000)
/lib64/ld-linux-x86-64.so.2 (0x00007fc132e2d000)
``` …
> Set the same tags as origin did

- Makefile
Much better option than https://github.com/openshift/origin/pull/23438
It's still not pretty, but it's slightly better.
> quick and dirty way to get a kubectl version

- pkg/helpers/describe/describer.go
The scenario when the docker image config field is not set (nil) is an error and instead of hiding it, we should print the empty fields.
Follow up for https://github.com/openshift/origin/pull/23318
/cc @smarterclayton 
/cc @tnozicka
> describe: print empty image config fields if the docker config is nil

- pkg/cli/cli.go
- pkg/cli/deployer/deployer.go
- pkg/cli/deployer/version.go
- pkg/cli/kubectlwrappers/wrappers.go
- pkg/cli/shim_kubectl.go
- pkg/cli/version/version.go
This PR
* adds OpenShift version information (clusteroperator openshift-apiserver version) to `oc version`
* there is no extended information for OpenShift version, only the clusteroperator/openshift-apiserver version number
* new version cmd, same as kubectl version with added OpenShift server version information
(see output below)
**NOTE** 
OpenShift Server Version requires admin user, if not logged in as admin user command or if clusteroperator not found, no info is given for OpenShift Version (no error) below -v 5, see output for -v 5 Info message. 
*Could not figure out git cmds to pull directly from https://github.com/openshift/origin/pull/23309 so did it manually*
> Extend version cmd

- pkg/cli/admin/release/mirror.go
_Resubmission of https://github.com/openshift/origin/pull/23381_
When performing a release mirror, provide examples for use in
install-config.yaml (install) or ImageContentSourcePolcy (upgrade).
https://jira.coreos.com/browse/CORS-1105
Example output:
```
$ oc adm release mirror --from=registry.svc.ci.openshift.org/ocp/release:4.2 --to=registry.svc.ci.openshift.org/rteague-1/mirror-test
info: Mirroring 94 images to registry.svc.ci.openshift.org/rteague-1/mirror-test ...
...
Success
Update image:  registry.svc.ci.openshift.org/rteague-1/mirror-test:release
Mirror prefix: registry.svc.ci.openshift.org/rteague-1/mirror-test
To use the new mirrored repository to install, add the following section to the install-config.yaml:
imageContentSources:
- mirrors:
- …
```
> release/mirror: Add examples for using the new mirror

- cmd/oc/oc.go
- cmd/oc/oc_test.go
SCCs are custom resources. Having them in the global oc scheme leads to strange effects like broken `oc edit` and `oc patch`.
> Bug 1707679: Don't install CRD SCC types into global scheme

- pkg/cli/extract/extract.go
Omitting binaryData is potentially invalid and extract should be usable
to script against these keys.
> Bug 1735404: `oc extract` should print binaryData as well

- pkg/cli/idle/idle.go
Resolves: https://bugzilla.redhat.com/show_bug.cgi?id=1737127
> Bug 1737127: idle: fix null dereference when pod's controller can't be found

- pkg/cli/admin/release/extract_tools.go
The installer for baremetal is in a separate image as part of the
release, we need to provide awareness to the `oc` command so we can
actually extract the installer and replace the release image location.
A user would extract the baremetal installer like this:
```
oc adm release extract --registry-config <pull secret> --command=openshift-baremetal-install --to /tmp
```
> pkg/cli/admin/release: support extracting baremetal installer

- pkg/cli/login/error_translation.go
- pkg/cli/login/helpers.go
- pkg/cli/login/loginoptions.go
This adds a very specific error message for users who pass the console URL instead of API URL. 
Adds a check for http response with Content-Type "html/text"  (console url) instead of "application/json" (server URL) 
(see output below)
_btw: kubeadmin is not meant to be used via CLI, only to be used for admin login to console to set up a valid identity provider via console, however, I used kubeadmin in the examples below bc I did not set up any other idp_
> Bug 1704827: Improve error msg when console URL passed to login via CLI

- pkg/cli/admin/release/new.go
`--exclude` was not being handled for `--from-release` in `oc adm release new`,
which prevents us from creating payloads that leave deliberate skew in a cluster.
> release: Allow --exclude to work for --from-release in release

- Makefile
- oc.spec
> Bug 1739445: Fix oc rpm for ART builds

- pkg/cli/set/env.go
- pkg/cli/set/probe.go
- pkg/cli/set/triggers.go
- pkg/cli/set/volume.go
This PR:
1) Removes Git Repo examples from `oc set volume` help menu, since git volume source is no longer supported.
2) updates examples in oc `dc/registry` to `dc/myapp`  
(3.x dc/registry vs 4.x deployment/image-registry), might cause confusion if left as/is.
> Bug 1709239: Remove Git Repo option from 'oc set volumes' cmd

- pkg/cli/admin/release/new.go
Passing --exclude resulted in a verification error because changing
those rules didn't correctly detect that the output is expected to
differ. Instead, we should skip if a user specifies any variants.
Also remove the need to declare "AlwaysInclude", manually verified
that it created the same output.
Needed for creating fake payloads during upgrade testing that lack
machine-config-operator.
> release: Fix verification errors when excluding components

- pkg/cli/admin/release/new.go
The current error is confusing for the default value (which is
cluster-version-operator) when the user screws up and doesn't specify
a release image input. Make it clear which tag we couldn't find.
> release: Add a better error message when base tag missing

- pkg/cli/secrets/sshauth.go
$ oc secret new-sshauth
Command "new-sshauth" is deprecated, use oc create secret
panic: runtime error: index out of range
goroutine 1 [running]:
github.com/openshift/origin/pkg/oc/cli/secrets.(*CreateSSHAuthSecretOptions).Complete(0xc420e5caa0, 0x3caf1a0, 0xc420f177d0, 0x5303668, 0x0, 0x0, 0x23, 0x23)
/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/pkg/oc/cli/secrets/sshauth.go:149 +0x2ae
github.com/openshift/origin/pkg/oc/cli/secrets.NewCmdCreateSSHAuthSecret.func1(0xc4213ab900, 0x5303668, 0x0, 0x0)
/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/pkg/oc/cli/secrets/sshauth.go:80 +0x7a
github.com/openshift/origin/vendor/github.com/spf13/cobra.(*Command).execute(0xc4213ab900, 0x5303668, 0x0, 0x0, 0xc4213ab900, …
> Fixup the following crash

- pkg/cli/admin/release/info.go
fix bug: https://bugzilla.redhat.com/show_bug.cgi?id=1725027
@xingxingxia @soltysh  Please help review. thanks.
> fix bug 1725027: --output flag to release info does not include all options

- pkg/cli/admin/inspect/pod.go
Makes the endpoint collection non-fatal.
> Bug 1756107: Make container endpoint collection errors non-fatal

- pkg/cli/admin/release/git.go
- pkg/cli/admin/release/git_test.go
- pkg/cli/admin/release/info.go
Prefixes like `[release-4.3]`, `[4.2]`, `[blocker]` are typically
informational only - to allow a little more flexibility from
contributors in PR titles strip those prefixes. Also support lists
of bugs and mixed case for `Bug` or the use of `Bugs`.
/assign @eparis
/cherrypick release-4.2
/cherrypick release-4.1
> release: Strip leading bracket indicators from changelogs

- pkg/cli/admin/release/extract_tools.go
- pkg/cli/admin/release/extract_tools_test.go
- pkg/cli/version/version.go
- pkg/version/version.go
This PR refactors `oc adm release extract` to report payload version for `oc version`.
In case of `oc version -o yaml` full output will print the version struct plus a new field `releaseClientVersion: payloadversion` 
See output below. 
`make build` w/ this PR checked out, then
with `oc adm release extract --tools quay.io/sallyom/release:test -v=3` access a test release image that includes:
* registry.svc.ci.openshift.org/ocp/release:4.3.0-0.ci-2019-10-07-053008
* cli image built from this PR 
/assign @soltysh  
cc @wking @tnozicka @smarterclayton
> Bug 1715001: If extracted from payload, 'oc version' reports payload version

- pkg/cli/admin/release/mirror.go
> pkg/cli/admin/release/mirror: Fix "exapmles" -> "examples" comment typo

- pkg/cli/admin/inspect/inspect.go
This commit fix wrong error flag shown during oc adm inspect command.
Signed-off-by: Ashish Ranjan <aranjan@redhat.com>
> fix(inspect): changes --base-dir flag to --dest-dir

- pkg/cli/image/extract/extract.go
There is a race condition in the vendored version of docker code that
can cause image extraction to panic.  When the `pigz` package is
installed, docker's DecompressStream code prefers to use it, however,
that code can return the io buffer to the pool while the command is
still writing to it. If the buffer is reused while that's happening,
`oc` will panic.  There are many reports of this happening.
As the vendored docker comes from kubectl, and the version there (even
for k8s 1.16) is quite old, this disables using pigz at all by setting
MOBY_DISABLE_PIGZ environment variable. 
fixes #58
> pkg/cli/image/extract: disable pigz to prevent race condition

- pkg/cli/image/mirror/mirror.go
- pkg/cli/image/mirror/plan.go
We mirror the manifest list and blobs, but not the sub manifests. Correct that by registering those with the plan.
Without this change mirroring a manifest list and `--filter-by-os=.*` fails with 'manifest invalid' due to the sub manifest not being copied (you can't push a manifest list unless all manifests are found).
> image-mirror: Manifest list manifests have to be copied

- cmd/oc/oc.go
- pkg/cli/image/extract/extract.go
Due to a race condition in Docker[1], we need to disable extraction
using unpigz. Currently this is done in the image extraction code,
however this code is multi-threaded.  Setenv is not thread safe in C[2],
so even thought it is safe in go[3], there's a small risk if there's
any C threads running.
It's safer to just set this env variable once when `oc` starts, rather
every time the layerByEntry function is called.
[1] https://github.com/moby/moby/issues/39859
[2] https://github.com/rust-lang/rust/pull/24741
[3] https://github.com/golang/go/blob/a38a917aee626a9b9d5ce2b93964f586bf759ea0/src/syscall/env_unix.go#L18
> cmd/oc: disable docker's use of pigz earlier

- pkg/cli/admin/release/extract_tools.go
- pkg/cli/admin/release/extract_tools_test.go
- pkg/version/version.go
Since[ this](https://github.com/openshift/oc/pull/88) merged, when using an extracted oc to extract openshift-install|oc, command fails, because the shared binary replacement location.  This PR is the fix. 
/cc @soltysh
> Bug 1763728: fix 'oc adm release extract' version injection

- pkg/cli/admin/release/extract.go
- pkg/cli/admin/release/info.go
- pkg/cli/admin/release/mirror.go
- pkg/cli/image/imagesource/dryrun.go
- pkg/cli/image/imagesource/options.go
- pkg/cli/image/imagesource/reference.go
- pkg/cli/image/info/info.go
- pkg/cli/image/mirror/mappings.go
- pkg/cli/image/mirror/mirror.go
- pkg/cli/registry/login/login.go
Three improvements to simplify life for disconnected users
---
release: Release mirror dry run should work without remote
It should be possible to do
$ oc adm release mirror --dry-run A --to B
where B is not reachable from the current location. This allows you to get
the correct image content source policy, before mirroring to disk.
---
release: Allow `oc adm release info` to retrieve semantic versions
When connected to a cluster, requesting a semantic version in the argument
to oc adm release info will lookup matching semantic versions in the
ClusterVersion object and return release info if found. Simplifies "show
metadata for next release".
---
image: Allow `oc image info` to lookup images by wildcard
$ oc image info library/mysql:9*
now finds matching tags based on the wildcard syntax.
> Improve release to work better for disconnected

- pkg/cli/admin/release/new.go
Previously, additional mappings provided as args weren't considered when
creating a new release image from an ImageStream, an existing release
image, or a directory. The was particularly problematic when attempting
to add new images:
oc adm release new \
--from-release quay.io/openshift-release-dev/ocp-release:4.2 \
--to-image quay.io/crawford/openshift-release \
cluster-etcd-operator=quay.io/hexfusion/cluster-etcd-operator
Without this patch, the previous command would create a release image
but it wouldn't the cluster-etcd-operator manifests.
Instead of adding new mappings in the default case (when not using an
existing ImageStream, release image, or directory), add them
unconditionally. Clayton thinks that this defect may have been
introduced when the validation code was being …
> Bug 1725977: admin/release/new: always consider all mappings

- pkg/cli/newapp/newapp.go
Fixing problem introduced in https://github.com/openshift/oc/pull/101
/assign @adambkaplan @DhritiShikhar
> Bug 1767163: fix app.kubernetes.io/name to use just IS name

- pkg/cli/admin/inspect/inspect.go
- pkg/cli/admin/inspect/resource.go
> Improve errors in inspect

- pkg/helpers/newapp/docker/dockerfile/dockerfile.go
- pkg/helpers/newapp/docker/dockerfile/dockerfile_test.go
In some cases the FROM statement on a Dockerfile may contain an extra
alias, e.g.:
FROM fedora:latest AS builder
This commit fixes the parser to use only the second parsed node on the
FROM statement(on this case "fedora:latest") instead of returning the
last one(on this case "builder").
> Bug 1759920: Fixed Dockerfile FROM statement parser.

- pkg/helpers/cmd/templater.go
This PR completes this fix for oc: https://github.com/openshift/kubernetes-kubectl/pull/3
> Bug 1748777: oc: don't print usage info if pass a bad flag, only suggest to pass --help

- pkg/cli/image/manifest/manifest.go
- pkg/cli/image/mirror/mappings.go
- pkg/helpers/image/helpers.go
The digest is more specific and should override tag when we retrieve
image info or perform mirrors. Almost all code uses these two helpers.
> image: If a user specifies both tag and digest, retrieve via digest

- pkg/cli/admin/upgrade/upgrade.go
--force is used when
a) the release image is not verified.
b) the operators are blocking upgrades.
For cases when the users are using custom update channel, the release-image is probably not going to be verified by Red Hat signature, but the users should be allowed to update to the latest
available update by skipping the verification step.
And for cases where the users want to upgrade to the latest upgrade, even when the operators are blocking updates should be achievable by setting the force flag.
/assign @smarterclayton
> Bug 1713263: pkg/cli/admin/upgrade: allow users to force when updating to latest

- pkg/cli/admin/admin.go
- pkg/cli/admin/catalog/catalog.go
- pkg/cli/admin/catalog/cmd.go
Constrain `oc adm catalog` subcommand to linux builds. 
This temporarily addresses an [issue with cross-compiling the subcommand](https://bugzilla.redhat.com/show_bug.cgi?id=1771329 ) for mac and windows in 4.3.
> Bug 1771329: only build adm catalog command for linux

- Makefile
- images/cli-artifacts/Dockerfile.rhel
- oc.spec
In order for console-operator deployment to succeed, cli-artifacts needs to be available on all arches for downloads-openshift-console.  However, in that case, /usr/bin/oc (inherited from cli) is a native binary, and we want to provide all primary Linux architectures to match those on mirror.openshift.com.
In order to do so, this provides cross-compiled Linux binaries for multiple architectures.  Cross-compiling oc fails with gssapi enabled, therefore it is disabled in the cross builds.
Because this affects cluster deployment, we are looking to get this into 4.2 and later branches (we can provide separate PRs for stable branches as needed).
> Enable all Linux arches in cli-artifacts

- images/cli-artifacts/Dockerfile.rhel
https://github.com/openshift/oc/pull/153 introduced a regression because
`oc adm release extract` does not handle the hard links well.
> Bug 1774642: Avoid hard links in cli-artifacts

- pkg/cli/debug/debug.go
The RHEL7 support tools image is only built for AMD64, but there will
soon be a need for an image that works on System Z (and eventually
Power). Changing to the RHEL8 image gets us the additional
architectures. Additionally, RHCOS has moved to RHEL8 content, so it's
best to keep the support tools in sync.
> Bug 1777030: Update support tools container image

- pkg/cli/admin/release/extract_tools.go
- pkg/cli/admin/release/extract_tools_test.go
- pkg/version/version.go
This is everything from #165 except setting `InjectReleaseVersion` for the installers, because @abhinavdahiya [wants some time][1] to look into the ecosystem around that.  @sallyom, this also lets us fix the existing bugs described in #165 while avoiding [your concerns][2] about warnings when running code that expects to inject release versions into the installer before the installer has the marker to recieve them.
[1]: https://github.com/openshift/installer/pull/2682#issuecomment-554725150
[2]: https://github.com/openshift/oc/pull/165#issuecomment-555026307
> Bug 1775875: pkg/cli/admin/release/extract_tools: Pass []replacements to copyAndReplace

- Makefile
- images/cli-artifacts/Dockerfile.rhel
- oc.spec
In order for console-operator deployment to succeed, cli-artifacts needs to be available on all arches for downloads-openshift-console.  However, in that case, /usr/bin/oc (inherited from cli) is a native binary, and we want to provide all primary Linux architectures to match those on mirror.openshift.com.
In order to do so, this provides cross-compiled Linux binaries for multiple architectures.  Cross-compiling oc fails with gssapi enabled, therefore it is disabled in the cross builds.
Cherry-pick of https://github.com/openshift/oc/pull/153 to 4.2.
> Bug 1773807: Enable all Linux arches in cli-artifacts [4.2]

- pkg/cli/debug/debug.go
Reverts openshift/oc#185
Apparently we can't support RHEL8 container images on RHEL7 nodes, so this isn't going to work on RHEL7 workers.
> Revert "Bug 1777030: Update support tools container image"

- pkg/cli/debug/debug.go
Reverts openshift/oc#196
Apparently we can't support RHEL8 container images on RHEL7 nodes, so this isn't going to work on RHEL7 workers.
> Revert "Bug 1777031: Update support tools container image"

- pkg/cli/admin/release/extract_tools.go
We've been injecting the release version into oc since 13215d7176 (Bug
1715001: when extracting tools from payload, 'oc version' should
report payload version, 2019-09-10, #88), but we want to inject it
into the installer to to avoid potential confusion from:
```console
$ oc adm release extract --command=openshift-install quay.io/openshift-release-dev/ocp-release:4.2.7
$ ./openshift-install version
./openshift-install v4.2.5
built from commit 425e4ff0037487e32571258640b39f56d5ee5572
release image quay.io/openshift-release-dev/ocp-release@sha256:bac62983757570b9b8f8bc84c740782984a255c16372b3e30cfc8b52c0a187b9
```
This commit refactors the split helpers from f55426f91b (Bug 1763728:
fix 'oc adm release extract' version injection, 2019-10-17, #131) with
a single helper that takes a …
> Bug 1773257: pkg/cli/admin/release/extract_tools: Inject release version into installer

- pkg/cli/admin/policy/subject_review.go
- pkg/cli/debug/debug.go
- pkg/cli/process/process.go
> Get rid of unnecessary conversions

- pkg/cli/kubectlwrappers/wrappers.go
We have a bunch of unnecessary wrappers where we should not have. This PR removes them and re-uses the kubectl information where possible.
/assign @damemi
> Clean kubectl wrappers

- pkg/cli/admin/release/image_mapper.go
```
* Fedora CoreOS upgraded from {31.20191213.0 } to {31.20191213.0 Fedora CoreOS}
```
should be
```
* Fedora CoreOS upgraded from 31.20191213.0 to 31.20191213.0
```
Missed this in the previous PR #209
> release: Fix component version display in changelog

- pkg/cli/set/set.go
Removes the extra `set` word in the help statements for `oc set serviceacount --help`
> oc set serviceacount: fix help statements

- pkg/helpers/describe/deployments.go
> Bug 1785513: fix describe for HPA

- pkg/cli/admin/inspect/pod.go
Updates `oc adm inspect` to only gather endpoint information with a certificate to protect against replays.  Also uses cluster-reader permission instead of cluster-admin.
> Bug 1785194: don't gather pod endpoints using tokens

- pkg/helpers/describe/projectstatus.go
* Bugzilla: [When "oc status" run, "panic: runtime error: invalid memory address or nil pointer dereference" is shown](https://bugzilla.redhat.com/show_bug.cgi?id=1788016)
* Version: v4.2
* Description: 
If job spec pointer dereference is nil, the result will be empty string instead of showing wrong result or runtime error.
e.g.>
```
// There is a result without no problem as follows.
$ oc status
In project test on server https://api.ocp4.example.com:6443
job/pi manages perl
created 25 minutes ago 1/1 completed 0 running
// If job spec pointer is nil, the result is empty string instead of runtime error.
$ oc status
In project test on server https://api.ocp4.example.com:6443
job/pi manages perl
```
> Bug 1788088: When "oc status" run, "panic: runtime error: invalid memory address or nil pointer dereference" is shown

- go.mod
- go.sum
- pkg/helpers/cmd/templater.go
- vendor/k8s.io/kubectl/pkg/util/templates/templater.go
- vendor/modules.txt
Don't print usage menu upon error, only print error message. 
/cc @soltysh
> Bug 1778019: If required flag is not passed, don't print usage menu, only print error

- Makefile
- hack/verify-imports.sh
- tools/genman/gen_man.go
This should help us track k/k imports ensuring nobody adds new.
If you look at `hack/verify-imports.sh` script you'll notice there's only 2 big offenders:
- `k8s.io/kubernetes/pkg/credentialprovider`
- `k8s.io/kubernetes/pkg/apis/rbac/v1`
But IIRC those need to be solved upstream too, I'll need to look into it. The next 2 imports should disappear.
> Verify imports

- pkg/cli/set/imagelookup.go
> Bug 1774424: set builder flags so it prints resources when nothing is specified

- pkg/cli/admin/inspect/pod.go
Signed-off-by: Ashish Ranjan <ashishranjan738@gmail.com>
This commit fixes wrong placement of `waitgroup.Add` function in log collection method for `oc adm inspect` command. The `waitgroup.Add` function should be called before the goroutine is called.
> Fixes wrong placement of waitgroup.Add function

- pkg/cli/admin/prune/images/images.go
Kubernetes client-go requires only one authentication method to be present therefore this patch zeroes the content of BearerTokenFile as basic auth is used during prune.
In a nutshell: or we use token based authentication or basic auth, never both at the same time.
Note: This patch is also necessary to fix [Bug 1762837](https://bugzilla.redhat.com/show_bug.cgi?id=1762837)
> Bug 1790978: Zeroing BearerTokenFile for prune.

- pkg/cli/admin/inspect/pod.go
When pods are stopped or crashlooped, they can still have logs.  We want to collect those logs.
You'll need to pick this one too.
> Bug 1792330: pods that are no longer running can still have logs

- pkg/cli/admin/prune/images/images.go
We only need to "ping" the remote registry if we are going to access it
during the prune process. If prune-registry flag is set to false we wont
access it so it makes sense to avoid trying to "ping" it.
> Bug 1762837: Restrict pings to remote registry prior to prune.

- pkg/cli/admin/inspect/namespace.go
we want this so we can see if things like etcd have valid endpoints.
@soltysh needs a pick into 4.3, so you'll want to do a bug dance.  Also, I suspect that you really want to find a way to easily wire this into a service get, not a general namespace blast.
> Bug 1792330: collect endpoints for namespaces

- pkg/cli/admin/catalog/mirror.go
These were being passed to the underlying `mirror` call, but not the underlying `extract` call, which meant that using `--insecure` would fail if talking to an untrusted registry.
> Bug 1790802: Pass security options for `oc adm catalog mirror`

- pkg/cli/admin/catalog/mirror.go
The underlying `mirror` plan will fail if just one source tag does not exist, so placing them all in one call doesn't give us the chance to continue mirroring if one fails.
> Bug 1790798: Mirror images one by one for oc adm catalog mirror

- pkg/cli/admin/catalog/mirror.go
Fixes an issue where destination image references contained digests which the imagesource parser can't handle explicitly.
This is a manual backport for an issue that was already resolved in master but could not be cleanly cherry-picked.
This resolves https://bugzilla.redhat.com/show_bug.cgi?id=1796182
> Bug 1796182: remove destination digests if present

- pkg/cli/admin/release/git.go
Some PRs include things like <title> which break the release viewer
We also escape any instance of ` to prevent odd formatting
> Bug 1798622: oc adm release info: escape PR titles which might contain html

- go.mod
- go.sum
- vendor/github.com/openshift/build-machinery-go/make/lib/golang.mk
- vendor/modules.txt
ART builder are still on 1.13.4
picks up https://github.com/openshift/build-machinery-go/pull/7
/cc @mfojtik @soltysh
> Bug 1801253: Enforce golang only at 1.13.4 level

- pkg/helpers/describe/projectstatus.go
If job spec pointer dereference is nil, the result will be empty string instead of showing wrong result or runtime error.
Reference: https://bugzilla.redhat.com/show_bug.cgi?id=1788016
> Bug 1788016: Suppress nil pointer dereference for job spec

- pkg/cli/newapp/newapp.go
- pkg/cli/newbuild/newbuild.go
Add a warning to `oc new-app` and `oc new-build` if a Jenkins pipeline strategy build was created.
> Bug 1801064: Deprecate Pipelines in new-app/build

- pkg/cli/debug/debug.go
- pkg/helpers/conditions/conditions.go
1 commit:
* [Bug 1771552](https://bugzilla.redhat.com/show_bug.cgi?id=1771552)
In case of bad command passed to oc debug, user will now get information about why the command failed to run, and also will not have to wait the Timeout (15 min)  to get the output.  
2 commit:
* [Bug 1771553](https://bugzilla.redhat.com/show_bug.cgi?id=1771553)
If container exit code != 0, debug cmd should report non-zero
* [Bug 1771549](https://bugzilla.redhat.com/show_bug.cgi?id=1771549)
oc debug pod logs should go to stderr if container exit code != 0
* [Bug 1798549](https://bugzilla.redhat.com/show_bug.cgi?id=1798549)
oc debug node/nodename should fail quickly if debug pod image pull fails
> Bug 1771552: Bug 1771553: Bug 1771549: Bug 1798549: oc debug

- pkg/cli/admin/catalog/mirror.go
- pkg/cli/image/manifest/manifest.go
- pkg/cli/image/mirror/mirror.go
Currently `oc image mirror`, when pointed at a
manifest list digest, checks the contents of the manifest and mirrors
just the underlying image if it contains only a single image.
This change adds an option to mirroring to force the repodigest to
mirror in addition to the underlying image digest. Additionally, it
forces `oc image mirror` and `oc adm catalog mirror` to always
enable this option
https://bugzilla.redhat.com/show_bug.cgi?id=1800674
> Bug 1800674: Option to force RepoDigest mirror

- pkg/cli/admin/release/info.go
we did things like build the suffix then had lots of other strings
to stuff the suffix into. This builds and write the lines to out as
they are needed with no intermediate steps.
> adm release info: refactor to build messages in order

- pkg/cli/newapp/newapp.go
- pkg/cli/newbuild/newbuild.go
> Bug 1801064: Add '\n' for pipeline deprecate info

- pkg/cli/image/mirror/mirror.go
`Complete` gives error `error: you must specify at least one source image to pull and the destination to push to as SRC=DST or SRC DST [DST2 DST3 ...]` if only `--from-dir` is specified even though it is supposed to override `--dir`.
This adds the override logic to Complete like what happens during `Run().plan.Repository`.
> override FileDir with FromFileDir if set in Complete

- pkg/cli/debug/debug.go
> Bug 1801285: set nodeName for debug pod only when explicitly set

- pkg/cli/admin/catalog/build.go
Updates the default image used in the `--from` option of `oc adm catalog build` to the official mirror.
> Bug 1800464: fix(catalog): use registry image from openshift quay namespace

- pkg/cli/admin/release/info.go
We added a new image and the changelog generation failed on that
repo because we had no `oldRepo` set, which caused the command
to exit in 4.5. This guards the loop to exclude those from change
log generation, which will keep them on the new images section.
The `special-resource-operator` is breaking this right now in changelogs
https://openshift-release.svc.ci.openshift.org/releasestream/4.5.0-0.ci/release/4.5.0-0.ci-2020-03-09-193951?from=4.5.0-0.ci-2020-03-08-014740
Unable to show full changelog: could not generate a changelog: fatal: repository '' does not exist error: exit status 128
With this PR it succeeds with:
```
* [special-resource-operator](https://github.com/openshift-psap/special-resource-operator) git [b9bcdca4](https://github.com/openshift-psap/special-resource-operator/com …
```
> release: Changelog fails when new image added

- oc.spec
oc.spec: Update Go to version 1.13
Also moves the Source0 definition below the Name definition so it can be
evaluated correctly by build tools like rpkg.
Also adds versions to Obsoletes and Provides declarations.
> oc.spec: Update to Go 1.13 and make it consumable by 3rd party build services

- pkg/cli/debug/debug.go
/cc @soltysh 
/cc @smarterclayton
> oc debug: add help for --to-namespace

- pkg/cli/set/helper.go
- pkg/cli/set/volume.go
When `--local` is set `info.Mapping` is nil, which causes panics in the
command. Use the external patches method and remove the old helper that no
longer works, and fix places in the error path where we assume mapping is
present. This was missed when the upstream changed.
Also fix bug where --local causes the object to be printed twice.
Needs a test/cmd test
> `set volume` does not work with `--local`

- images/cli-artifacts/Dockerfile.rhel
Places Apache License file in cli-artifacts since Apache License 2.0
requires to give a copy of the license, for example, when publishing
binary on downloads-openshift-console.
> Place apache license in cli-artifacts

- images/tools/Dockerfile
- images/tools/OWNERS
This will ensure every cluster has a tools image available and will
allow oc debug to implicitly use the tools image on any cluster.
Includes git and jq and will allow the tests image to be built on
top of it.
> images: Add a tools image for use with debug and system administration

- pkg/cli/image/imagesource/file.go
Presently disk mirroring via `oc adm release mirror ... --to-dir` creates absolute symlinks in the mirrored release. This means that the absolute path to manifests needs to recreated when transferring the mirrored content into a disconnected environment, or changing the symlinks from absolute to relative.
This PR instead creates relative symlinks in `v2/openshift/release/manifests`, allowing the content to be transferred without modifications.
> Use relative symlinks for disk mirroring

- images/tools/Dockerfile
Currently they are not packaged for that OS.
FYI @jupierce after this merges let me know if we get a green `tools` build.
> images/tools: Remove numactl* packages until they are available on s390x

- images/tools/Dockerfile
It's not truly necessary and complicates downstream images.  I broke origin tests because it tries to clear the root passwd user.
> images/tools: Don't change user

- pkg/cli/admin/release/git.go
- pkg/cli/admin/release/info.go
Only escape those characters.  Necessary to get changelog back to showing quotes correctly.
> release: In markdown output, only < and > are unsafe characters

- contrib/completions/bash/oc
- contrib/completions/zsh/oc
- pkg/cli/image/mirror/mirror.go
Mirrors are complex and it should be possible to mirror "as much as
possible". Adding the flag will still exit with error, but we will
go the full distance.
> image/mirror: Allow `--continue-on-error` for mirror

- pkg/cli/image/manifest/manifest.go
In general we want the world to be schema v2, so mirror should
make a best effort to upconvert as necessary. This logic will
eventually be necessary for OCI registries as well.
> image/mirror: Upconvert v1 schemas to v2 schemas by default

- pkg/cli/debug/debug.go
Now debug uses openshift/tools:latest which is provided by the payload.
> debug: Correctly default the tools image now that it is on the cluster

- pkg/cli/rsh/rsh.go
As of k8s 1.18, kubectl exec expects the command preceded by '--' as seen from the help:
```
Usage:
kubectl exec (POD | TYPE/NAME) [-c CONTAINER] [flags] -- COMMAND [args...] [options]
```
If '--' is not present, kubectl exec prints the following informative message:
```
kubectl exec [POD] [COMMAND] is DEPRECATED and will be removed in a future version. Use kubectl kubectl exec [POD] -- [COMMAND] instead.
```
The message is still informative though given oc rsh does not require additional '--',
it's confusing.
In more detail 1.18 rebase brings the following lines in kubectl exec code:
```
if argsLenAtDash > -1 {
p.Command = argsIn[argsLenAtDash:]
} else if len(argsIn) > 1 {
fmt.Fprint(p.ErrOut, "kubectl exec [POD] [COMMAND] is DEPRECATED and will be removed in a future version. Use …
```
> oc rsh: properly shadow position of --

- pkg/cli/admin/prune/images/images.go
Kubernetes client-go requires only one authentication method to be present
therefore this patch zeroes the content of BearerTokenFile as basic auth
is used during prune.
In a nutshell: or we use token based authentication or basic auth, never
both at the same time.
This is a version of https://github.com/openshift/oc/pull/257
> Bug 1821648: Zeroing BearerTokenFile for prune

- pkg/helpers/source-to-image/git/testhelpers.go
The tests are attempting to perform a git commit but that might
ask people for their password when running `make test-unit` if
they have signing globally enabled. Add "--no-gpg-sign" to
prevent this.
> make unit tests not ask for gpg store password

- pkg/cli/login/loginoptions_test.go
- pkg/helpers/tokencmd/request_token.go
- pkg/helpers/tokencmd/request_token_test.go
The previous check to help decide which CA to use when
performing a login is performed in such a way that fails in most
cases, causing the oauth-server to log `remote error: bad certificate`.
This commit fixes that by retrieving the server cert, closing the
connection and extracting the logic for certificate verification
locally without ruining the handshake with the server.
> Bug 1819688: login: choose the CAs based on the remote server cert

- pkg/cli/login/loginoptions.go
- pkg/cli/project/project.go
- pkg/helpers/kubeconfig/smart_merge.go
- pkg/helpers/project/whoami.go
While trying to use login with tokens (for `oc adm oauth create token`) I realized we had atrophied a bit and it deserved a cleanup.
The primary fix is avoiding printing the token to the screen (the comment was optimistic) and the secondary fix is calling `users.Get("~")` repeatedly to get the same darn data.
> Bug 1825791: Fix a large number of silly things in login

- pkg/cli/admin/release/mirror.go
- pkg/helpers/release/configmap.go
Applying directly to a cluster and writing to a local file are orthogonal actions, and we can do both or neither.  This commit removes previous restrictions from 331c1a1958 (#343) to:
* Allow users to set both flags for a single `oc` invocation.  To support this, some dry-run `continue` were removed, because in the case where all of:
```
--dry-run --apply-release-image-signature --release-image-signature-to-dir=whatever
```
are set, we want to log both the fact that we'd be applying and writing-to-disk each signature, and not log the application but skip over the writing-to-disk log.
* Allow for mirrors that set none of `--apply-release-image-signature`, `--release-image-signature-to-dir`, or `--to-dir`.  This provides backwards compatibility with earlier `oc`, which did not interact with …
> Bug 1825565: pkg/cli/admin/release/mirror: Allow --apply-release-image-signature and --release-image-signature-to-dir

- pkg/cli/admin/upgrade/upgrade.go
Also soften "operator blocking upgrades" to the more generic "update precondition failures", because the cluster-version operator may learn about other preconditions with time.  The warning is intended to raise awareness about `--force` being an "I've exhausted all other options and performed a bunch of undocumented manual verification" safety valve, and not something that anyone should be doing frequently.
> Bug 1826533: pkg/cli/admin/upgrade: Warn when --force is used

- OWNERS_ALIASES
- pkg/cli/admin/upgrade/OWNERS
These to subcommands interact with the cluster-version operator, which is now maintained by the updates team.  I'm seeding the alias with the content from [the CVO][1].  I've left the `component` property (added to the root `OWNERS` in e83f2ac9ae, #367) off for now, because the tooling around that only consumes entries at the repo level.
[1]: https://github.com/openshift/cluster-version-operator/blob/914467c03b5bc25dbe4c9295c420fdb2598db821/OWNERS
> pkg/cli/admin/upgrade: Delegate to update-approvers

- pkg/cli/admin/upgrade/upgrade.go
To raise awareness that users are initiating an update which was not recommended by their configured Cincinnati upstream, so they are on the hook for validating its stability.
> Bug 1826533: pkg/cli/admin/upgrade: Warn when --allow-explicit-upgrade let you through

- pkg/cli/admin/upgrade/upgrade.go
To raise awareness that users are initiating or re-targeting an update despite their cluster being unhealthy, which may help (updating to a fixed release) or hurt (re-targeting a 4.1 -> 4.2 update to start installing 4.3 components, which will not play nicely with any remaining 4.1 components).  This is bit ugly due to the two `checkForUpgrade` callsites, although I haven't tried to DRY that up.  And I've done some minimal shuffling so `checkForUpgrade` returns error messages that [are lowercased][1] and which can still be used in both warning strings and fatal messages.
[1]: https://github.com/golang/go/wiki/CodeReviewComments#error-strings
> Bug 1826533: pkg/cli/admin/upgrade: Warn when --allow-upgrade-with-warnings let you through

- pkg/cli/admin/upgrade/upgrade.go
Adding a client-side guard like [the server-side guard][1] from openshift/cluster-version-operator@55e3cb450f (openshift/cluster-version-operator#170).  This isn't that big a deal, because the client-side guard exists, but it does save users the effort of pushing a by-tag pullspec into ClusterVersion and then having to circle back around to notice that the cluster-version operator is complaining about the verification failure.
The warning on `--force` (instead of a hard failure) is because @smarterclayton considers blocking this flow completely to be a breaking API change, and also considers that failing those folks early is more invasive than letting them continue to slip through here and have some subset of them potentially blow up later if:
1. You ask to update to a by-tag pullspec.
2. …
> Bug 1826533: pkg/cli/admin/upgrade: Client-side by-tag guard

- pkg/cli/project/project.go
- pkg/cli/status/status.go
It can happen a project is no longer available when running the status.
Right now, oc status considers "namespaces XXX not found" error message
as valid and keeps querying for services, deployment, etc. over
on-existing namespace.
New output for non-existing namespaces:
```
$ oc status
error: the project "jenkins-csb-skynet" specified in your config does not exist.
```
> bug 1826676: oc status: check if the current project exists before printing status

- pkg/cli/create/routereenecrypt.go
* `pkg/cli/create/routereenecrypt.go` (`reencryptRouteLong`): Indicate that `--dest-ca-cert` is optional and that the destination CA certificate defaults to the service CA.
(`reencryptRouteExample`): Omit `--dest-ca-cert` from one example.
(`NewCmdCreateReencryptRoute`): Omit `--dest-ca-cert` from the synopsis as the flag is optional and is already mentioned in the description and flags sections. Document the default behavior when `--dest-ca-cert` is omitted.
---
@openshift/openshift-team-network-edge
> Bug 1835997: create route reencrypt: Improve --dest-ca-cert help

- pkg/cli/admin/catalog/mirrorer.go
- pkg/cli/admin/catalog/mirrorer_test.go
Catalogs may reference image pull specs without a tag or digest, with
the expectation that the tag "latest" will be assumed.
> Bug 1827073: Support mirroring catalogs using default-tagged source images.

- pkg/cli/admin/release/extract.go
- pkg/cli/admin/release/mirror.go
- pkg/cli/admin/release/new.go
The command fails when specifying a non-default from directory because
the from directory was not passed to either extract or mirror. Add that
transformation.
Fixes 
```
oc adm release mirror --from-dir=X --from=file://Y:Z
error: blob unknown
```
because mirror was looking for Y:Z in the current dir, not X.
Also include the Parallel options as good practice even if they are
not heavily used in these flows.
> Bug 1806779: Mirroring from custom directory via oc adm release mirror fails

- pkg/cli/project/project.go
- pkg/cli/status/status.go
This PR clarifies error message for `oc status` and `oc project` when run from context of a deleted namespace. 
/cc @ingvagabund 
closed https://github.com/openshift/oc/pull/417, opened this
> Bug 1835011: improve error for 'oc project' and 'oc status' when project doesn't exist

- pkg/helpers/tokencmd/request_token.go
- pkg/helpers/tokencmd/request_token_test.go
/assign @stlaz 
In https://github.com/openshift/oc/commit/eabf7a06457d4c645167cb150167fb3076bb2899 you moved to `tls.Dial` the problem is that it does not use proxy, when one is specified. It needs to wrapped in a full http client to consume one, when needed.
> Bug 1837375: use http.Client.Head instead of tls.Dial to be able to consume proxy settings

- pkg/cli/login/loginoptions.go
- pkg/cli/project/project.go
- pkg/helpers/describe/projectstatus.go
- pkg/helpers/errors/login.go
This PR updates return msg to users that cannot create projects for `oc login`, `oc new-project`, and `oc project`
If ProjectRequestMessage is set, and user without self-provisioner clusterrole logs in or tries to create  projects, return the ProjectRequestMessage. This is consistent with console.  
If no ProjectRequestMessage set, then return the same message for login|project|new-project: 
```console
$ oc project
You may not request a new project via this API.
```
`oc project` without this PR is misleading:
```console
$ oc project
No project has been set. Pass a project name to make that the default.
```
see comment below to set projectRequestMsg and remove self-provisioner clusterrole
> Bug 1802580: return ProjectRequestMessage if it is set with login,project cmds

- pkg/helpers/groupsync/rfc2307/ldapinterface.go
While testing, noticed that https://github.com/openshift/oc/pull/405 only covered for ActiveDirectory, but  with RFC 2307, out of bounds search was still resulting in error, not warning.
> Bug 1838838: oc adm group sync - search outside base dn warning - RFC 2307

- pkg/cli/admin/catalog/mirror.go
`oc adm catalog mirror` initially targeted "registry images" built via `oc adm catalog build`.
Newer `opm` tooling creates index images with slight differences. This PR accounts for them in two ways:
- The database folder has always been configurable, but the database name was hardcoded to bundles.db. The first commit removes the hardcoding, so index images could be supported via the `--path` flag.
- `mirror` now detects the "index label", if present, and uses that to find the database in the image. `--path` takes precedence, if present.
> Bug 1829832: support mirroring for index images

- pkg/cli/admin/policy/authz_helpers.go
- pkg/cli/admin/policy/modify_roles.go
- pkg/cli/admin/policy/modify_scc.go
- pkg/cli/admin/policy/modify_scc_test.go
This is new version of https://github.com/openshift/origin/pull/22781 with some changes.
I'll need to update tests too. 
/assign @stlaz
> Bug 1833558: create ClusteRole and ClusterRoleBinding when invoking oc adm policy add-scc-to-user

- pkg/cli/admin/catalog/mirror.go
- pkg/cli/admin/catalog/mirror_test.go
This fixes a regression introduced in 4.5, where ICSP sources were generated with digests. This causes unnecessary churn on clusters when no new repos have been added during a catalog update.
> Bug 1842582: Don't include digest in source for ICSP when mirroring a catalog

- pkg/cli/admin/release/extract.go
- pkg/cli/admin/release/mirror.go
- pkg/cli/admin/release/new.go
The command fails when specifying a non-default from directory because the from directory was not passed to either extract or mirror. Add that transformation.
Also include the Parallel options as good practice even if they are not heavily used in these flows.
Backporting e1567dd1f291bc2264c6423afa17a4084ee900ee (#424) and resolving a context conflict because 4.4 does not include 2725cfa7ce (#358).
> Bug 1806780: release: Mirroring from custom directory via oc adm release mirror fails

- pkg/cli/project/project.go
- pkg/cli/requestproject/request_project.go
```
$ oc config get-contexts
CURRENT   NAME                                                                               CLUSTER                                                       AUTHINFO                                                                   NAMESPACE
admin                                                                              test0531                                                      admin                                                                      
admin-jchaloup                                                                     jchaloup-20200601                                             admin-jchaloup                                                             
default/api-test0531-group-b-devcluster-openshift-com:6443/system:admin …
```
> bug 1840411: oc project: respect --context flag

- pkg/cli/admin/inspect/eventFilterPage.go
- pkg/cli/admin/inspect/inspect.go
- pkg/cli/admin/inspect/pod.go
- pkg/cli/admin/inspect/port_forward.go
- pkg/cli/admin/inspect/util.go
- pkg/cli/admin/mustgather/mustgather.go
The event filter is based on free jqgrid available here: https://github.com/free-jqgrid/jqGrid/. jqGrid is a popular jQuery Plugin for displaying and editing data in tabular form.
This is built on the top of PR https://github.com/openshift/oc/pull/448.
> Add event filter and complete event json to inspect the must-gather results

- pkg/cli/cli.go
- pkg/cli/kubectlwrappers/wrappers.go
> Bug 1843929: use wrapper for kustomize sub-command

- pkg/cli/project/project.go
```
$ oc config get-contexts
CURRENT   NAME                                                                                     CLUSTER                                                       AUTHINFO                                                                   NAMESPACE
admin                                                                                    jchaloup-20200618                                             admin                                                                      
admin-groupb                                                                             test0616                                                      admin-groupb                                                               
hongkliu-test/api-jchaloup-20200618-group-b-devcluster-openshift-com:64 …
```
> bug 1840411: oc project: rewrite context after kubeconfig is read

- pkg/cli/admin/inspect/inspect.go
- pkg/cli/admin/inspect/resource.go
- pkg/cli/admin/inspect/util.go
This allows `oc adm inspect co` to run 90 seconds for me locally against my aws cluster.
> make oc adm inspect run in parallel and remove rate limits

- pkg/cli/admin/catalog/mirror.go
Didn't `Complete` the options, which was skipping parsing the flag into a regex, causing matches to fail.
> Bug 1851817: fix filter-by-os parsing for oc adm catalog mirror

- pkg/cli/admin/inspect/inspect.go
- pkg/cli/admin/inspect/resource.go
- pkg/cli/admin/inspect/util.go
This reverts commit 7ec02e2eacdf66c5a6b77e44ee779398d5aee80b.
https://github.com/openshift/origin/pull/25239 nerfed a test that demonstrated that we broke must gather. We need to fix must-gather, not nerf the test for our data collection.  
looking at it, https://github.com/openshift/oc/pull/449 appears to be a good candidate, though it's not obvious why at first glance.
> bug 1829243: Revert "run inspect in parallel"

- pkg/cli/admin/release/extract.go
- pkg/cli/admin/release/mirror.go
- pkg/cli/admin/release/new.go
This picks #327 and #446 back to release-4.3. #327 picks back cleanly (see #456), and I'm recycling the bot's 95de610 in this PR. #446 does not pick back cleanly, because release-4.3 lacks release-4.4's #426. I've resolved the minor context conflict manually to create dbe3f73.
> Bug 1806782: Allow a file:// release argument to release mirror

- pkg/cli/image/manifest/manifest.go
- pkg/cli/image/mirror/mirror.go
- pkg/cli/image/mirror/plan.go
Add warning when mirroring SchemaVersion:1 images that digests are not preserved.
Also, update TODOs with functions handling schema conversions to drop support for Schema v1 in future release.
>  Bug 1850931: 'oc image mirror' Add warning when mirroring SchemaVersion:1 images

- pkg/cli/create/create.go
- pkg/cli/create/user_identity_mapping.go
/assign @damemi 
This was broken in https://github.com/openshift/oc/pull/460
> create: fix create useridentitymapping

- pkg/cli/admin/release/info.go
If a metadata field has an empty string, map, or array, there isn't
huge value in showing it to a human viewer. The data will still be
present in `-o json`.
Correct a bug where `Metadata:` is printed multiple times, one per
key.
> release: Hide empty metadata fields in release info

- OWNERS_ALIASES
- pkg/cli/admin/catalog/OWNERS
This command is related to building and mirroring the catalog.
Seeding the alias with ecordell for now.
> pkg/cli/adm/catalog: Delegate to catalog-approvers

- pkg/cli/admin/mustgather/mustgather.go
oc adm must-gather is creating a pod which is getting scheduled on
Windows nodes. This commit changes the podspec to include a linux
node selector.
> Bug 1861559: Only schedule must-gather pod on Linux nodes

- pkg/cli/admin/inspect/event_filter_html.go
Old event filter page had a column for the related object (involvedObject), which is missing in the new event filter. Adding it back.
> inspect: add back related object (involvedObject) column

- pkg/cli/logout/logout.go
Since openshift/enhancements#323, oc logout should delete the object name of oauthaccesstoken instead of token value.
And I didnt **import** [openshift/oauth-server](https://github.com/openshift/oauth-server),because this fix  just needs few funcs from that repo.
> Bug 1868324: oc logout should make the token invalid

- pkg/helpers/release/verify.go
I am not able to reproduce the info messages reported in the bug.  I do see the messages are double printed, though.  There might be a good reason why these are both printing klog.Infof and klog.V(4)? 
/cc @smarterclayton
> Bug 1866876: Signature verify error msgs to klog.V(4) rather than klog.Infof

- pkg/cli/admin/release/new.go
With this cmd and a single auth file that contains the creds to quay.io/openshift-release-dev: 
`$ oc adm release new --from-release registry.svc.ci.openshift.org/ocp/release:4.6.0-0.nightly-2020-08-17-150352 --to-image quay.io/sallyom/origin-release:latest -a ~/installer/pull-secret`  
This fails when trying to push to quay.io/sallyom.  The message isn't clear on which registry/repository is failing auth.
With this PR, the error msg is more clear: 
`error: failed to push image quay.io/sallyom/origin-release:latest: unauthorized: access to the requested resource is not authorized`  
(b4 this PR error is this: `error: unauthorized: access to the requested resource is not authorized` with no indication of which auth failed)
> Bug 1867594: Clarify which registry/repository fails with unauthorized

- pkg/cli/admin/prune/images/images.go
- pkg/cli/admin/prune/images/images_test.go
Pruner attempts to derive internal image registry host from the last
unmanaged image or from the last image stream created. In some cases
OpenShift may not contain any of those (for instance in a fresh install
with Removed registry), this makes pruner to fail even with the flag
--prune-registry set to false.
This commit allows the pruner job to move on with the --prune-registry
flag set to false even when we can't derive the internal registry host.
> Bug 1867792: Allow prune to move on with Removed registry

- pkg/cli/admin/mustgather/mustgather.go
`oc adm must-gather` should use `ImagePullPolicy: "Always"`? 
issue this PR resolves: 
```
Run oc adm must-gather --image docker.io/sallyom/must-gather:local then look at pod yaml of must-gather pod:
(pod yaml snippet)
start with:
image: docker.io/sallyom/must-gather:local
imageID: docker.io/sallyom/must-gather@sha256:b20516b99edb0dd40010f4084b16117e936863dd25ea24b363489
committed and pushed new image id to docker.io/sallyom/must-gather:local
with "IfNotPresent" imagePullPolicy:
image: docker.io/sallyom/must-gather:local
imageID: docker.io/sallyom/must-gather@sha256:b20516b99edb0dd40010f4084b16117e936863dd25ea24b36348961cb4a
with "Always" imagePullPolicy:
image: docker.io/sallyom/must-gather:local
imageID: docker.io/sallyom/must-gather@sha256:21aed5526cbc8db38c350cc74c575 …
```
> Bug 1866380: must-gather ImagePullPolicy should be 'Always'

- pkg/cli/admin/release/OWNERS
Some subcommands within the release package interact with the
cluster-version operator, which is maintained by the updates (OTA) team.
> pkg/cli/admin/release: Delegate to update-approvers

- pkg/cli/admin/mustgather/mustgather.go
This cuts down must-gather time by ~2 min.
> Bug 1866399: Shorten retry interval in must-gather

- pkg/cli/image/manifest/manifest.go
- pkg/cli/image/mirror/mirror.go
- pkg/cli/image/mirror/plan.go
A foreign image layer has a URL that points outside the current registry, such that the registry returns not found if the blob
is requested. Since mirror attempts to ensure the destination image can be pulled, even in the presence of disjoint networks,
and given that the Docker daemon will by default attempt the blob lookup first before checking URLs, always copy the blob
by checking the source registry, then trying to pull the layer URLs.
There may be scenarios where this is not desirable, and a future change may allow skipping mirror of those blobs.
> Bug 1872709: Copy foreign layers from external sources during mirroring

- pkg/cli/admin/inspect/namespace.go
Adds `endpointslices` to the resource list in the `namespaceResourcesToCollect()` function. This way, `oc adm inspect ns/<namespace>` will collect all EndpointSlices resources and place them in `namespaces/<namespace>/discovery.k8s.io/endpoints.yaml`. 
The [OpenShift Router](github.com/openshift/router) uses `EndpointSlices` by default in 4.6, so this change is needed to add `EndpointSlices` resources to `must-gather` outputs on a per-namespace basis in 4.6.
> Bug 1872363: Add EndpointSlices to list of namespace resources to collect

- pkg/cli/admin/upgrade/upgrade.go
When `Upgradeable=False`, the cluster-version operator will block (usually) minor version bumps.  [Sometimes][1] it will block all version bumps.  Users running `oc adm upgrade` should be notified about these conditions, so they are not surprised if they choose a target and the CVO subsequently blocks the chosen update.
[1]: https://bugzilla.redhat.com/show_bug.cgi?id=1822844
> Bug 1874293: pkg/cli/admin/upgrade/: Mention Upgradeable=False

- pkg/cli/admin/mustgather/mustgather.go
Increase retry intervals in must-gather. 3s proved too short for some,
resulted in too many retries.  10s is a fine compromise.
> Bug 1866399: lessen retries in must-gather

- pkg/cli/admin/mustgather/mustgather.go
Without this, 'oc adm must-gather' fails when defaultNodeSelector is set and the
must-gather namespace is created on a node without the matching labels.
This PR adds the annotation 'openshift.io/node-selector: ""' to the
must-gather namespace to override a configured defaultNodeSelector.
/cc @deads2k
> Bug 1812813: oc adm must-gather: add empty node-selector annotation to namespace

- pkg/cli/image/mirror/mirror.go
Was introduced during mirror changes accidentally.
> mirror: Log line is accidentally being printed at V(0) instead of V(5)

- pkg/cli/admin/mustgather/mustgather.go
Move `gather` container from init containers into containers so the pod does not stay in `Pending` state until gather container is finished. Otherwise, `KubePodNotReady` alert gets triggered.
Once the gathering phase is finished, must-gather pod drops to NotReady state since `gather` container terminates:
```
NAME                READY   STATUS     RESTARTS   AGE
must-gather-sr295   1/2     NotReady   0          4m18s
```
Having a pod in `NotReady` status might still be better than having it in `Pending`. The copy phase should take less than the gathering one (depending on the network bandwidth).
Backporting https://github.com/openshift/oc/pull/540
> bug 1875551: must-gather: move gather init container under containers

- images/cli-artifacts/Dockerfile.rhel
- images/cli/Dockerfile.rhel
oc is currently dynamically linked, which is needed for gssapi support.
Dynamically linked RHEL 8 binaries will not run on RHEL 7 because of
dependencies on GLIBC_2.28 symbols.
> Bug 1879081: Build cli images with RHEL 7

- pkg/cli/admin/inspect/inspect.go
- pkg/cli/admin/inspect/resource.go
- pkg/cli/admin/inspect/util.go
This brings back commit 7ec02e2eacdf66c5a6b77e44ee779398d5aee80b which was reverted as a culprit to https://bugzilla.redhat.com/show_bug.cgi?id=1861746 which it actually was not.
> Bug 1861746: run inspect in parallel

- pkg/cli/secrets/link.go
- pkg/cli/secrets/unlink.go
Changing `oc [un]link` to `oc secrets [un]link` in the help text
> bug 1880959: oc secrets link/unlink: fix missing secrets keyword in the command help

- pkg/cli/admin/mustgather/mustgather.go
/cc @deads2k 
/assign @mfojtik
> Bug 1861746: must-gather: always force disk flush after in the copy container

- go.mod
- go.sum
- vendor/modules.txt
This PR bumps library-go to get changes from openshift/library-go#898: bitbucket.org/ww/goautoneg is no longer available, and it is replaced by github.com/munnerz/goautoneg (which is already vendored and has the same content).
> Bug 1872520: Replace bitbucket.org/ww/goautoneg with its mirror

- pkg/cli/admin/release/new.go
Looks like the correct word in the help should be `precede`
> cli/admin/release/new: typo fix

- images/cli/Dockerfile.rhel
Updating openshift-enterprise-cli builder & base images to be consistent with ART
Reconciling with https://github.com/openshift/ocp-build-data/tree/990044f295fb1d5e238823902962dbcfa1c041c9/images/openshift-enterprise-cli.yml
> Bug 1878163: Updating openshift-enterprise-cli builder & base images to be consistent with ART

- pkg/helpers/source-to-image/git/url.go
- pkg/helpers/source-to-image/git/url_test.go
Turns our we do not vendor in openshift/source-to-image, but copy some of its packages into openshift/oc
Assuming there is a rationale / history on that, and am not going to bother altering the apporach.
So I'm porting our recent fix https://github.com/openshift/source-to-image/commit/129c90e36fec88dae5e2910a0de4082836e1b623
/assign @adambkaplan 
> Bug 1884270: bypass golang url parsing with scp styled ssh git URLs; refactor URL for older git clients

- pkg/cli/login/login.go
- pkg/helpers/tokencmd/basicauth.go
- pkg/helpers/tokencmd/basicauth_test.go
- pkg/helpers/tokencmd/request_token.go
- pkg/helpers/tokencmd/request_token_test.go
* If a user provides `oc login -u anything`, try for basic auth prompt. 
* If only password IDP available, and no username was provided, show the tokenURL message instead of basic auth prompt.
> oc login: Show tokenURL message if only IDP is basic and user has not provided username

- pkg/helpers/image/dockerlayer/add/add.go
If we don't close this pipe reader with an error we ended up having a
deadlock as we keep trying to read indefinitely from it. This deadlock
causes the error message to be misguiding when attempting to upload a
layer with invalid format (gzip: invalid header).
Without this patch oc image append using an invalid layer format fails
with either "timeout" (docker.io) or "protocol error" (quay.io) instead
of reporting appropriate error ("invalid gzip").
> Bug 1885179: Avoid deadlock by closing pipe reader end

- images/cli-artifacts/Dockerfile.rhel
Updating ose-cli-artifacts builder & base images to be consistent with ART
Reconciling with https://github.com/openshift/ocp-build-data/tree/f66c03011773dc3755ad874fc691be612914d65f/images/ose-cli-artifacts.yml
Depends on https://github.com/openshift/oc/pull/606 . Allow it to merge and then run `/test all` on this PR.
> Updating ose-cli-artifacts builder & base images to be consistent with ART

- images/deployer/Dockerfile.rhel
Updating openshift-enterprise-deployer builder & base images to be consistent with ART
Reconciling with https://github.com/openshift/ocp-build-data/tree/f66c03011773dc3755ad874fc691be612914d65f/images/openshift-enterprise-deployer.yml
Depends on https://github.com/openshift/oc/pull/606 . Allow it to merge and then run `/test all` on this PR.
> Updating openshift-enterprise-deployer builder & base images to be consistent with ART

- images/cli/Dockerfile.rhel
Updating openshift-enterprise-cli builder & base images to be consistent with ART
Reconciling with https://github.com/openshift/ocp-build-data/tree/f66c03011773dc3755ad874fc691be612914d65f/images/openshift-enterprise-cli.yml
Depends on https://github.com/openshift/images/pull/44 . Allow it to merge and then run `/test all` on this PR.
> Updating openshift-enterprise-cli builder & base images to be consistent with ART

- images/tools/Dockerfile
Updating ose-tools builder & base images to be consistent with ART
Reconciling with https://github.com/openshift/ocp-build-data/tree/f66c03011773dc3755ad874fc691be612914d65f/images/ose-tools.yml
Depends on https://github.com/openshift/oc/pull/606 . Allow it to merge and then run `/test all` on this PR.
> Updating ose-tools builder & base images to be consistent with ART

- images/cli-artifacts/Dockerfile.rhel
Updating ose-cli-artifacts builder & base images to be consistent with ART
Reconciling with https://github.com/openshift/ocp-build-data/tree/990044f295fb1d5e238823902962dbcfa1c041c9/images/ose-cli-artifacts.yml
Depends on https://github.com/openshift/oc/pull/596 . Allow it to merge and then run `/test all` on this PR.
> Bug 1878163: Updating ose-cli-artifacts builder & base images to be consistent with ART

- Makefile
- hack/generate-versioninfo.sh
This was previously enabled in 4.1 but was lost in 4.2 when oc was split
out from the origin repository.
> Bug 1891555: Create Windows version information

- pkg/cli/admin/release/extract.go
Fix typo (omission of 'adm release')  in "oc adm release extract" help
> fix help for 'oc adm release extract'

- pkg/cli/image/mirror/mirror.go
Somebody (me) wrote this `--filter-by-os=/*` as example of how to list/mirror all digests of a multi-arch image with the wildcard filter-by-os.  This PR fixes the help to show `--filter-by-os=.*` instead.
> show proper wildcard for 'oc image mirror --help example'

- pkg/cli/admin/mustgather/mustgather.go
- pkg/cli/admin/mustgather/mustgather_test.go
This is the only reasonable image we can probably fall-back to, although I'm a bit hesitant on using it here. 
/assign @wking
> Bug 1888738: fall-back must-gather to official RH supported image

- oc.spec
This is needed after https://github.com/openshift/oc/pull/623
> Bug 1891555: BuildRequires goversioninfo

- Makefile
When building in OCP, this variable is set with the intended version
information.
For CI versions, annotated tags (releases) need to be created.  This 
used to occur in openshift/origin but hasn't regularly since this was 
split out.
> Bug 1891555: Accept OS_GIT_VERSION to set version information

- go.mod
- pkg/cli/admin/prune/imageprune/prune.go
- pkg/cli/admin/prune/imageprune/prune_test.go
- pkg/helpers/image/test/util.go
- vendor/modules.txt
This PR adds support of OCI images to the pruner. The pruner should
1. keep blobs that are used by OCI images (even if they are no longer used by other schema 1 or schema 2 images)
2. delete config/layers of OCI images if they are no longer used by any image
> IR-112: Pruner should be aware of OCI image configs

- pkg/cli/observe/observe.go
With this PR you can now `oc observe` any resource on the cluster, not just the built-in. So before `oc observe clusteroperator` was not possible, now it will work smoothly. 
> observe: support CRDs

- pkg/cli/admin/release/mirror.go
- pkg/cli/admin/release/mirror_test.go
The recent `oc adm release mirror` fix to add the image sources for --to-release-image along with --to introduced a bug where it is possible to get duplicate image sources when --to and --to-release-image have the same registry/repo/name.  This PR adds de-duplicate code to the printed image sources.
> Bug 1903033: deduplicate imageContentSources printed when mirroring release

- pkg/cli/admin/verifyimagesignature/verify-signature.go
/assign @sallyom 
There are two possible approaches to this problem:
1. the one from this PR
2. allowing injecting `--registry-config` similarly to how we do that in `oc image mirror`
what do you think which one would be better?
> Bug 1890671: use proper username for image verification

- pkg/cli/image/manifest/manifest.go
- pkg/cli/image/mirror/mirror.go
With this PR, the `--keep-manifest-list=true` command will fail if `--filter-by-os` is passed with any value other than `--filter-by-os=.*`. This is because it is not possible to preserve the manifest list digest while also altering the manifest list to only include some of its manifests (you could, but it would be rejected by registries as it will no longer be valid). Before this PR, `--keep-manifest-list=true` did not actually keep the manifest list digest, in cases where the `--filter-by-os=not/wildcard`, a new manifest list with a new digest was created. 
This PR also addresses https://bugzilla.redhat.com/show_bug.cgi?id=1882689
/assign @smarterclayton
> Bug 1890951: Improve output of 'oc image mirror' with multi-arch images

- pkg/cli/debug/debug.go
As discussed in the bugzilla report, creating the debug namespace that can override admin configured defaultNodeSelector gives too much privilege to oc and breaks the contract of debug in that you change the context you are running in. 
We are reverting this change in favor of the original workaround, that is, for the admin to create a new debug namespace with the empty node-selector and then direct oc to use that namespace for debugging.
```
$ oc adm new-project debug --node-selector=""
$ oc debug node/<node> -n debug
```
> REVERT: Bug 1812813: oc debug node: create debug namespace with empty node-selector annotation #550

- pkg/cli/admin/release/mirror.go
Fixing a bug from e575833cd4 (#646), where untranslated architectures would fail [with][1]:
error: unable to push manifest to local-registry.apps.pravind.redhat.com:5000/ocp4/openshift4:4.7.0-0.nightly-ppc64le-2020-12-21-131639=ppc64le-prometheus: invalid tag format
because tags are usually restricted to [`[\w][\w.-]{0,127}`][2], and [`\w` is `[0-9A-Za-z_]`][3].  That means `=` is not a valid character.
[1]: https://bugzilla.redhat.com/show_bug.cgi?id=1878972#c14
[2]: https://github.com/containers/image/blob/a5061e5a5f00333ea3a92e7103effd11c6e2f51d/docker/reference/regexp.go#L36-L37
[3]: https://github.com/google/re2/wiki/Syntax
> Bug 1878972: pkg/cli/admin/release: Use '-', not '=', for untranslated arches

- pkg/cli/admin/prune/imageprune/prune.go
- pkg/cli/admin/prune/imageprune/prune_test.go
- pkg/cli/admin/prune/images/images.go
- pkg/helpers/image/test/util.go
This commit makes image pruner aware of StatefulSets, Jobs and CronJobs existing in the cluster.
> Bug 1880068: Take StatefulSets, Jobs and CronJobs into account during image prune

- pkg/cli/admin/release/extract.go
`oc adm release extract`: with --credentials-requests flag, only write the credentials requests manifests, don't write _all_ the manifests.
> Bug 1908484: credentials-requests extract only write creds requests not all manifests

- pkg/cli/image/manifest/manifest.go
The warning issued when oc chooses an os/arch digest from a manifest list should not include the suggestion to run --keep-manifest-list=true, since that flag is only exposed during mirroring. the warning is issued with oc imageextract _and_ mirror
warning comes from `ProcessManifestList`, exercised with extract & mirror, however
`oc image extract` --keep-manifest-list is not exposed
`oc image mirror` --keep-manifest-list is exposed
> Bug 1914452: Fix the manifest list warning when choosing an os/arch digest from list

- pkg/helpers/newapp/app/dockerimagelookup.go
Provide msg for UnuathorizedError with `oc new-app` 
Example: (private image quay.io/sallyom/podescape-io:test)
Before this PR:
```console
$ oc new-app --docker-image=quay.io/sallyom/podescape-io:test
error: unable to locate any local docker images with name "quay.io/sallyom/podescape-io:test"
```
With this PR:
```console
$ oc new-app --docker-image=quay.io/sallyom/podescape-io:test
W0108 17:39:59.507884 3164436 dockerimagelookup.go:240] container image remote registry lookup failed: you may not have access to the container image "quay.io/sallyom/podescape-io:test"
error: unable to locate any local docker images with name "quay.io/sallyom/podescape-io:test"
```
> Bug 1890995: oc new-app: provide message for unauthorized error with image lookup

- pkg/cli/image/extract/extract.go
- pkg/cli/image/info/info.go
- pkg/cli/image/manifest/manifest.go
- pkg/cli/image/mirror/mirror.go
- vendor/github.com/docker/distribution/manifest/ocischema/builder.go
- vendor/github.com/docker/distribution/manifest/ocischema/manifest.go
- vendor/modules.txt
oc was burying image not accessed error messages with "image does not exist" message
([Bug 1890677](https://bugzilla.redhat.com/show_bug.cgi?id=1890677))
This PR gives more information about why an image was not found - and clarifies error to be `image not found` rather than `image does not exist` 
Also, added the `ocischema` package to register OCI media types w/ oc  (the error from the bug report will no longer be an error)
> Bug 1890677: oc image: Include error msg when image not found and register oci schema for mediatypes

- pkg/cli/image/append/append.go
- pkg/cli/image/extract/extract.go
Clarify in help menu that `--filter-by-os=.*` is not supported with `oc image extract` and `oc image append`. 
> Bug 1906276: oc image append|extract: clarify help for --filter-by-os

- pkg/cli/importimage/importimage.go
Following our discussions on https://github.com/openshift/oc/pull/679 this PR makes `oc help image-import` to contain an example of `--request-timeout` flag usage.
> Bug 1878022: Improving import-image help messages

- pkg/cli/admin/mustgather/mustgather.go
- pkg/cli/rsh/rsh.go
- pkg/cli/rsync/copy_rsync.go
There are 2 main issues with `oc adm must-gather` that this PR addresses:
1. On the env, the logs streaming from gather pod ends after ~10min, when the gather runs longer and on that cluster I was given access it was taking ~30mins, you'll only get info about the initial 10mins. The time-out is coming from server, so we just need to ensure we re-try streaming logs after that time-out if the pod is still running.
2. Current copy logic is missing compression.
3. Current sync logic is copying the artifacts only once, if it fails it doesn't re-try. 
> Bug 1888192: add rsync & log re-tries

- pkg/cli/shim_kubectl.go
/assign @deads2k 
Example invocation with this PR:
```
$ ./oc annotate --local -f ../origin/test/extended/testdata/deployments/deployment-simple.yaml x=y
W0111 14:15:50.202062   44273 shim_kubectl.go:55] Using non-groupfied API resources is deprecated, update apiVersion to "apps.openshift.io/v1" for your resource
deploymentconfig.apps.openshift.io/deployment-simple annotated
```
> Bug 1914894: warn users about using non-groupified resources

- Makefile
- docs/generated/.gitignore
- hack/clibyexample/OWNERS
- hack/clibyexample/template
Looks like we missed those when moving from origin repo.
Sample output after running `make generate-docs`: https://gist.github.com/soltysh/526b047401dad67e1558068f535ef558
> Add missing docs generation tools

- pkg/cli/image/extract/extract.go
This patch adds possibility to extract file from the root directory of an image.
Closes: BZ#1919032
> Bug 1919032: Fix image extract from Root Directory

- pkg/cli/registry/login/login.go
This added help text is necessary because it's easy to forget you have a connected cluster (especially when kubeconfig is unset but there's the file in the default ~/.kube/config). If you forget you are currently connected, then it's easy to forget that `oc registry login localhost:5000` will write the authentication token from the connected cluster (for current context) as the  
```
"localhost:5000": {
"auth": "thiswouldbewrong"
```
when what you _probably_ want is `oc registry login localhost:5000 --auth-basic=user:password`
> Add help text to 'oc registry login' when using --registry flag

- pkg/cli/image/append/append.go
- pkg/cli/image/extract/extract.go
/assign @smarterclayton 
This flag `--dir` ~does not make sense~ wrt `oc image extract` and is confusing because it lends to the misconception that with it one can choose where to extract contents of an image into. ~It also is not wired properly~  This PR exposes the flag `--to-dir` to add the ability for users to designate where to extract image contents to on disk. 
`--dir` is used elsewhere and in most cases is misleading. 
This PR clarifies and updates the flags `--dir, --to-dir, --from-dir`.
For example with `oc image mirror`:
`'--dir='': The directory on disk that file:// images will be copied under'`
`oc image info`:
`--dir='': The directory on disk that file:// images will be read from.`  
And here is an example of `--dir`  with both meanings of the flag:
```console
$ oc image …
```
> Bug 1904006: update and clarify --dir --from-dir flags with 'oc image'

- pkg/cli/admin/inspect/secret.go
still hides the secret content, but let's you know how many bytes it was.
> indicate how many bytes the hidden secret key was

- pkg/cli/login/loginoptions.go
When using oc login with option --insecure-skip-tls-verify=true,
server certificate checkings are performed on an initial HEAD request
sent to the cluster and may lead to unexpected errors (e.g tls timeout)
preventing the user from logging eventhough he/she had intentionally
requested to skip them.
(picked from https://github.com/openshift/oc/pull/514)
> Bug 1880865: Avoid TLS cert checking when login with --insecure-skip-tls-verify=true

- pkg/cli/admin/inspect/namespace.go
Pod disruption budgets are important enough to be included in Insights tarballs (openshift/insights-operator#185), and they aren't all that big, so we should pick them up as a standard part of interesting namespaces too.  This will help with things like auditing issues where we failed to drain (PDB too strict) or disrupted a core workload (PDB too weak or missing).
> pkg/cli/admin/inspect/namespace: Gather PDBs too

- pkg/cli/admin/inspect/inspect.go
- pkg/cli/admin/inspect/inspect_test.go
- pkg/cli/admin/inspect/pod.go
- pkg/cli/admin/inspect/resource.go
- pkg/cli/admin/inspect/route.go
- pkg/cli/admin/inspect/secret.go
- pkg/cli/admin/mustgather/mustgather.go
A possible example of how to run `oc adm inspect clusteroperators` if must-gather fails.
/hold
this hasn't been tested yet.
> inspect clusteroperators as a backup to must-gather if it fails

- pkg/cli/login/loginoptions.go
Reverts regression introduced in https://github.com/openshift/oc/pull/746 until we can determine a valid approach to solve that problem
> Bug 1935102: Revert Avoid TLS cert checking when login with --insecure-skip-tls-verify=true

- pkg/helpers/newapp/newapptest/newapp_test.go
In https://github.com/openshift/ruby-hello-world/pull/121 IS-es were updated to `ruby-27-centos` which broke all units in oc
/cc @vrutkovs @bparees 
/assign @deads2k
> Fix unit test to use new IS

- pkg/cli/image/mirror/mappings.go
- pkg/cli/image/mirror/mirror.go
While mirroring multiple images, quay.io sends `http2: server sent GOAWAY and closed the connection; LastStreamID=1, ErrCode=ENHANCE_YOUR_CALM, debug=""""`  , `Request Header Or Cookie Too Large</center>\r\n<hr><center>nginx/1.14.1`
To avoid this, split the mappings into groups - []Mappings length 10
This PR sets a hard-coded length of 10 for []Mapping from which the imageTrees and plan are built. I've seen from local testing that oc image mirror fails when given > ~20 SRC=DST mappings.
When sending more that ~20 mappings with `oc image mirror -f file-w-more-than-20` and/or w/ `oc adm catalog mirror` the `Request Header Or Cookie Too Large</center>\r\n<hr><center>nginx/1.14.1` or the `http2 ErrCode=ENHANCE_YOUR_CALM` error is encountered. This PR splits large groups of mappings into …
> Bug 1874106: Split work of oc image mirror to avoid AuthHeaderTooLong error from registry

- pkg/cli/admin/inspect/pod.go
We now gather alerts from the monitoring stack and this takes a long
time run.  Also, when we have problems we normally also have networking
issues so these rarely work when there is something actually broken.
> stop trying to gather metrics and other endpoints directly from pods

- pkg/cli/admin/inspect/namespace.go
if something goes wrong while collecting pods, we track an error which gets reported, but the next line panics. We don't want panics.
/cherrypick release-4.7
/cherry-pick release-4.6
> prevent inspect from panic-ing if pods are missing

- go.mod
- go.sum
- vendor/github.com/gogo/protobuf/proto/text_parser.go
- vendor/modules.txt
Fixes https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-3121
> bug 1924453: Bump github.com/gogo/protobuf to v1.3.2

- pkg/cli/status/status.go
Minor fix to correct the `oc status --help` message. 
Error:
```bash
$ oc --suggest
Error: unknown flag: --suggest
See 'oc --help' for usage.
$
```
> Fixing oc status help example message

- pkg/cli/process/process.go
The code paths that use the `usageErrorFn` func were appending an [`%!(EXTRA ..)`](https://golang.org/pkg/fmt/) message in the output due to variadic args that were not passed properly.
Example output:
```
❯ oc process
error: Must pass a filename or name of stored template%!(EXTRA []interface {}=[])
See 'oc process -h' for help and examples
```
And output with the fix:
```
❯ oc process
error: The following parameters were provided more than once:
See 'oc process -h' for help and examples
```
PTAL
> Fix usage error print

- hack/clibyexample/template
- tools/gendocs/gen_openshift_docs.go
- tools/gendocs/gendocs/gendocs.go
https://issues.redhat.com/browse/OSDOCS-1790
https://issues.redhat.com/browse/OSDOCS-2017
Example output: https://gist.github.com/bergerhoffer/82d4afaa49505fef53d9d0d388e7b6d9 (there will be a table of contents once it is imported into the product docs)
Preview of file incorporated into the product docs (internal): http://file.rdu.redhat.com/~ahoffer/2021/OSDOCS-1790/OSDOCS-1790/cli_reference/openshift_cli/cli-command-reference.html
> Updating generate docs output for product docs

- pkg/cli/admin/createbootstrapprojecttemplate/create_bootstrap_project_template.go
- pkg/cli/admin/createerrortemplate/create_error_template.go
- pkg/cli/admin/createlogintemplate/create_login_template.go
- pkg/cli/admin/createproviderselectiontemplate/create_provider_selection_template.go
- pkg/cli/admin/project/new_project.go
- pkg/cli/projects/projects.go
- pkg/cli/whoami/whoami.go
https://issues.redhat.com/browse/OSDOCS-2033
For now, I've just done the ones that we already had existing examples for in the current CLI docs: 
* https://docs.openshift.com/container-platform/4.7/cli_reference/openshift_cli/developer-cli-commands.html
* https://docs.openshift.com/container-platform/4.7/cli_reference/openshift_cli/administrator-cli-commands.html
> OSDOCS-2033: Adding examples for some CLI commands

- pkg/cli/admin/catalog/mirror.go
- pkg/cli/image/mirror/mappings.go
- pkg/cli/image/mirror/mirror.go
Reverting this change, as `--skip-multiple-scopes` is the workaround for the issue outlined in the bug. With this workaround, we can  take time to investigate a fix that is more targeted to specific situations.
> Bug 1946839: Revert: Split work of oc image mirror

- pkg/helpers/newapp/app/imageref.go
- pkg/helpers/newapp/app/imageref_test.go
If `ImageRef` has `Stream` value filled, it means, that we are working with `ImageStream` that already exists.
In this case suggested name and suggested namespace for `ImageRef` should be taken from that `ImageStream`, and not from the object.
This fixes the bug in which new `ImageStream` is created when we are working with existing `ImageStream`, which has name and namespace different from our deployment name.
> Bug 1925148: ImageRef Stream name priority increased

- images/tools/Dockerfile
Allow stress and fio packages to tools image so that it can be used in tests.
cc @soltysh @smarterclayton
> Add stress and fio packages to tools image

- pkg/cli/admin/release/new.go
In the previous change a key scenario was omitted. An image stream
tag might have the form:
```
spec:
tags:
- name: foo
generation: 5
from: {name: "image1"}
status:
tags:
- tag: foo
items:
- generation: 5
image: image2
- generation: 5
image: image1
```
because a push happened immediately after a spec tagging (generation
only changes on import). Switch oc adm release new to always prefer
status tag, and to let the image stream decide what pull spec should
be used.
> Bug 1937020: Releases from image streams must prefer status tag

- pkg/cli/debug/debug.go
This is backporting https://github.com/openshift/oc/pull/668 to 4.6. 
/assign @ingvagabund
> Bug 1947430: Revert "Bug 1812813: oc debug node: create debug namespace"

- pkg/cli/admin/mustgather/mustgather.go
Must-gather pod should not preemptable but it
is ok to be OOMKilled if there is resource
crunch on the node. So, it should have a
priority class of `system-cluster-critical`
> Bug 1957295: Must gather pod should have priority class

- pkg/helpers/newapp/newapptest/newapp_test.go
> Fix unit test failure

- pkg/helpers/kubeconfig/smart_merge.go
This is a possible fix for https://github.com/openshift/oc/issues/647
Before this patch, if the openshift cluster is behind a cluster proxy (eg. kubectl proxy), and the authentication method is not token, `oc project <project-name>` will create a new user in `kubeconfig`, with blank info. This will lead to further `oc` commands return authentication error.
```
- name: system:serviceaccount:openshift-xxxx-xxxx:xxxxx
user: {}
```
With this patch, when `oc project <project-name>` creating a new `kubeconfig`, it will preserve all the `AuthInfo` from `RESTConfig`, so that it won't break the customized settings.
```
- name: system:serviceaccount:openshift-xxxxx-xxxx/xxx-xxx-xxxx-xxxxx-xxxx-xx-xxxx-com:443
user:
exec:
apiVersion: client.authentication.k8s.io/v1beta1
args:
- …
```
> Bug 1944581: Preserve AuthInfo when switching projects

- pkg/cli/admin/mustgather/mustgather.go
- pkg/cli/debug/debug.go
/assign @smarterclayton 
This builds on top of methods introduced in https://github.com/openshift/library-go/pull/1078/
/cc @dmage @ricardomaraschini 
since you two will be also interested in usage
> Bug 1960758: use recent pull spec for must-gather and debug

- pkg/cli/admin/catalog/mirror.go
since the "--filter-by-os" is deprecated, the error log should be "--index-filter-by-os"
[root@preserve-olm-agent-test openshift-tests-private]# oc adm catalog mirror  --index-filter-by-os='linux/abc'  registry.redhat.io/redhat/redhat-operator-index:v4.6 localhost:5000 --manifests-only 
error: the image is a manifest list and contains multiple images - use **--filter-by-os** to select from:
OS            DIGEST
linux/amd64   sha256:4f0299265620cb29f8010308b0cfac15a8d3fe22b0422f1fdbb86ad5a3383b2a
linux/ppc64le sha256:9959915cad81b4f2b5c14316ec95980f5fd64b38ea6a1f35bcf4183f5c6147ef
linux/s390x   sha256:a57764ff56ec696f372810b1202988cb0a71fc1482b13a1726e9d4e9d74715bc
> Bug 1964936: fix error log for "oc adm catalog mirror"

- pkg/helpers/newapp/newapptest/newapp_test.go
I couldn't trigger automatic cherry-pick, so this is a manual one from https://github.com/openshift/oc/pull/821 which should fix units in 4.7 branch.
> [release-4.7] Fix unit test failure

- pkg/cli/admin/groups/sync/sync.go
- pkg/helpers/groupsync/groupsyncer.go
- pkg/helpers/groupsync/groupsyncer_test.go
This attempts to get group `kind`/`apiVersion` to print in the list when using `oc adm groups sync`
Output with these changes (using sample LDAP at https://www.forumsys.com/tutorials/integration-how-to/ldap/online-ldap-test-server/):
```
$ ./oc adm groups sync --sync-config=ldap-config.yaml -o yaml
apiVersion: v1
items:
- apiVersion: user.openshift.io/v1
kind: group
metadata:
annotations:
openshift.io/ldap.sync-time: 2021-03-09T11:34:59-0500
openshift.io/ldap.uid: ou=mathematicians,dc=example,dc=com
openshift.io/ldap.url: ldap.forumsys.com:389
creationTimestamp: null
labels:
openshift.io/ldap.host: ldap.forumsys.com
name: Mathematicians
users: null
kind: List
metadata: {}
```
> Bug 1936904: Insert apiVersion and Kind into `oc adm groups sync` list output

- pkg/helpers/tokencmd/basicauth.go
- pkg/helpers/tokencmd/request_token.go
This PR bumps printing error for BasicAuthNoUsernameError to v=2 from v=4. Also, adds a bit to guide users to provide a username for the password prompt. 
Fixes https://github.com/openshift/oc/issues/817
> Bug 1893999: guide user to provide username with basic auth error/only password IDP and no username provided

- pkg/helpers/newapp/newapptest/newapp_test.go
I couldn't trigger automatic cherry-pick, so this is a manual one from #821 which should fix units in 4.7 branch.
Adding valid-bug label, since this is unblocking the queue.
/assign @atiratree
> [release-4.6] Fix unit test failure

- pkg/helpers/image/credentialprovider/config.go
Add json.Valid check before trying to read docker config
At the moment, if we fail during unmarshaling JSON, it doesn't
give much of hint where the failure occurred.
For example error message when we provide invalid JSON:
```
unable to load --registry-config: error occurred while trying to unmarshal json
```
Since we have filePath and json package, before actually unmarshaling
the json, we can verify it's contents.
This patch adds a little bit more friendlier error message, before
even failing on unmarshaling
```
unable to load --registry-config: json format is invalid: file.json
```
> Add json.Valid check before trying to read docker config

- pkg/cli/logs/logs.go
> Bug 1973643: make oc logs work with BuildConfig's JenkinsPipeline strategy

- pkg/cli/set/probe.go
some examples lacked `set` in `oc set probe`
> fix typo in examples template

- pkg/cli/admin/catalog/mirror.go
Manually picking part of https://github.com/openshift/oc/pull/780
'oc adm catalog mirror' often fails with server error
'414 Request-URI Too Large' This is because mirroring the
catalog pushes a lot of content in parallel. To avoid this,
set the mirroring flag --skip-multiple-scopes to true.
/assign @damemi
> [release-4.7] Bug 1976284: skip-multiple-scopes with adm catalog mirror

- pkg/helpers/kubeconfig/smart_merge.go
We can use existing Proxy field.
Without patch:
```
➜  oc git:(add-proxy-to-oc) ✗ cat ~/.kube/config | grep 8080
proxy-url: http://127.0.0.1:8080
➜  oc git:(add-proxy-to-oc) ✗ ./oc project default
Already on project "default" on server "https://example.com:6443".
➜  oc git:(add-proxy-to-oc) ✗ cat ~/.kube/config | grep 8080
➜  oc git:(add-proxy-to-oc) ✗
```
With patch:
```
➜  oc git:(add-proxy-to-oc) ✗ cat ~/.kube/config | grep 8080
proxy-url: http://127.0.0.1:8080
➜  oc git:(add-proxy-to-oc) ✗ ./oc project default
Already on project "default" on server "https://example.com:6443".
➜  oc git:(add-proxy-to-oc) ✗ cat ~/.kube/config | grep 8080
proxy-url: http://127.0.0.1:8080
```
With Login option `--proxy` added `oc` will use that during login and will save the proxy as proxy-url for any …
> Bug 1925534: Add proxy to oc

- pkg/cli/admin/release/extract_tools.go
Previously, one could extract x86_64 Windows and Mac binaries (the only 
architectures for those OSes until recently, and still the only ones 
fully supported by Go at the moment) and the Linux binary for the 
payload architecture, but there was no way to e.g. extract an x86_64 
Linux binary to use as a client with a server of a different another 
architecture.  This fixes that, and also extracts binaries for the 
(client) architecture on which oc is run even on Linux.
This also adds the ability to extract an x86_64 Linux installer from a 
payload of any architecture, on the basis that a remote install should 
only require what the user has on their desk, and they may not have (and 
should not need) a matching system for that purpose.  This uses a new 
addition to installer-artifacts. …
> release: extract Linux binaries for multiple architectures

- pkg/helpers/kubeconfig/smart_merge.go
- pkg/helpers/newapp/newapptest/newapp_test.go
Manual cherry-pick of https://github.com/openshift/oc/pull/692 and https://github.com/openshift/oc/pull/860 to fix unit tests.
> [release-4.6] Bug 1973613: Preserve AuthInfo when switching projects

- pkg/cli/admin/prune/imageprune/prune.go
- pkg/cli/admin/prune/imageprune/prune_test.go
- pkg/cli/admin/prune/images/images.go
- pkg/helpers/image/test/util.go
Replaced batch/v1beta1 with batch/v1 so warnings about deprecated CronJob would stop appearing in image-pruner pods.
> Bug 1976112: Fixed warnings about deprecated CronJob in image-pruner pods

- contrib/completions/bash/oc
- contrib/completions/zsh/oc
- pkg/cli/admin/upgrade/channel/channel.go
- pkg/cli/admin/upgrade/upgrade.go
A new subcommand for conveniently managing channels.  Example workflow, starting in a channel:
```console
$ oc adm upgrade
Cluster version is 4.6.0-fc.3
Upstream: https://api.openshift.com/api/upgrades_info/v1/graph
Channel: candidate-4.6 (choices: candidate-4.6)
Updates:
VERSION    IMAGE
4.6.0-fc.4 quay.io/openshift-release-dev/ocp-release@sha256:960ec73733150827076cbb5fa2c1f5aaa9a94bfbce1b4897e46432a56ac976c1
4.6.0-fc.5 quay.io/openshift-release-dev/ocp-release@sha256:5883d0db15939484bd477147e6949c53fbc6f551ec20a0f1106b8a3acfb86ef8
```
Trying to change to the same channel is a no-op:
```console
$ oc adm upgrade channel candidate-4.6
info: Cluster is already in candidate-4.6
```
Trying to change to an unrecognized channel gets a warning:
```console
$ oc adm upgrade channel does-not-exist …
```
> pkg/cli/admin/upgrade/channel: Add 'oc adm upgrade channel ...'

- OWNERS
- OWNERS_ALIASES
- contrib/completions/OWNERS
So folks can touch commands/options within their sections and not need to reach out to root apporovers.  To make it convenient to continue to include the root approvers here, I've shifted them into a new alias.
> contrib/completions/OWNERS: Delegate to all approver aliases

- pkg/helpers/describe/describer.go
- pkg/helpers/describe/describer_test.go
this will align with upstream quota format in describe command: https://github.com/kubernetes/kubernetes/pull/102177
> Bug 1955292: show consistent unit format in cluster resource quota describe

- .gitignore
- pkg/helpers/describe/describer.go
- pkg/helpers/describe/describer_test.go
Adding `oc describe` output for build volumes
Adding tests for `oc describe` output for build volumes
Adding `_tmp` to .gitignore
Sample `oc describe` output for a build config: https://pastebin.com/1TeAfvku
Sample `oc describe` output for a build: https://pastebin.com/vEDEUhhq
> Bug 1978629: Add oc describe output for build volumes

- pkg/cli/debug/debug.go
During the call to `oc debug` for the pod with management resources
it possible that the debug pod will lose workload annotations and
the admission will reject the debug pod because of it.
Signed-off-by: Artyom Lukianov <alukiano@redhat.com>
> Bug 1980118: Keep workload annotations during the `oc debug` call.

- pkg/cli/admin/release/extract.go
This PR enables "ibmcloud" to be specified as part of the cloud argument to `oc adm release extract". An example would look like this:
```sh
oc adm release extract --credentials-requests --cloud=ibmcloud --to=./credrequests <RELEASE_IMAGE>
```
This is related to this CCO PR: https://github.com/openshift/cloud-credential-operator/pull/356 
...and this enhancement: https://github.com/openshift/enhancements/pull/773
> Support ibmcloud provider in release extract

- pkg/helpers/newapp/cmd/newapp_test.go
- pkg/helpers/source-to-image/git/url.go
- pkg/helpers/source-to-image/git/url_test.go
/hold
for now
want to discuss with @adambkaplan when he returns from PTO
this is a possible reconciliation with the concerns in this BZ with conclusions drawn from https://bugzilla.redhat.com/show_bug.cgi?id=1884270
but I'm not ready to make an executive decsion here
> Bug 1971332: revert incorrect allowance of ssh:// prefix with scp styled URLs

- pkg/cli/logs/logs.go
- pkg/helpers/newapp/newapptest/newapp_test.go
This picks https://github.com/openshift/oc/pull/863/ and https://github.com/openshift/oc/pull/860/ to fix units. 
/assign @atiratree
> [release-4.8] Bug 1974267: make oc logs work with BuildConfig's JenkinsPipeline strategy

- pkg/cli/image/imagesource/file.go
- pkg/cli/image/imagesource/file_unix.go
- pkg/cli/image/imagesource/file_windows.go
When running `oc adm release mirror` with the `--to-dir` argument, it creates files on the local machine with the sha256 digest as part of the filename. Since this digest consists of `algo:hash`, this fails on Windows machines, as the `:` character is not allowed in file paths.
This PR introduces platform-specific file path generation for digests that for Windows will replace `:` with `-`. Other platforms are not affected by this change and will continue to allow `:` in file paths.
> Bug 1903545: Replace colons with dashes in Windows file paths

- pkg/cli/admin/catalog/mirrorer.go
When attempting to mirror a registry using `oc adm catalog mirror`, an out of range panic occurs.
This fixes the panic by ensuring we stay in the correct range of the slice that generates image name.
> Bug 1786835: Check for out of range condition

- pkg/cli/admin/upgrade/upgrade.go
The previous:
> This command will request that the cluster begin an upgrade...
and similar [confused some readers][1], because the no-argument invocation is just a read query that does not request an update.  This commit makes the wording more generic, to match the subcommand's actual generic functionality (reading from and optionally writing to ClusterVersion).
I've also tweaked the "No updates available" message to avoid folks misreading as:
> ... doing so may not... result in downtime or data loss.
when we are trying to convey that updating despite a lack of recommendations might be dangerous.
In both cases, the wording I'm altering dates back to the creation of this subcommand in cd30f2f864 (openshift/origin#21605).
[1]: https://bugzilla.redhat.com/show_bug.cgi?id=1992680#c2
> Bug 1992680: pkg/cli/admin/upgrade/upgrade: Copy edits, including "assists with cluster upgrades"

- OWNERS_ALIASES
Update catalog-approvers and catalog-reviewers alias' in the root OWNERS_ALIASES.
> Bug 1999159: Update the catalog-related owner alias'

- go.mod
- go.sum
- vendor/k8s.io/client-go/util/jsonpath/jsonpath.go
- vendor/modules.txt
to bring in: revert "fix wrong output when using jsonpath"
links:
- https://github.com/openshift/kubernetes-client-go/pull/29
- upstream: https://github.com/kubernetes/kubernetes/pull/104172
> Bug 1989505: bump kubernetes-client-go library

- pkg/cli/admin/upgrade/channel/channel.go
Prior to this change, we have:
When current update channel is unknown, it still requires override.
```
$ oc adm upgrade
Cluster version is 4.9.0-0.nightly-2021-07-31-093358
Upstream: https://github.com/shellyyang1989/upgrade-cincy/raw/master/cincy5.json
Channel: channel-f (available channels: channel-a, channel-b)
Updates:
VERSION                           IMAGE
4.9.0-0.nightly-2021-08-01-102437 registry.ci.openshift.org/ocp/release@sha256:421304acff8d9c5bf24365c42460721f9ae1392dd20fbf642c118c163b7731e5
$ oc adm upgrade channel
error: the requested channel "" is not one of the available channels (channel-a, channel-b), you must pass --allow-explicit-channel to continue
```
When desired channel is not specified (or empty), it will clear the channel, but the error message is not clear …
> Bug 1989504: The code logic of channel clear is ambiguous, as well as the help info and output messages

- pkg/cli/admin/catalog/mirror.go
- pkg/cli/admin/catalog/mirrorer.go
- pkg/cli/admin/catalog/mirrorer_test.go
Manual cherrypick of https://github.com/openshift/oc/pull/781 that fixes the invalid package imports in mirrored_test.go.
> [release-4.6] Bug 1942818: when mirroring to a file destination, mount images under the index location

- pkg/cli/create/deploymentconfig.go
* Description: To define a command, consistently include the "command" field instead of "arg" in the configuration file like "Deployment" object. Refer [here](https://kubernetes.io/docs/tasks/inject-data-application/define-command-argument-container/) more details at the k8s docs.
* Reference: https://bugzilla.redhat.com/show_bug.cgi?id=2002950
> Bug 2002950: Define a Command instead of Arguments for Container

- pkg/cli/admin/catalog/mirrorer.go
> Bug 2004193: Registry mirror panic

- pkg/cli/admin/catalog/mirrorer.go
> Bug 2004194: Registry mirror panic

- README.md
When debugging another issue and getting this repo started for the first time it was necassary to install two packages via brew.
```
brew install heimdal
brew install gpgme
```
As a result I am proposing a change to add these into the README for the future.
> Add MacOS local building instructions to README

- pkg/cli/admin/catalog/mirror.go
WIP: This PR supersedes [PR 741](https://github.com/openshift/oc/pull/741).
> Bug 1926522: oc adm catalog mirror tmp directory cleanup

- pkg/cli/debug/debug.go
When running oc debug with `--as-root`, Pod with `.spec.securityContext.runAsNonRoot: true` fails with `Error: container's runAsUser breaks non-root policy`.
See also: #879
> runAsNonRoot in Pod SCC should be nil when oc debug run with `--as-root` 

- pkg/cli/create/route/route.go
- pkg/cli/create/routeedge.go
- pkg/cli/create/routepassthrough.go
- pkg/cli/create/routereenecrypt.go
- pkg/cli/expose/expose.go
When doing dry run, the namespace will not be part of the output
manifests ( i.e. yaml or json, etc. ). This commit adds the namespace
to the generated route resource if it is not the default.
How to reproduce it?
```
$ oc create route passthrough namex --service servicex -n namespacex --dry-run=client -o yaml
apiVersion: route.openshift.io/v1
kind: Route
metadata:
creationTimestamp: null
labels:
app.kubernetes.io/component: identity-provider
app.kubernetes.io/instance: e2e-test
app.kubernetes.io/name: namex
app.kubernetes.io/version: v2.24.0
name: namex
spec:
port:
targetPort: http
tls:
termination: passthrough
to:
kind: ""
name: servicex
weight: null
status: {}
```
> Make sure to set the namespace for routes resources

- pkg/cli/admin/upgrade/upgrade.go
Copying from [the CVO][1], and adjusting to return a pointer instead of a (non-pointer,found) tuple.  Future work can shift this function into library-go.  This avoids:
```console
$ oc adm upgrade --to 4.6.0-fc.5
error: Can't look up image for version 4.6.0-fc.5. The update channel has not been configured.
```
When that lookup would succeed when investigating ClusterVersion's `status.history`:
```console
$ oc patch clusterversion version --type json -p '[{"op": "add", "path": "/spec/desiredUpdate", "value": {"version": "4.6.0-fc.5"}}]'
$ oc adm upgrade
info: An upgrade is in progress. Working towards 4.6.0-fc.5: downloading update
warning: Cannot display available updates:
Reason: NoChannel
Message: The update channel has not been configured.
```
[1]: …
> Bug 1878925: pkg/cli/admin/upgrade: Remove help text around history lookups

- pkg/cli/admin/upgrade/upgrade.go
- pkg/cli/admin/upgrade/upgrade_test.go
Since it landed in cd30f2f864, `oc adm upgrade` has had client-side guards .  Those guards were then, and until this commit still were, sequential, so the caller would only hear about the first guard that fails.  Then the user will be prompted, with modern `oc`, to set `--allow-upgrade-with-warnings` to waive the warnings.  This commit adjusts `checkForUpgrade` to complain about all failing checks, so the user can see all the guards they're waiving before the set the override (and also to see all the guards they waived if the do set the override).
> Bug 1952230: pkg/cli/admin/upgrade: Always run all client-side checks

- pkg/cli/admin/upgrade/upgrade.go
Replace output like:
```console
$ oc adm upgrade
Cluster version is 4.9...
Upgradeable=False
Reason: MultipleReasons
Message: Cluster should not be upgraded between minor versions for multiple reasons: ClusterVersionOverridesSet,Testing
* Disabling ownership via cluster version overrides prevents upgrades. Please remove overrides before continuing.
* Cluster operator testing should not be upgraded between minor versions: Testing upgradeable https://example.com/a.
warning: Cannot display available updates:
Reason: NoChannel
Message: The update channel has not been configured.
```
With:
```
...
Message: Cluster should not be upgraded between minor versions for multiple reasons: ClusterVersionOverridesSet,Testing
* Disabling ownership via cluster version overrides prevents upgrades. Please …
```
> pkg/cli/admin/upgrade: Indent multi-line messages

- pkg/cli/secrets/link.go
Per https://github.com/openshift/openshift-docs/issues/38217
> GitHub-38217: Removing old example that mentions limitSecretReferences

- pkg/cli/admin/mustgather/mustgather.go
Since we've added option to run must-gather container on multiple nodes
(https://github.com/openshift/oc/pull/850, --node-selector), folder name
should be different for pods running on different nodes with the same
image name.
Signed-off-by: Nadia Pinaeva <npinaeva@redhat.com>
> mustgather: add NodeName to destDir folder name

- pkg/cli/admin/upgrade/upgrade.go
Commands need an example in order to show up in the autogenerated CLI docs. Adding an example for `oc adm upgrade` so that it'll show up.
> Adding an example for oc adm upgrade

- pkg/cli/admin/release/extract.go
This PR enables "alibabacloud" to be specified as part of the cloud argument to `oc adm release extract". An example would look like this:
```
oc adm release extract --credentials-requests --cloud=alibabacloud --to=./credrequests <RELEASE_IMAGE>
```
This is related to this CCO PR: https://github.com/openshift/cloud-credential-operator/pull/412
/cc @kwoodson @joelddiaz
> feat/oc-release-extract-cco: add support for alibabacloud

- Makefile
- images/cli-artifacts/Dockerfile.rhel
- pkg/cli/admin/release/extract_tools.go
This will allow users of the newest M1 MacOS hardware to use a native oc binary, rather than relying on Rosetta2 translation of the darwin/amd64 oc.
Extraction of a darwin/arm64 openshift-install will follow separately.
﻿
> Add darwin/arm64 oc

- pkg/cli/admin/release/extract_tools.go
This is a follow-up to #990, now that we have been able to confirm that these binaries do work when extracted from a payload.﻿
> release: extract darwin/arm64 openshift-install

- contrib/completions/bash/oc
- pkg/cli/admin/upgrade/upgrade.go
So that users can upgrade to a version listed in Supported but not
recommended updates. The list of versions can be seen with oc adm upgrade --include-not-recommended
For details refer to https://github.com/openshift/enhancements/blob/2cc2d9b331532c852878a7c793f3a754914c824e/enhancements/update/targeted-update-edge-blocking.md
https://issues.redhat.com/browse/OTA-528
Signed-off-by: Lalatendu Mohanty <lmohanty@redhat.com>
> Adding the flag --allow-not-recommended to oc adm upgrade

- pkg/cli/admin/mustgather/mustgather.go
Fixes: https://github.com/openshift/oc/issues/941
As per the current tolerations, `Operator: Exists`, the must-gather pod is spawned with following `spec.tolerations`:
> $ oc get pods must-gather-2cnh8 -ojson -n openshift-must-gather-strbd | jq .spec.tolerations
> [
>   {
>     "operator": "Exists"
>   }
> ]
After specifying the `Key: "node-role.kubernetes.io/master"`, the pod comes up with these additional tolerations (which helps to take the `not-ready` and `unreachable` conditions into consideration):
> $ oc get pods must-gather-lcq28 -ojson -n openshift-must-gather-j245c | jq .spec.tolerations
> [
>   {
>     "key": "node-role.kubernetes.io/master",
>     "operator": "Exists"
>   },
>   {
>     "effect": "NoExecute",
>     "key": "node.kubernetes.io/not-ready",
>     "operator": …
> Modified MG pod tolerations

- pkg/cli/requestproject/request_project.go
k8s.gcr.io/serve_hostname is deprecated and single-arch.  agnhost is the literal replacement in the E2E test suite.
> Bug 2032111: requestproject: use agnhost serve-hostname

- pkg/cli/admin/inspect/inspect.go
- pkg/cli/admin/inspect/namespace.go
- pkg/cli/admin/inspect/pod.go
For example, see [here](https://en.wiktionary.org/wiki/occurred).
> Bug 2033751: pkg/cli/admin/inspect: Fix "ocurred" -> "occurred" typos

- pkg/cli/admin/prune/deployments/deployments.go
Specifically, this fixes a panic when using `--replica-sets`.
> Bug 2034889: Fix prune deployment panic

- pkg/cli/admin/prune/deployments/data.go
- pkg/cli/admin/prune/deployments/data_test.go
- pkg/cli/admin/prune/deployments/resolvers.go
This is a followup to https://github.com/openshift/oc/pull/1015 that improves a few aspects of pruning ReplicaSets and switches to matching replicas and deployments using OwnerReferences rather than Annotations.
> Bug 2036826: Improved prune deployments

- pkg/cli/admin/buildchain/test/multiple-namespaces-bcs.yaml
- pkg/cli/admin/buildchain/test/single-namespace-bcs.yaml
- pkg/helpers/describe/projectstatus_test.go
- pkg/helpers/graph/genericgraph/test/new-project-deployed-app.yaml
- pkg/helpers/graph/genericgraph/test/new-project-no-build.yaml
- pkg/helpers/graph/genericgraph/test/new-project-one-build.yaml
- pkg/helpers/graph/genericgraph/test/new-project-two-deployment-configs.yaml
- pkg/helpers/newapp/cmd/newapp_test.go
- pkg/helpers/newapp/newapptest/newapp_test.go
GitHub is removing support for the unsecured "git://" protocol when
cloning source code [1]. This is being done in phases, with full
removal happening on March 15, 2022. Some of the new-app unit tests
connect to GitHub and attempt to clone source code - this updates the
tests to use HTTPS instead of `git://`.
[1] https://github.blog/2021-09-01-improving-git-protocol-security-github/
> Bug 2039491: Remove `git://` from new-app tests

- pkg/cli/debug/debug.go
due to a default selector and  suggest a possible solution
@soltysh 
example output:
```bash
Starting pod/ip-10-0-149-155eu-central-1computeinternal-debug ...
To use host binaries, run `chroot /host`
Removing debug pod ...
error: debug pod could not be scheduled: Pod Predicate NodeAffinity failed. To fix this you may want to create a new namespace with empty node selector and run the debug there. For example: oc adm new-project --node-selector="" debug
```
> Bug 2038160: Inform user about inability to schedule a debug pod

- pkg/cli/admin/catalog/mirror.go
- pkg/cli/admin/catalog/testdata/test-declcfg/.indexignore
- pkg/cli/admin/catalog/testdata/test-declcfg/README.md
When loading file-based catalogs, oc adm catalog mirror should
automatically ignore .indexignore files it finds rather than requiring
an explicit pattern in the .indexignore file to ignore itself. There is
no circumstance where a .indexignore file would be expected to be
understood as an catalog file.
Signed-off-by: Joe Lanford <joe.lanford@gmail.com>
> Bug 1999246: adm catalog mirror should ignore .indexignore files

- pkg/cli/admin/prune/deployments/data.go
- pkg/cli/admin/prune/deployments/data_test.go
- pkg/cli/admin/prune/deployments/deployments.go
- pkg/cli/admin/prune/deployments/prune.go
- pkg/cli/admin/prune/deployments/prune_test.go
- pkg/cli/admin/prune/deployments/resolvers.go
This allows `oc adm prune deployments --replica-sets=true --orphans=true` to work on orphaned ReplicaSets.
> Bug 2039359: Fix adm prune rs orphans

- pkg/cli/debug/debug.go
This is to address https://issues.redhat.com/browse/RFE-2567
Setting a 15 minute idle timeout on debug node pods.
> Add TMOUT env to debug node pod

- pkg/cli/admin/upgrade/upgrade.go
As [Evgeni points out][1], there is a bug in a0f1832b91 (#1041).  When `--to-image` is not set, we want to mention that the user may want to set it.  When `--to-image` is set, we want to mention `--allow-explicit-update`.  The previous check had the reversed sense, and mentioned `--allow-explicit-upgrade` when `--to-image` was unset.
[1]: https://bugzilla.redhat.com/show_bug.cgi?id=2044140#c8
> Bug 2044140: pkg/cli/admin/upgrade: Fix nextStep option sense

- pkg/cli/admin/mustgather/mustgather.go
Followup to #1003 explains why we need empty tolerations. 
/assign @ravisantoshgudimetla
> Comment tolerations used in must-gather

- pkg/cli/debug/debug.go
> Bug 2052034: make sure that we check for resorces and files before picking the simplest path

- go.mod
- go.sum
- vendor/github.com/openshift/library-go/pkg/image/registryclient/client.go
- vendor/github.com/openshift/library-go/pkg/image/registryclient/client_mirrored.go
- vendor/modules.txt
This PR bumps library-go to get a new registryclient that can correctly
handle image references like
registry.example.com/namespace.with.dot/foo
> Bug 2049234: Fix mirroring images that have dots in their namespace

- go.mod
- go.sum
- vendor/github.com/openshift/library-go/pkg/image/registryclient/client.go
- vendor/github.com/openshift/library-go/pkg/image/registryclient/client_mirrored.go
- vendor/modules.txt
Backport of #1063.
This PR bumps library-go to get a new registryclient that can correctly
handle image references like
registry.example.com/namespace.with.dot/foo
> Bug 2053218: Fix mirroring images that have dots in their namespace

- hack/clibyexample/template
- hack/clibyexample/template-admin
https://issues.redhat.com/browse/OSDOCS-3257
We have a new metadata requirement on our doc files to identify the content type (REFERENCE in this case). Adding to the templates.
> OSDOCS-3257: Adding in new metadata requirement for docs

- pkg/cli/cli.go
Manual cherry-pick of a single commit bumping discovery burst from https://github.com/openshift/oc/pull/1033
> Bug 2045008: bump discovery burst

- pkg/cli/admin/upgrade/upgrade.go
We've had the warning at least since this repo was created in 3abf60a31e.  But since we grew `--allow-explicit-upgrade` in 0501d04ff1 (#109), `--to-image` has been just as restricted to recommended updates as `--to`.  Removing the warning here avoids unnecessary alarm.  We can save the warning for `--allow-explicit-upgrade`, whose help text I'm consolidating in this
commit.  The new structure is:
* `--to` and `--to-image` together, since in the absence of `--allow-explicit-upgrade` those are equally safe.
* The paragraph about unsupported updates or broken CVO <-> upstream update service communication.  Before this paragraph had focused on `--to-image`, but I've adjusted it to focus on `--allow-explicit-upgrade`.
* The `--allow-upgrade-with-warnings` paragraph.  I've moved the sentence …
> Bug 2056893: pkg/cli/admin/upgrade: Drop --to-image help warning

- pkg/cli/admin/release/extract.go
Add Nutanix as a cloud platform for `oc adm release extract`
subcommand for extracting credentials request objects of
NutanixProviderSpec.
> Add Nutanix platform

- pkg/cli/admin/upgrade/upgrade.go
Making it easier for folks to find the `oc adm upgrade channel` subcommand from 4b8f0fd876 (#576), when they look at `oc adm --help`.
> pkg/cli/admin/upgrade: Mention channel choices

- pkg/cli/set/triggers.go
OKD 4.8 uses Kubernetes 1.21 which has changed the `CronJob`'s version to `batch/v1`. Unfortunately, `oc set triggers` isn't aware of that change yet which means it is impossible to configure `Image` triggers on a `CronJob`.
> Allow triggers on batch/v1 CronJobs

- go.mod
- go.sum
- pkg/cli/admin/mustgather/mustgather.go
- vendor/k8s.io/pod-security-admission/LICENSE
- vendor/k8s.io/pod-security-admission/api/attributes.go
- vendor/k8s.io/pod-security-admission/api/constants.go
- vendor/k8s.io/pod-security-admission/api/doc.go
- vendor/k8s.io/pod-security-admission/api/helpers.go
- vendor/modules.txt
This labels the must-gather namespace as privileged. Depending on the options (i.e. host-network) this namespace has to be privileged.
```
$ for f in registry-*/audit_logs/kube-apiserver/*audit.log.gz; do gzcat $f; done | jq  '. | select((.annotations | has("pod-security.kubernetes.io/audit-violations"))) | {objectRef: (.objectRef.namespace + "/" + .objectRef.resource + "/"+ .objectRef.name), "pod-security.kubernetes.io/audit-violations": .annotations["pod-security.kubernetes.io/audit-violations"]}' | jq -C -s --sort-keys '. | unique | .[]'
{
"objectRef": "openshift-must-gather-lhspw/pods/",
"pod-security.kubernetes.io/audit-violations": "would violate PodSecurity \"restricted:latest\": allowPrivilegeEscalation != false (containers \"gather\", \"copy\" must set …
```
> pkg/cli/admin/mustgather: label must-gather ns as privileged

- pkg/cli/admin/release/bug.go
- pkg/cli/admin/release/bug_test.go
- pkg/cli/admin/release/git.go
- pkg/cli/admin/release/git_test.go
- pkg/cli/admin/release/info.go
Currently, `oc adm release info` retrieves and describes bugs only from Bugzilla.
But in the near future, Jira will be the primary source for managing bugs.
This PR adds handler for Jira bugs whose start with `OCPBUGS-` prefix and combining
Jira defects as well as Bugzilla bugs whose start with `BUG `.
> Introduce Jira defects into release info

- pkg/cli/admin/migrate/migrator.go
`ServerResources` function was removed in Kubernetes 1.24(ref: https://github.com/kubernetes/kubernetes/pull/107180). This PR changes places to `ServerGroupResources` to prevent any build errors in bump to 1.24.
> Use ServerGroupResources instead deprecated ServerResources

- pkg/cli/importimage/importimage.go
This PR adds validation for reference-policy flag for import-image
command. It will return error when reference-policy is other than
source or local. In addition to that upper or lower cases will be treated
as valid(ie. Local, loCal, Source, etc.)
> Bug 2041454: Validate reference-policy for import-image command

- pkg/cli/admin/upgrade/upgrade.go
ClusterVersion's spec can evolve over time, growing additional properties like [capabilities][1].  With the old `POST`/`Update(...)` approach, that could lead to older `oc` (who didn't know about the new properties) naively clearing them when they washed the in-cluster resource through their local ClusterVersion Go type.  With this commit, we transition to `PATCH`, so we can touch just `spec.desiredUpdate`, regardless of what else is going on in spec.
Also, while I'm touching this code:
* I set things up so `--allow-not-recommended` works with `--to-latest` as well.  This also consolidated so there was only a single `Update` to convert to a `Patch`.
* I adjusted `--allow-explicit-upgrade --to-image ...` logging to only complain about `--allow-explicit-upgrade` when we needed to use it, …
> Bug 2075647: pkg/cli/admin/upgrade: Use PATCH instead of POST for spec updates

- pkg/cli/image/manifest/dockercredentials/auth_resolver.go
- pkg/cli/registry/login/login.go
- pkg/helpers/image/helpers.go
Also specify a subject of the docker conf deprecation message as noted in the BZ.
> Bug 2073113: do not report docker conf deprecation warning when the docker is not available

- cmd/oc/oc.go
Api server does not permit strategic merge patch type for CRDs during
patch operations. This is ensured by not registering CRDs schemes.
Therefore, `oc` must only register non-crds into scheme. This PR removes
`network.openshift.io` registration because it does not contain any non-crd.
ref: https://github.com/openshift/api/blob/2f6f4d85d80b3f39d66e7e1674aeff71f8a68b3d/network/v1/register.go#L33-L40
> Bug 2071614: Remove network CRDs scheme registration

- pkg/cli/admin/release/git.go
- pkg/cli/admin/release/git_test.go
Repositories, like insights-operator, use squash-merge and
`oc adm release info --changes-from` does not show changes for these repos.
This PR adds handling also squash merging and shows changes.
> Bug 2007647: Add squash-merge support into oc adm release info

- pkg/cli/project/project.go
Currently if user enters <tab> after `oc project`, it auto completes
as `oc project project`. This PR fixes that and after entering <tab>,
it lists all projects.
> Bug 2080416: Fix project command auto completion

- pkg/cli/admin/inspect/inspect.go
This is followup to https://github.com/openshift/oc/pull/1051 after we landed k8s 1.24. It removes that temporary hack in favor of directly setting `ShowManagedFields` in printers. 
> Replace temporary show-managed fields hack with a proper solution

- pkg/cli/serviceaccounts/create_kubeconfig.go
- pkg/cli/serviceaccounts/gettoken.go
- pkg/cli/serviceaccounts/newtoken.go
- pkg/cli/serviceaccounts/subcommand.go
As discussed on slack, start deprecating `oc serviceaccounts` commands in favor of `oc create token`. 
/assign @stlaz @s-urbaniak
> Deprecate oc serviceaccounts command

- pkg/cli/admin/inspect/namespace.go
add `egressfirewalls` and `networkpolicies` to the namespace resources.
Required for networking debugging.
`egressfirewalls` are only registered for ovn-kubernetes network plugin, but inspect will just skip them for other clusters and log
```
error: errors occurred while gathering data:
the server doesn't have a resource type "egressfirewalls"
```
Signed-off-by: Nadia Pinaeva <npinaeva@redhat.com>
> Bug 2023295: [inspect] Add namespace-scoped networking resources to inspect

- pkg/cli/admin/release/info.go
- pkg/cli/admin/release/new.go
- pkg/cli/image/append/append.go
Followup work from https://github.com/openshift/oc/pull/1109
> WRKLDS-370: copy manifests from linux/amd64 to all manifests in a list

- pkg/cli/admin/upgrade/upgrade.go
To accurately display the upgrade's status add the `ReleaseAccepted` condition to the `oc adm upgrade` command.
With the new logic introduced by the bug fix for the CVO (https://bugzilla.redhat.com/show_bug.cgi?id=1822752), it is necessary to accurately display the current status of the upgrade in a case where a release payload wasn't accepted.
This change will display (using the `oc adm upgrade` command) the reason and the message containing information on why the given release payload wasn't accepted and thus why the update hasn't started.
Pull request related to https://issues.redhat.com/browse/OTA-589
> Bug 2065507: Add the ReleaseAccepted condition to the oc adm upgrade command

- pkg/cli/admin/release/mirror.go
Release signatures are written in file in json format. However,
file extension is in yaml. This PR changes extension to json.
`oc-mirror` uses correct extension 
https://github.com/openshift/oc-mirror/blob/7bde4c7bde6b829a34592b2d12115fb38b15576f/pkg/cli/mirror/release.go#L39
> Bug 2083770: Change release signature file extension to json

- pkg/cli/image/mirror/mirror.go
Fixes #1104 
The skipMissing flag is checked and if the error thrown is a 404 then the process is allowed to continue
> Bug 2090751: Correcting skipMissing flag usage when a manifest cannot be found

- pkg/cli/admin/upgrade/upgrade.go
The outgoing wording is from 3abf60a31e.  But the flow is:
1. User calls `oc adm upgrade ...` to request an update.
2. `oc` performs some client-side checks, which can be overridden with `--allow-upgrade-with-warnings`.
3. `oc` accepts the update, and patches ClusterVersion's `spec.desiredUpdate`.
4. The cluster-version operator performs some checks, which can be overridden with `--force`.
6. The CVO accepts the update, and begins updating.
The message I'm touching happens just after 3, but the outgoing wording [could be misinterpreted][1] as a claim about being at step 6. This commit pivots to wording that is more clearly tied to step 3.
[1]: https://bugzilla.redhat.com/show_bug.cgi?id=2087103
> Bug 2087103: pkg/cli/admin/upgrade: "Updating to" -> "Requesting update to"

- OWNERS_ALIASES
While working on #1152, we realized that the owners of this component is way too small. This PR adds the relevant owners (namely from the OLM team) to be able to review/approve code.
> *: add relevant code owners for catalog alias

- pkg/helpers/tokencmd/basicauth.go
- pkg/helpers/tokencmd/basicauth_test.go
- pkg/helpers/tokencmd/negotiator_sspi.go
- pkg/helpers/tokencmd/negotiator_sspi_unsupported.go
- pkg/helpers/tokencmd/request_token.go
- pkg/version/server_version.go
~There is no easy access for not logged in users to the console.~
~We have to guess the console URL, since we are not authenticated yet and we cannot be sure of the real URL (configurability docs: https://docs.openshift.com/container-platform/4.7/web_console/configuring-web-console.html)~
show console URL when asking for Authentication
- the URL will redirect to the real URL
- added check for a server version since this feature is not generally available before OpenShift 4.11 (Kubernetes 1.24)
The output of the command:
```bash
> oc login -u test
Authentication required for https://api.my-cluster0.com:6443 (openshift)
Console URL: https://api.my-cluster0.com:6443/console
Username: test
Password:
```
> Bug 1957668: show console URL when asking for Authentication

- pkg/cli/rsync/copy_rsync.go
- pkg/cli/rsync/util.go
The oc rsync fails, complaining that rsync and tar are missing in the
container:
```
$ oc rsync --container foo -n openshift-storage pod/rook-ceph-tools-56f88ff6cb-tvpg5:/etc/redhat-release /tmp
WARNING: cannot use rsync: rsync not available in container
WARNING: cannot use tar: tar not available in container
error: No available strategies to copy.
```
> Bug 2057633: add validations for a pod & container to rsync

- pkg/cli/admin/release/bug.go
- pkg/cli/admin/release/info.go
Currently, bug source types can be Bugzilla or Jira and there is no
differentiator point for bugs in `oc adm release info`. By passing
`--output=json`, users will be able to see bugs belong to Jira or
Bugzilla.
This PR adds json output format support for release info bugs.
> Bug 2100138: Add json support for release info bug printing

- pkg/cli/admin/mustgather/mustgather.go
Colon character is used by rsync command to extract pod name and
determine the type of path is local or remote.
This PR adds validation to ensure that dest-dir option does not
contain any special character possibly affecting rsync.
> Bug 2015321: Add destdir special character validation in must-gather

- pkg/cli/image/manifest/manifest.go
"Chose %s/%s manifest from the manifest list." log creates noise
especially for the commands calling image extraction in a multi-threaded way.
This PR lowers of this log's level. Users will still be able to see
these logs by passing `-v=2` but log will be disabled by default.
> Bug 2100708: Lower chosen platform architecture/OS log level

- pkg/cli/kubectlwrappers/wrappers.go
Completion function in get command was cut out from it and instead it is being set in [here](https://github.com/kubernetes/kubernetes/blob/e89a87f708a03c5a8331639739982d426077ad3a/staging/src/k8s.io/kubectl/pkg/cmd/cmd.go#L325). This change was done in [this PR](https://github.com/kubernetes/kubernetes/pull/108493).
In order to support completion for get command, we need to set explicitly this in oc. This PR does this.
/cc @soltysh
> Bug 2101885: Set completion function for get command

- pkg/cli/admin/release/extract.go
- pkg/cli/admin/release/extract_tools.go
- pkg/cli/admin/release/info.go
- pkg/cli/admin/release/mirror.go
- pkg/cli/admin/release/new.go
- pkg/cli/image/extract/extract.go
`release info` and `release extract` commands need manifestlist image's
sha value instead filtered by os image sha.
Thanks to that, extracted tools will be used for all archs. This PR
adds IsManifestList field into ReleaseInfo and uses it when digest needs
to be set for these commands.
> Bug 2100166: Add new IsManifestList flag into ReleaseInfo struct

- go.mod
- pkg/cli/admin/inspect/inspect.go
- pkg/cli/admin/inspect/pod.go
- vendor/modules.txt
Added a flag that allows the user to get the rotated pod log files stored by kubelet.
Currently logs that were rotated are not exposed through the K8s log API.
Almost clean cherry-pick, there was a conflict in `vendor/modules.txt`: https://github.com/openshift/oc/pull/958#issuecomment-1173959866
Signed-off-by: Patryk Diak <pdiak@redhat.com>
(cherry picked from commit efb24f6f65b76c64c5143185e340dbb050349a6b)
> [release-4.9] Bug 2103910: Introduce an option to retrieve the rotated log files for a pod

- pkg/cli/admin/release/extract_tools.go
This will allow a much simpler extraction of `ccoctl` from the payload than that currently documented.
Related:
https://issues.redhat.com/browse/CCO-169
https://github.com/openshift/cloud-credential-operator/pull/431
/cc @jeffnowicki
> release: extract ccoctl

- pkg/cli/admin/release/info.go
The `--output=json` option is used on the `Openshift Release Controller` Jira and Bugzilla verifier. 
This option was added to be able to distinguish between Jira and Bugzilla bugs ([PR](https://github.com/openshift/oc/pull/1177)).
We use:
`oc adm release info --bugs=/tmp/git/ --output=json <from> <to>` to get the bug list for a given input.
When `oc` fails to retrieve a certain bug, it returns: 
`error: Bug XXXXX was not retrieved` 
This breaks our use case, and the `--skip-bug-check` option is required (at the moment this option is enabled for `--output=name` only)
This (`--output=json --skip-bug-check`) will return something like:
```json
[
{
"id": 2088606,
"status": "",
"priority": "",
"summary": "",
"source": 0
}
]
```
> release info bug printing: enable `--skip-bug-check` for `--output=json` 

- pkg/cli/image/manifest/dockercredentials/auth_resolver.go
- pkg/cli/image/manifest/dockercredentials/credential_store_factory.go
- pkg/cli/image/manifest/dockercredentials/credential_store_factory_test.go
- pkg/helpers/image/credentialprovider/config.go
- pkg/helpers/image/credentialprovider/config_test.go
This PR is to support the container registry with identity token.
This is how the typical `.docker/config.json` file looks like:
```json
{
"auths": {
"icr.io": {
"auth": "aWFtYXBpa2V5Og==",
"identitytoken": "xxxxxxxxxxxxxxxxxxxxx"
}
}
}
```
without this change:
```shell
$ oc adm release info icr.io/openshift-release-dev/ocp-release:4.11.0-0.nightly-multi-2022-07-06-015348-x86_64
Warning: the default reading order of registry auth file will be changed from "${HOME}/.docker/config.json" to podman registry config locations in the future version of oc. "${HOME}/.docker/config.json" is deprecated, but can still be used for storing credentials as a fallback. See https://github.com/containers/image/blob/main/docs/containers-auth.json.5.md for the order of podman registry config locations.
error: …
```
> Support for identity token

- pkg/cli/admin/release/extract.go
- pkg/cli/admin/release/extract_tools.go
- pkg/cli/admin/release/info.go
- pkg/cli/admin/release/mirror.go
- pkg/cli/admin/release/new.go
- pkg/cli/image/extract/extract.go
- pkg/cli/image/manifest/manifest.go
When performing oc adm release info or extract commands on heterogeneous images with tags, the release image reference is incorrect. infer the manifestlist digest and add that to the release image when referencing by tag
> Bug 2105325: Add ManifestListDigest field to release info struct

- pkg/cli/admin/inspect/inspect.go
- pkg/cli/admin/inspect/resource.go
- pkg/cli/admin/inspect/util.go
Collect all resources served by the server through the discovery client and check whether an about-to-be-inspected resource exists to avoid getting an error when it does not.
```
$ ./oc adm inspect co/console
Gathering data for ns/openshift-console-operator...
W0729 16:26:09.139371 1931005 util.go:119] the server doesn't have a resource type egressfirewalls, skipping the inspection
Gathering data for ns/openshift-console...
W0729 16:26:15.981392 1931005 util.go:119] the server doesn't have a resource type egressfirewalls, skipping the inspection
Wrote inspect data to inspect.local.8870216383603463254.
```
> bug 2095708: oc adm inspect: check a resource exists before its inspection

- pkg/cli/debug/debug.go
To be compatible with the upstream [debug](https://github.com/kubernetes/kubernetes/blob/fd0c15cce3d66bc2b32fc6943688425ec269d97d/staging/src/k8s.io/kubectl/pkg/cmd/debug/profiles.go#L52) command, this PR sets
`HostIPC` to true when debugging a node for `oc`. 
In addition to that this PR fixes the referenced issue.
> Bug 2108307: Set HostIPC to true when debugging node

- pkg/cli/admin/release/new.go
This is manual cherry-pick of https://github.com/openshift/oc/pull/1183, https://github.com/openshift/oc/pull/1192
> [release-4.11] Bug 2103638: Use from-release as based image when base digest is invalid

- pkg/cli/admin/inspect/namespace.go
This PR adds `servicemonitors` resource into common namespaces for `oc adm inspect`. 
`servicemonitors` is a useful resource as stated in referenced bug and it takes a few kilobytes storage.
> Bug 2112934: Add servicemonitors into common namespaces for inspection

- pkg/cli/admin/inspect/inspect.go
- pkg/cli/admin/inspect/resource.go
- pkg/cli/admin/inspect/util.go
Collect all resources served by the server through the discovery client and check whether an about-to-be-inspected resource exists to avoid getting an error when it does not.
```
$ ./oc adm inspect co/console
Gathering data for ns/openshift-console-operator...
W0729 16:26:09.139371 1931005 util.go:119] the server doesn't have a resource type egressfirewalls, skipping the inspection
Gathering data for ns/openshift-console...
W0729 16:26:15.981392 1931005 util.go:119] the server doesn't have a resource type egressfirewalls, skipping the inspection
Wrote inspect data to inspect.local.8870216383603463254.
```
Cherry-picking https://github.com/openshift/oc/pull/1215
> [release-4.10] bug 2116526: oc adm inspect: check a resource exists before its inspection

- pkg/helpers/cmd/errors.go
The original message's command can't let readers successfully add pod security labels due to the automatic sync mechanism. This confuses them. As talked in Slack with @stlaz , this needs modification. To make messages simplified, just adding security.openshift.io/scc.podSecurityLabelSync=false, not trying to complicatedly explain that only non-installer-created namespaces with no openshift- prefix require this label and non-installer-created openshift- prefixed namespaces don't require it.
/assign @stlaz
> Give a complete oc label command in pod security error message

- pkg/cli/admin/inspect/namespace.go
Another namespace-scoped networking resource we need to fetch
https://github.com/openshift/oc/pull/1128
Signed-off-by: Ori Braunshtein <obraunsh@redhat.com>
> Bug 2087679: [inspect] Add EgressQoS to inspect

- pkg/cli/debug/debug.go
- pkg/cli/debug/debug_test.go
Currently, if user wants to debug a node and default namespace is not privileged, `oc` returns a pod security violation error.
Since this hurts the usability of `oc debug node/` command, this PR adds creation of temporary namespace for node debugging.
Temporary namespace will be created iff;
- user tries to debug a node
- `--to-namespace` is not set
- `--namespace` is not set
- default namespace is not privileged
/assign @soltysh @deads2k 
/cc @stbenjam
> OCPBUGS-852: cli/debug: Create temporary namespace for node debugging

- pkg/helpers/cmd/errors.go
If user gets a pod security violation error, `oc` suggests a command how to overcome that. However, newly created namespaces already have `pod-security.kubernetes.io/enforce: restricted` this label and suggested command is failing by
`error: 'pod-security.kubernetes.io/enforce' already has a value (restricted), and --overwrite is false`.
This PR adds `--overwrite` flag into suggested commands in case new namespace might already contain such labels.
> Add --overwrite flag into pod security violation error message

- OWNERS_ALIASES
Catching up with [this CVO config][1].  Abhinav and Clayton are no longer with Red Hat. Vadim has [moved to the assisted-installer][2], and Scott dropped himself [here][3].
[1]: https://github.com/openshift/cluster-version-operator/blob/bce1e9fb73467152ef38b11746b616038ff939f7/OWNERS
[2]: https://github.com/openshift/cluster-version-operator/commit/799b668d25b388808410a09ab3857446adca85f1
[3]: https://github.com/openshift/cluster-version-operator/commit/7c5dbf6d62b1108c1ee9c4493ce5898f8b0faa6a
> OWNERS_ALIASES: Freshen update-approvers

- pkg/cli/admin/release/extract.go
- pkg/cli/admin/release/mirror.go
- pkg/cli/image/extract/extract.go
There's no reason we can't do things like "extract manifests to a directory" and "extract a single thing to a file", etc. simultaneously.  This pull request is the first portion of changes to consolidate shared logic, and reduce the amount of case-specific code.  It should mostly be a no-op refactor for users, except for the extension of verification coverage to cases that previously lacked verification.
> pkg/cli/admin/release/extract: Unify extraction cases

- pkg/cli/admin/release/extract.go
Otherwise it confuses other tools that take the JSON output from extraction.
Fixes: https://github.com/openshift/oc/pull/1237
@wking
> pkg/cli/admin/release/extract: Don't print image metadata verification messages when extracting to stdout

- pkg/cli/debug/debug.go
- pkg/cli/version/version.go
This PR;
- uses `GetKustomizeModVersion()` function to get kustomize version instead using static one. Because https://github.com/kubernetes/kubernetes/pull/109430 patch was merged and landed on o/k
- adds check to not create temporary namespace if `dry-run` flag is passed to `oc debug node`. It is redundant operation for dry-run.
- relies on `printFlags` functions instead manual output calculations. `printFlags` already supports required functionality.
> oc debug,version: minor todo improvements

- pkg/cli/login/loginoptions.go
Initially, all project-listing errors were fatal.  bcf5470fe7 began tolerating `IsNotFound`.  40e76d093d began tolerating `IsForbidden`.  But sometimes the error can be on the service side, [like][1]:
```console
$ oc login --token=...
Logged into "https://api..." as "..." using the token provided.
Error from server (Timeout): the server was unable to return a response in the time allotted, but may still be processing the request (get projects.project.openshift.io)
```
With this commit, we log the error, so the caller is aware that we had problems, but we fall back to `default`, because it's hard to imagine a situation where the caller would rather not be logged in.  If they want to adjust their default project after logging in, they can always do that in follow-up work.
[1]: …
> OCPBUGS-2495: pkg/cli/login: Warn, but do not fail, on surprise project-list errors

- pkg/helpers/newapp/app/sourcelookup.go
When a user tries to create a new-app with a SSH based repository, `oc` fails on not being able to `git ls-remote --heads` due authentication error, i.e.:
```
$ oc new-app --v=8 --source-secret=github-repo-key --name=test-app 'git@github.com:otaviof/nodejs-ex.git'
I1019 09:41:10.701737   24709 loader.go:374] Config loaded from file:  /home/otaviof/.kube/config
I1019 09:41:10.702768   24709 sourcelookup.go:316] Checking if git@github.com:otaviof/nodejs-ex.git requires authentication
I1019 09:41:10.702789   24709 repository.go:450] Executing git ls-remote --heads git@github.com:otaviof/nodejs-ex.git
I1019 09:41:10.702811   24709 repository.go:459] Environment:
I1019 09:41:10.702818   24709 repository.go:461] - HOME=/tmp/githome2802467764
I1019 09:41:10.702825   24709 repository.go:461] - …
```
> Bug 2078694: New-App Using Git via SSH

- pkg/helpers/newapp/cmd/newapp.go
Bumping openshift-apiserver brings with it stricter validation of namespace (obj vs. request).
> use correct namespace with sample templates

- pkg/cli/debug/debug.go
When user tries to debug a pod, priorityClassName is automatically copied to this debug pod. However, there is no such information for node debugging.
This PR adds "openshift-user-critical" priorityClassName into node debugging pod which means that "it is fine node debugging pod to be preempted by user-workload and OOMKilled."[1]
[1] https://github.com/openshift/enhancements/blob/master/CONVENTIONS.md#priority-classes
> Bug 2093046: oc debug: Add priorityClassName into node debugging pod template

- pkg/cli/image/manifest/manifest.go
- pkg/cli/registry/login/login.go
- pkg/helpers/image/helpers.go
to be in line with podman behaviour. Changes were originally introduced in https://github.com/openshift/oc/pull/1011
- workaround for empty files: delete the empty file before
- support for stdout output is removed
> remove support for empty files and stdout in oc registry login 

- pkg/cli/admin/release/extract_tools.go
A linux/arm64 installer binary will be created by https://github.com/openshift/installer/pull/6514, but this remains compatible with versions that don't have.  linux/arm64 oc has been available for a while.
> release: extract linux/arm64 binaries from all payloads

- pkg/cli/admin/upgrade/upgrade.go
- pkg/cli/admin/upgrade/upgrade_test.go
Spun out of [this comment][0].
cae0b5e096 (openshift/origin#22644) moved this code from Failing to Degraded, likely inspired by openshift/api#287.  But Degraded is only used in ClusterOperator. ClusterVersion kept using Failing, as seen in openshift/cluster-version-operator#191.  This commit returns us to watching for Failing (the condition the CVO has been setting the whole time), and informing the caller for any non-happy statuses (or the lack of a Failing condition at all).
Even though the issue causing `Failing=True` may block the current update from progressing, it should not block admins from requesting a new update target.  For some bugs, retargeting is the recommended way to resolve the issue that is currently sticking the update ([one example][1]).
[0]: …
> OCPBUGS-3714: pkg/cli/admin/upgrade: Report on Failing!=False conditions

- pkg/cli/admin/upgrade/upgrade.go
The outgoing wording dates back to the initial subcommand implementation in openshift/origin@65cce8c37d (openshift/origin#21605).  But "force" is easy to conflate with the `--force` option, and we occasionally hear of users who set `--force` under the mistaken impression that it is related to the recommended-ness of the target release image.  There's already a paragraph in the generic `--help` text discussing the risks of `--allow-explicit-upgrade`, and folks who use `--to-image` in the absence of recommended updates will hear about `--allow-explicit-upgrade` when a bare `--to-image` fails to turn up the requested pullspec in `availableUpdates`.
> pkg/cli/admin/upgrade: Drop "force" from "No updates available"

- pkg/cli/admin/release/info.go
- pkg/cli/admin/release/info_test.go
Comparing release text for various arch-specific shards of the multi-arch 4.12.0-rc.0 release:
```console
$ for B in arm64 ppc64le s390x; do diff -u <(curl -s https://mirror.openshift.com/pub/openshift-v4/multi/clients/ocp/4.12.0-rc.0/amd64/release.txt) <(curl -s "https://mirror.openshift.com/pub/openshift-v4/multi/clients/ocp/4.12.0-rc.0/${B}/release.txt"); done
--- /dev/fd/63  2022-11-16 14:57:24.849975880 -0800
+++ /dev/fd/62  2022-11-16 14:57:24.854975880 -0800
@@ -13,7 +13,7 @@
Name:           4.12.0-rc.0
Digest:         sha256:7ac78aaca993bf307010e8e92642da2bc28e275fbac241b42f24be46153f12d1
Created:        2022-11-10T19:12:09Z
-OS/Arch:        linux/amd64
+OS/Arch:        linux/arm64
Manifests:      643
Metadata files: 1
--- /dev/fd/63  2022-11-16 14:57:26.195975808 -0800
+++ …
```
> pkg/cli/admin/release/info: Render multi-arch release information

- pkg/cli/importimage/importimage.go
This PR returns import image error retrieved from server to return correct exit code.
> OCPBUGS-4280: oc import-image: reflect import image error

- pkg/cli/image/archive/archive.go
Currently on darwin, archiving is failing by raising unsupported system error.
This PR handles that error and proceeds to archiving.
This is basically the same approach applied in here https://github.com/openshift/oc/blob/952066e54e7b9a487f321d3266161786ff8ab742/pkg/cli/image/archive/archive.go#L444
> OCPBUGS-3526: Proceed archive if Lsetxattr gets unsupported error

- pkg/cli/admin/release/extract.go
- pkg/cli/admin/release/info.go
- pkg/cli/admin/release/mirror.go
- pkg/cli/admin/release/new.go
Align OCP versions with the new CI registry
> Rename registry.svc.ci.openshift.org to registry.ci.openshift.org

- pkg/cli/admin/release/extract_tools.go
Fixes [ARMOCP-469](https://issues.redhat.com/browse/ARMOCP-469)
> Handle non-amd64 command pulls from amd64 payload

- pkg/cli/admin/release/bug.go
- pkg/cli/admin/release/bug_test.go
- pkg/cli/admin/release/git.go
- pkg/cli/admin/release/git_test.go
- pkg/cli/admin/release/info.go
for discussion on workloads call.
This allows the changelog to link to all the jira tickets(i.e. also stories/epics) referenced in commits, not just OCPBUGS tickets.
> FDN-112: Parse any jira reference from commit text, not just OCPBUGS

- pkg/cli/admin/mustgather/mustgather.go
Provide a visible flag to run must-gather in its own name space. Originally an experimental flag.
> WRKLDS-629: oc adm must-gather: unhidden --run-namespace flag

- pkg/cli/cli.go
- pkg/cli/kubectlwrappers/wrappers.go
/assign @sanchezl @ardaguclu
This will unblock the rebase PR, we will need to expose this either way, but this should be enough to get the e2e passing. 
1.26 PR: https://github.com/openshift/kubernetes/pull/1432
> Expose events command to land k8s 1.26

- pkg/cli/importimage/importimage.go
- pkg/cli/importimage/importimage_test.go
issues.redhat.com/browse/IR-260
> IR-260: Add CLI flag to set ImportMode when importing a tag

- pkg/cli/tag/tag.go
- pkg/cli/tag/tag_test.go
Adds the given value (one of "PreserveOriginal", "Legacy", "") to the resulting ImageStreamTag. Invalid values result in an error by the API server.
https://issues.redhat.com/browse/IR-261
See also: https://github.com/openshift/oc/pull/1289/
> IR-261: Add --import-mode to 'tag'

- pkg/cli/admin/release/bug.go
- pkg/cli/admin/release/bug_test.go
- pkg/cli/admin/release/info.go
A request has been made to enable the release-controller to display feature-orientated differences, specifically, for 4.Next releases, but it will also be available for all releases.  To accomplish this, we'd like the enable `oc` to be able to generate it's changelog information in a format other than markdown, for easier post-processing.  This PR has an initial attempt at making as close to a 1-1 mapping from the markdown output to a JSON payload.
For example, the release-controller's output for a difference between `4.12.0-rc.7` and `4.12.0-rc.8` can be observed [here](https://amd64.ocp.releases.ci.openshift.org/dashboards/compare?from=4.12.0-rc.7&to=4.12.0-rc.8).  The release-controller does a minimal amount of processing to the output of the following command:
```
oc adm release info …
```
> Enable Changelog to output in JSON

- pkg/cli/admin/mustgather/mustgather.go
Commit dc5504ff0383bde3c5fa86d4cbc4c3d6c878f703 adds the ability to run must-gather in a namespace skipping rope binding operations. With [WRKLDS-629](https://issues.redhat.com//browse/WRKLDS-629) or PR #1313 in 4.13 we no long consider this experimental, so this log/error is incorrect
> WRKLDS-629: release run-namspace functionality

- pkg/cli/admin/release/info.go
Removing an extraneous parenthesis included in the output of the JSON formatted Changelog.
> Removing unwanted character from changelog output

- pkg/cli/admin/release/new.go
For OKD payloads it would be useful to display kernel (if its overriden) and CRI-O versions used
> OCPBUGS-3473: oc adm release new: allow specifying crio and kernel versions

- pkg/cli/debug/debug.go
Currently, `Quiet` and `ContainerName` fields are managed by setting
directly to `Attach` command's fields. This creates tight coupling,
that's why, this PR adds these fields into `oc debug` command.
Main motivation behind this change is better aligning with `kubectl debug`
in terms of flag management to ease the future integration.
Moreover, this PR does a few refactorings like renaming and moving
adding flags to it's own function.
> oc debug: Use own fields instead directly depending on Attach's

- OWNERS_ALIASES
Catching up with openshift/cluster-version-operator@f921431cca (openshift/cluster-version-operator#891).
> OWNERS_ALIASES: Update approvers: add David, remove Jack

- pkg/cli/admin/admin.go
- pkg/cli/admin/migrate/icsp/icsp.go
- pkg/cli/admin/migrate/icsp/icsp_test.go
According to the discuusion [resolution](https://docs.google.com/document/d/13h6IJn8wlzXdiPMvCWlMEHOXXqEZ9_GYOl02Wldb3z8/edit?usp=sharing), having a tool in oc to convert icsp file is helpul to land new CRD imagedigestmirrorset. This pr propose command `oc image convert` to convert passed in icsp file to idms file.
```
$ ./oc adm migrate icsp --help
Update imagecontentsourcepolicy file(s) to imagedigestmirrorset file(s). If --dest-dir is unset, the
imagedigestmirrorset file(s) that can be added to a cluster will be written to file(s) under the current directory.
Examples:
oc adm migrate icsp imagecontentsourcepolicy.yaml --dest-dir mydir
Options:
--dest-dir='':
Set a specific directory on the local machine to write imagedigestmirrorset file(s) to.
Usage:
oc adm migrate icsp [flags] …
```
> [OCPNODE-521] Add icsp file convert command

- pkg/cli/admin/upgrade/channel/channel.go
Like 123fa58184 (#1111), but for the `channel` subcommand. 123fa58184 described the general risk of using POST/Update when the local `oc` client may not be aware of some new spec properties.  For the `channel` subcommand specifically, it was added in 4.9:
```console
$ git ls-tree -r origin/release-4.8 -- pkg/cli/admin/upgrade
100644 blob 578fa80a8162d0cdfc6cb277e7b09c3bbad81444    pkg/cli/admin/upgrade/OWNERS
100644 blob e2418c1a0b931f4d444154a6b180855431bba72d    pkg/cli/admin/upgrade/upgrade.go
100644 blob 581af58611b0b4c11d5a6a2fbb9e14796e869ce4    pkg/cli/admin/upgrade/upgrade_test.go
$ git ls-tree -r origin/release-4.9 -- pkg/cli/admin/upgrade
100644 blob 578fa80a8162d0cdfc6cb277e7b09c3bbad81444    pkg/cli/admin/upgrade/OWNERS
100644 blob b427176401a5ec5973468dc569442fed04701744 …
```
> OCPBUGS-7780: pkg/cli/admin/upgrade/channel: Use PATCH instead of POST for spec updates

- pkg/cli/admin/mustgather/mustgather.go
This is so oc adm must-gather works by default in hypershift clusters.
Ref https://issues.redhat.com/browse/HOSTEDCP-836
> Do not set master node selector if there's no masters

- pkg/cli/image/strategy/onerror.go
- pkg/cli/image/strategy/onerror_test.go
Currently, when icsp file is passed, oc does not search in subrepositories. This PR adds ability that is searching also in subrepositories.
This PR basically applies the same mechanism used in here https://github.com/openshift/image-registry/blob/master/pkg/dockerregistry/server/simplelookupicsp.go for the same purpose.
> OCPBUGS-5949: Add subrepository support for ICSP

- pkg/helpers/newapp/newapptest/newapp_test.go
needed because of the files removal in https://github.com/sclorg/s2i-ruby-container/pull/462
> OCPBUGS-10622: bump repo sclorg/s2i-ruby-container location for newapp test

- images/cli-artifacts/Dockerfile.rhel
The `oc` binary copied into the `/usr/bin` folder when building the cli-artifacts image is always the one built for amd64. 
This PR proposes:
1. To shorten the number of `COPY` layers by copying and adapting the folder names later in a `RUN` layer;
2. instead of copying, a symbolic link to the correct architecture binary in /usr/bin, to also reduce the size of the final image.
Refers OCPBUGS-1117
> OCPBUGS-1117: The architecture of oc in the cli-artifacts' /usr/bin folder should to the one of the built image

- pkg/cli/image/mirror/mirror.go
The assuption that the manifest existing means that the blobs exist only works when the target is a registry that will validate that the blobs have been uploaded before the manifest. On other targets, we should check for layer existence each time because the user may have used "--continue-on-error" and end up with missing layers.
https://issues.redhat.com/browse/OCPBUGS-3393
> OCPBUGS-3393: Always copy the blobs if the target isn't a registry

- pkg/helpers/source-to-image/git/testhelpers.go
We can't run the unit tests out-of-the-box on up-to-date systems because of the fix for CVE-2022-39253.
Newer git versions default to not trusting cloning over the file transport. We now need to explicitly turn it on for this test, which we know is safe because we just created both repos.
More info: https://github.blog/2022-10-18-git-security-vulnerabilities-announced/#cve-2022-39253
```
jammy:oc$ SKIP_EXTERNAL_GIT=true make test
go test -mod=vendor -race ./...
ok      github.com/openshift/oc/cmd/oc  0.121s
ok      github.com/openshift/oc/pkg/cli 0.665s
?       github.com/openshift/oc/pkg/cli/admin   [no test files]
?       github.com/openshift/oc/pkg/cli/admin/buildchain        [no test files]
ok      github.com/openshift/oc/pkg/cli/admin/catalog   7.830s
? …
```
> Test Fix: Allow submodule using file transport with newer git

- pkg/helpers/graph/buildgraph/analysis/bc.go
Currently when user runs `oc status --suggest` if misconfigured registry is detected, `oc` suggests to run `oc adm registry -h` command. However, this command is deprecated and removed, this PR instead suggests correct command `oc registry -h`.
> OCPBUGS-10879: Fix deprecated oc command suggestion

- pkg/cli/newapp/newapp.go
- pkg/cli/newbuild/newbuild.go
- pkg/helpers/newapp/app/builder.go
- pkg/helpers/newapp/app/componentmatch.go
- pkg/helpers/newapp/app/dockerimagelookup.go
- pkg/helpers/newapp/app/imageref.go
- pkg/helpers/newapp/app/imagestreamlookup.go
- pkg/helpers/newapp/app/pipeline.go
- pkg/helpers/newapp/cmd/newapp.go
[IR-300](https://issues.redhat.com//browse/IR-300)
- add new flag --import-mode=Legacy or --import-mode=PreserveOriginal
- the default is Legacy
[IR-301](https://issues.redhat.com//browse/IR-301)
- support Legacy and PreserveOriginal import-mode with oc new-build
- add a guard to protect a panic when no DockerConfig exists
- add a PreserveOriginal guard for IsBuilderImage
The scope of this issue is limited to the imported images. The use of BuildConfig is not addressed in this PR, and is addressed in a separate backlog issue with the BuildConfig team.
> IR-300,IR-301: generates ImageStreamTags with import-mode when using oc new-build and oc-new-app

- pkg/cli/admin/upgrade/upgrade.go
`Invalid=True`, `Failing=True`, and `Progressing=True` are all reasons we might want to delay a transition to multi-arch.  Copy over the block from the version-bumping switch case, so we get the usual checks for `--to-multi-arch` too.  The user may opt to waive these guards with `--allow-upgrade-with-warnings` as usual, but at least they'll be aware that there are issues they may want to look into.
> OCPBUGS-8048: pkg/cli/admin/upgrade: Client-side checks for --to-multi-arch

- pkg/cli/image/append/append.go
- pkg/cli/image/manifest/manifest.go
The keep-manifest-list option for the append command was not exposed externally and only used in the case of creating the release image. This PR aims to expose this option while also keeping functionality intact. So, this means:
-  keep-manifest-list will always preserve the manifestlist when appending images. when used with --filter-by-os, the 
append will only happen for filtered images.
-  if keep-manifest-list is not specified, functionality will be same as before.
> append: expose keep-manifest-list option and preserve manifestlist when appending to specific arch images

- pkg/cli/image/extract/extract.go
- pkg/cli/image/manifest/errors.go
- pkg/cli/image/manifest/manifest.go
Fixes [OCPBUGS-1115](https://issues.redhat.com/browse/OCPBUGS-1115).
When extracting 'oc' from a manifest listed image, if the --no-filter-by-os flag was not used and an image could not be found for the runtime OS/runtime arch combination, warn the user a manifest image could not be found for this combination and try searching for a linux/runtime arch combination again in the manifest listed image.
> OCPBUGS-1115: Use linux/arch when user's OS isn't in manifests 

- pkg/cli/debug/debug.go
`oc debug` command uses same deterministic pod name in every execution(if matching pod name exists, it deletes this pod and re-creates it). 
Currently, some CI jobs rely on executing `oc debug` multiple times in a short period
of time. When it happens, sometimes informers might return previous container's
terminated state(although genuine container hasn't started yet). This causes debug command fails intermittently.
This might be considered an issue in informers but wouldn't it be also better to add suffix(just how [kubectl debug does](https://github.com/kubernetes/kubernetes/blob/d89d5ab2680bc74fe4487ad71e514f4e0812d9ce/staging/src/k8s.io/kubectl/pkg/cmd/debug/debug.go#L584)) to set apart debug pods from each other. If user still wants to attach same container, he/she can pass …
> OCPBUGS-10843: oc debug unique pod name

- pkg/cli/image/manifest/manifest.go
Currently, the original index digest is maintained because the variable containing the digest is incorrectly scoped instead of being overwritten.
> OCPBUGS-8004: Fix bug when recreating an index with fewer images

- pkg/cli/image/manifest/manifest.go
We only need to tell the registry we accept them, the registry client code already handles OCI manifests transparently for us.
> Support OCI manifest lists in image mirror

- pkg/cli/admin/prune/imageprune/helper_test.go
replaces trimLeft function with the more appropriate trimPrefix to avoid potential bugs.
for example:
```golang
// will output ello.test
fmt.Println(strings.TrimLeft("hello.test", "http://"))
```
> replace trimLeft with trimPrefix

- pkg/cli/admin/upgrade/upgrade.go
The outgoing docs were frequently conflated.  The incoming docs hopefully make the distinction clearer, and they list the client-side `checkForUpgrade` conditions.  I haven't mentioned the `Invalid` check, because that trips so rarely, but I have used the open-ended "include checks for...", so folks aren't too surprised if they hit a client-side guard that's not listed in the docs.  The "failing clusters" bit is a lie, but that's already tracked in #900, and eventually I'll be able to talk someone into reviewing the fix.
The cluster-side guards are also open-ended, although I do call out both release verification (signature checks and similar) andupgradeable conditions, since those are declared in [the `force` godocs][2].  I do not mention additional guards like [the etcd backups][3], …
> pkg/cli/admin/upgrade: Clarify client-side vs. server-side docs

- .ci-operator.yaml
- go.mod
- images/cli-artifacts/Dockerfile.rhel
- images/cli/Dockerfile.rhel
- pkg/cli/login/loginoptions.go
Currently, `oc login` has some logic when user gets x509 certificate errors.
However in Go 1.20(with [this commit](https://go-review.googlesource.com/c/go/+/449336)) and upward versions, these certificate errors are wrapped in
`tls.CertificateVerificationError`(https://pkg.go.dev/crypto/tls#CertificateVerificationError). In order to keep the same functionality,
`oc login` needs to detect this type and extract correct error.
Furthermore, since this new type has been only added into Go 1.20,
we also need to bump `oc` to 1.20. 
This PR is also prerequisite for the openshift/kubernetes
1.27 vendoring of `oc`.
> OCPBUGS-12143: oc login: unwrap tls.CertificateVerificationError to use x509 errors

- pkg/cli/admin/inspect/util.go
Currently, `oc adm inspect` command aggregates error messages and prints them once. 
Event filtering unification mechanism returns plain errors but we need more explanatory error messages
to troubleshoot issues. 
This PR improves these. This PR does not solve the referenced bug, instead
it makes it easier to investigate problem.
> OCPBUGS-11632: Improve error log messages in event filtering

- pkg/helpers/groupsync/grouplister.go
The original design limited the ldap to openshift group mapping to a single group: https://github.com/openshift/api/blob/4f3c947a2271264efd787eebeec05deb141e0333/legacyconfig/v1/types.go#L1306
The current implementation does not allow to cleanly error without disrupting already existing automation which is either not aware of this restriction or willingly ignores it. We can only print a warning.
> OCPBUGS-11123: oc adm groups sync: print a warning when two or more groups are mapped to the same ldap uid

- pkg/cli/admin/upgrade/upgrade.go
This preserves the specified release image (using `--to-image=''`) in the ClusterVersion object.
> OCPBUGS-12901: preserve explicit release image in ClusterVersion

- pkg/helpers/newapp/newapptest/newapp_test.go
It seems that `registry.centos.org` is permanently closed and unit tests in oc relying on this
registry started failing(as seen in https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_oc/1429/pull-ci-openshift-oc-master-unit/1661706541889228800). This PR changes the tests to use appropriate images in `quay.io`.
> OCPBUGS-14082: Remove closed centos7 registry from newapp unit tests

- pkg/cli/admin/inspect/util.go
Although it is rare, if `events.yaml` file is invalid, `oc adm must-gather` and `oc adm inspect` commands return non zero exit code because they fail when generating `event-filter.html`. Since we don't have control on events, we can warn user and continue process instead returning error.
> OCPBUGS-11632: Skip invalid events yamls and continue

- pkg/cli/admin/release/mirror.go
Currently, `oc adm release mirror` does mirror the multi release image, but it will mirror all of the images with `-x86_64` in the tag:
`oc adm release mirror quay.io/openshift-release-dev/ocp-release:4.12.13-multi --keep-manifest-list=true --to=someregistry.io/somewhere/release `
This PR will rename containers w/`-multi` if the release image is manifest listed AND if `--keep-manifest-list=true`.
> OCPBUGS-14340: Name containers w/'multi' when mirroring a multi release image

- pkg/cli/admin/node/logs.go
- Map --tail internally to tailLines
- Map --unit internally to query
- Use service instead of journal in the help to normalize across Linux  and Windows
> OCPBUGS-11652: Extend adm node-logs to new API

- pkg/cli/admin/ocpcertificates/monitorregeneration/clusteroperator.go
- pkg/cli/admin/ocpcertificates/monitorregeneration/command.go
- pkg/cli/admin/ocpcertificates/monitorregeneration/configmap.go
- pkg/cli/admin/ocpcertificates/monitorregeneration/monitor.go
- pkg/cli/admin/ocpcertificates/monitorregeneration/monitoring_reflector_store.go
- pkg/cli/admin/ocpcertificates/monitorregeneration/secret.go
- pkg/cli/admin/ocpcertificates/ocp_certificates.go
Adds printing of static pod operator revisions so that we can watch the rollout happen and get reports of why a particular revision was created.  This is helpful for watching the manner in which new certificates trigger rollouts.
/assign @stlaz
> add printing for new revisions

- pkg/cli/config/refreshcabundle/refresh_ca_bundle.go
- pkg/cli/kubectlwrappers/ocp_config_command.go
- pkg/cli/kubectlwrappers/wrappers.go
Realistically the starting point will only be useable by cluster-admins.  The point of this is to use existing trust to get the updated/rotated trust during a rotation.
Convenient way to see the ca bundle in your kubeconfig
`oc config view --raw -o jsonpath='{.clusters[?(@.name == "the-name")].cluster.certificate-authority-data}' | base64 -d`
I got this compatible with general kubeconfigs.  Still needs good testing.  
/assign @stlaz
> add command to produce an updated CA bundle for trusting the kube-apiserver

- pkg/cli/config/adminkubeconfig/new_admin_kubeconfig.go
- pkg/cli/config/refreshcabundle/refresh_ca_bundle.go
- pkg/cli/kubectlwrappers/ocp_config_command.go
Add `oc config new-admin-kubeconfig` to create a new admin.kubeconfig using an existing connection.
/assign @stlaz
> create command to create new adminkubeconfig

- pkg/cli/admin/ocpcertificates/certregen/command.go
- pkg/cli/admin/ocpcertificates/certregen/leavesregen.go
- pkg/cli/admin/ocpcertificates/certregen/leavesregen_test.go
- pkg/cli/admin/ocpcertificates/certregen/rootregen.go
- pkg/cli/admin/ocpcertificates/certregen/rootregen_test.go
- pkg/cli/admin/ocpcertificates/ocp_certificates.go
- pkg/cli/admin/ocpcertificates/trustpurge/command.go
- pkg/cli/admin/ocpcertificates/trustpurge/trustpurge.go
- pkg/cli/admin/ocpcertificates/trustpurge/trustpurge_test.go
Adds the `oc adm ocp-certificates remove-old-trust` command.
TODO:
/assign @deads2k 
built on top of https://github.com/openshift/oc/pull/1443
> Add a command to remove older trust

- pkg/cli/clusteroperator/waitforstable/command.go
A running PR for today that will gain commits as I find things worthy of updates.
```
[deads@fedora oc]$ oc adm ocp-certificates regenerate-top-level -n openshift-kube-apiserver-operator secrets kube-apiserver-to-kubelet-signer kube-control-plane-signer  loadbalancer-serving-signer  localhost-serving-signer next-bound-service-account-signing-key service-network-serving-signer
secret/kube-apiserver-to-kubelet-signer regeneration set
secret/kube-control-plane-signer regeneration set
secret/loadbalancer-serving-signer regeneration set
secret/localhost-serving-signer regeneration set
secret/service-network-serving-signer regeneration set
[deads@fedora oc]$ oc adm clusteroperator wait-for-stable-cluster --minumum-stable-period=60s
All clusteroperators became stable at 2023-06-13T10:05:27-04:00 …
```
> tweaks needed for wait

- pkg/cli/config/adminkubeconfig/new_admin_kubeconfig.go
- pkg/cli/config/kubeletbootstrapkubeconfig/new_kubelet_bootstrap_kubeconfig.go
- pkg/cli/kubectlwrappers/ocp_config_command.go
builds on https://github.com/openshift/oc/pull/1452
`oc config new-kubelet-bootstrap-kubeconfig > ~/Downloads/bootstrap.kubeconfig`
/assign @rphillips
> add command to create new bootstrap kubeconfig for kubelet

- pkg/cli/image/extract/extract.go
- pkg/cli/image/strategy/explicit.go
- pkg/cli/image/strategy/explicit_test.go
- pkg/cli/image/strategy/onerror.go
- pkg/cli/image/strategy/onerror_test.go
This PR;
* adds foundational work to support IDMS(aka ImageDigestMirrorSet) as an alternative source
in addition to the ICSP. 
* introduces `--idms-file` in `oc image extract` depending on the foundational work above ^
* deprecates `--icsp-file` flag in `oc image extract` command to suggest `--idms-file` instead
> OCPNODE-1656: oc image extract: Introduce IDMS as alternative source

- go.mod
- go.sum
- pkg/cli/admin/ocpcertificates/ocp_certificates.go
- pkg/cli/admin/ocpcertificates/regeneratemco/command.go
- pkg/cli/admin/ocpcertificates/regeneratemco/rotatecerts.go
- pkg/cli/admin/ocpcertificates/regeneratemco/updatesecrets.go
- vendor/github.com/vincent-petithory/dataurl/LICENSE
- vendor/github.com/vincent-petithory/dataurl/README.md
- vendor/github.com/vincent-petithory/dataurl/dataurl.go
- vendor/github.com/vincent-petithory/dataurl/doc.go
- vendor/github.com/vincent-petithory/dataurl/lex.go
- vendor/github.com/vincent-petithory/dataurl/rfc2396.go
- vendor/github.com/vincent-petithory/dataurl/wercker.yml
- vendor/modules.txt
New oc command to rotate the Machine-Config-Server ca + cert. Also see: https://github.com/openshift/oc/pull/1449
To test this, take any cluster and run the command. Afterwards, try scaling a node into the cluster (e.g. on AWS, patch a worker machineset to add 1 more replica)
> ocpcertificates: add ability to rotate MCS CA/cert

- pkg/cli/admin/release/mirror.go
- pkg/cli/admin/release/mirror_test.go
story: https://issues.redhat.com/browse/OCPNODE-1580
Add `--print-mirror-instructions` flag to command oc adm release.
The printout instructions of the command will keep it as is if the flag is unset or set to `icsp`.
If set to `idms`, update the instruction output of `oc adm release mirror` to ImageDigestMirrorSet example.
The new ImageDigestMirrorSet examples are:
- use `imageDigestSources` field in install-config.yaml[1] that will creates ImageDigestMirrorSet manifests,
- manifest example of ImageDigestMirrorSet CRD
[1] Add `imageDigestSources` to install-config: https://github.com/openshift/installer/pull/6235
result of this patch:
```
LOCAL_REGISTRY=localhost:5000
LOCAL_REPOSITORY=ocp4/openshift4
LOCAL_SECRET_JSON=/home/qiwan/cluster/mysecret
sudo podman run -d -p 5000:5000 …
```
> OCPNODE-1580: Add --print-mirror-instructions to oc adm release mirror to allow idms instructions

- pkg/cli/admin/upgrade/upgrade.go
Cleaning up some nits from 6c8d9352d3 (#986).
> pkg/cli/admin/upgrade: Add post-period to space to some error messages

- pkg/cli/admin/upgrade/upgrade.go
Make a distinction between "all of these are not recommended for your cluster" and "we're having trouble figuring out if these risks apply to your cluster" more obvious to customers who haven't set `--include-not-recommended`.  For example, if the monitoring stack backing PromQL risk evaluation is unavailable, customers may want to assess their exposure manually, instead of waiting for an update recommendation that is not impacted by PromQL risks.
> pkg/cli/admin/upgrade: Surface Recommended=Unknown more prominently

- pkg/cli/login/loginoptions.go
The prompt appeared such as
```
Username: kubeadmin
Password: %!(EXTRA []interface {}=[])
```
due to a forgotten slice interface unwrap.
> Fix the output of error prompt

- pkg/cli/admin/waitfornodereboot/wait_for_node_reboot.go
Fixes
```
nodes/ failed getting current: resource name may not be empty
nodes/ip-10-0-242-72.us-west-1.compute.internal failed getting current: an error on the server ("read tcp 10.130.4.51:41854->13.56.72.38:6443: read: connection reset by peer") has prevented the request from succeeding (get nodes ip-10-0-242-72.us-west-1.compute.internal)
5 of 7 nodes rebooted, 0 rebooting to desired level: 2023-06-20T15:06:22-07:00
nodes/ failed getting current: resource name may not be empty
nodes/ failed getting current: resource name may not be empty
5 of 7 nodes rebooted, 0 rebooting to desired level: 2023-06-20T15:06:52-07:00
```
/assign @stlaz
> handle the error case of node retrieval while waiting for reboot

- pkg/cli/image/manifest/dockercredentials/auth_resolver.go
- pkg/cli/image/manifest/manifest.go
- pkg/cli/registry/login/login.go
- pkg/helpers/image/helpers.go
for storing and retrieving credentials
(${XDG_RUNTIME_DIR}/containers/auth.json by default). Docker config locations (usually ~/.docker/config.json) are still used as a fallback when podman
credentials are not found.
deprecate REGISTRY_AUTH_PREFERENCE env variable and warn about removal of docker auth preference in the future
TODO:
> OCPBUGS-10612: make registry auth prefence default to podman config locations 

- pkg/helpers/newapp/app/sourcelookup.go
When a user tries to create a new-app with a SSH based repository, `oc` fails on not being able to `git ls-remote --heads` due authentication error, i.e.:
```
$ oc new-app --v=8 --source-secret=github-repo-key --name=test-app 'git@github.com:otaviof/nodejs-ex.git'
I1019 09:41:10.701737   24709 loader.go:374] Config loaded from file:  /home/otaviof/.kube/config
I1019 09:41:10.702768   24709 sourcelookup.go:316] Checking if git@github.com:otaviof/nodejs-ex.git requires authentication
I1019 09:41:10.702789   24709 repository.go:450] Executing git ls-remote --heads git@github.com:otaviof/nodejs-ex.git
I1019 09:41:10.702811   24709 repository.go:459] Environment:
I1019 09:41:10.702818   24709 repository.go:461] - HOME=/tmp/githome2802467764
I1019 09:41:10.702825   24709 repository.go:461] - …
```
> OCPBUGS-4812:[release-4.11] New-App Using Git via SSH

- pkg/cli/image/append/append.go
There is no way to guarantee a single arch has been specified because the filter is a regex. This clarification explains the actual behaviour.
> Clarify the use of the filter without keep-manifest-list

- pkg/cli/image/extract/extract.go
`--idms-file` flag was introduced in oc image extract command with this PR https://github.com/openshift/oc/pull/1426/, however `-idms-file` is incorrectly mapping to `ICSPFile` field instead `IDMSFile`.
This PR fixes it.
/assign @QiWang19
> OCPBUGS-15012: oc image extract: idms-file flag map to IDMSFile field

- pkg/cli/admin/ocpcertificates/regeneratemco/command.go
- pkg/cli/admin/ocpcertificates/regeneratemco/rotatecerts.go
- pkg/cli/admin/ocpcertificates/regeneratemco/updatesecrets.go
In some cases, the MCS endpoint refers to the apiserver IP directly instead of the api-int url. Update the cert generation to account for this, otherwise we fail for those platforms.
Also update the kube-system root-ca cert for BM IPI, since BM IPI is the only platform that uses the MCO-generated and managed secret
> OCPBUGS-15776: mcs cert: account for environments that use IP directly

- pkg/helpers/kubeconfig/smart_merge.go
Ran into #1457 today when using tsh, kubectl, and oc. I was able to track this down and this patch was able to fix the missing field issue.
> Add tls-server-name when property exists in kubeconfig

- pkg/cli/admin/rebootmachineconfigpool/restart-template.json
The oldest version we want to run the cert rotation command on is 4.6, which has support only up to ignition spec 3.1 (3.2+ was introduced in 4.7)
Update the template to use 3.1 since it should be supported for all versions we want to run the procedure on.
> OCPBUGS-16009: reboot: set ignition version to 3.1

- pkg/cli/admin/release/extract.go
- pkg/cli/admin/release/mirror.go
De-duplicate the manifest-walking logic that used to be split between the `ExtractManifests` and `CredentialsRequests` branches.  The content written to disk (or `o.Out`) still depends on which of those two is set, but the manifest parsing portion is now shared from a common location.
This continues the effort begun in #1237 now that openshift/origin#27822 is in place to protect me from accidentally breaking things again.  The eventual goal is to [only extract expected-to-be-reconciled manifests][1], but I don't want to need to land that logic in two places, and this should be a no-op refactor that will allow me to land it in one place.
[1]: https://issues.redhat.com/browse/OTA-559
> OTA-994: pkg/cli/admin/release/extract: Centralize manifest extraction

- pkg/cli/login/login.go
This PR adds more informative text in the usage doc of `oc login --web` flag.
> login: improve usage message for --web option

- pkg/cli/admin/upgrade/upgrade.go
Fixing output like:
```console
$ oc adm upgrade --allow-upgrade-with-warnings --to 4.12.23
warning: --allow-upgrade-with-warnings is bypassing: the cluster is already upgrading:
Reason:
Message: Working towards 4.11.44: 681 of 806 done (84% complete)Requested update to 4.12.23
```
by adding a newline between the `... (84% complete)` error message, and the subsequent `Requested update to 4.12.23`.
> pkg/cli/admin/upgrade: Newlines after --allow-upgrade-with-warnings errors

- pkg/cli/admin/inspect/writer.go
oc adm inspect generated files sometime have the leading "---" and some time do not. This depends on the order of objects collected. This by itself is not an issue.
However this becomes an issue when combined with multiple invocations of oc adm inspect and collecting data to the same directory like must-gather does.
If an object is collected multiple times then the second time oc might overwrite the original file improperly and leave 4 bytes of the original content behind.
This is happening when not writing the "---\n" in the second invocation as this makes the content 4B shorter and the original tailing 4B are left in the file intact.
This garbage confuses YAML parsers.
> OCPBUGS-16735: Truncate existing files when writing from inspect

- pkg/cli/admin/release/extract.go
- pkg/cli/admin/release/extract_tools.go
- pkg/cli/admin/release/mirror.go
- pkg/cli/admin/release/new.go
- pkg/cli/admin/release/new_test.go
There are many manifests in release images.  CredentialsRequests, Deployments, ClusterOperators, etc., etc.  There are increasingly complicated conditions on whether the cluster-version operator reconciles or ignores a manifest, including [cluster profiles, cluster capabilities, and feature sets][1].  To make it easier for users to see the manifests that actually matter for their cluster, this commit adds `--included`, which uses [the same `Manifest.Include` logic used by the cluster-version operator][2].  As long as we keep the vendored copies of library-go close-ish between `oc` and the CVO, this will allow users to just get the manifests that apply to their cluster.  For example:
* You have enabled `TechPreviewNoUpgrade`, so here's [a CredentialsRequest for the `openshift-cluster-api` …
> OTA-559: pkg/cli/admin/release/extract: Add --included and --install-config

- pkg/cli/admin/release/extract.go
- pkg/cli/admin/release/extract_tools.go
- pkg/cli/admin/release/mirror.go
- pkg/cli/admin/release/new.go
- pkg/cli/admin/release/new_test.go
This reverts commit 9ec4f46e2fa3110f558900d5c482fb3b448bbc5d.
We suspect that https://github.com/openshift/oc/pull/1521 has broken all
Metal jobs, an example of a failure:
https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_cluster-baremetal-operator/355/pull-ci-openshift-cluster-baremetal-operator-master-e2e-metal-ipi-ovn-ipv6/1691359315740332032.
After the change, "oc adm extract" expects KUBECONFIG to be present, but at the point
when we call it, there is no cluster.
> OCPBUGS-17711: Revert "pkg/cli/admin/release/extract: Add --included and --install-config"

- pkg/cli/admin/prune/images/images.go
Allows the pruner to run on clusters without the DeploymentConfig capability.
> OCPBUGS-17925: pkg/cli/admin/prune/images: omit not found error for deployment configs

- cmd/oc/oc.go
- cmd/oc/oc_test.go
- pkg/cli/newapp/newapp.go
- pkg/cli/newapp/scheme.go
- pkg/cli/rollout/cancel.go
- pkg/cli/rollout/retry.go
- pkg/cli/set/buildhook.go
- pkg/cli/set/buildsecret.go
- pkg/cli/set/data.go
- pkg/cli/set/deploymenthook.go
- pkg/cli/set/env.go
- pkg/cli/set/helper.go
- pkg/cli/set/imagelookup.go
- pkg/cli/set/probe.go
- pkg/cli/set/routebackends.go
- pkg/cli/set/scheme.go
- pkg/cli/set/triggers.go
- pkg/cli/set/volume.go
- pkg/helpers/newapp/app/templatelookup.go
- pkg/helpers/newapp/cmd/newapp.go
- pkg/helpers/newapp/scheme.go
- pkg/helpers/scheme/scheme.go
Currently, route schema is registered for all commands in oc to
use it as native resource. Route is managed by openshift-apiserver and
up to this now, it works without any problem as well as vendoring
is happening in oc.
However, microshift does not have openshift-apiserver and that's why,
some commands behave differently whether object is native or CRD such
as `oc edit route`, `oc patch route`, etc. and these commands are failing on microshift.
To make `oc edit route` working on microshift, we have to remove registration
of routes.openshift.io and the rest of commands should work without any
problem embracing routes.openshift.io as CRD except that the `oc new-app`
and `oc set route-backends` commands. `oc new-app` must register Routes 
because there are templates creating route …
> OCPBUGS-15772: Decouple new-app and set commands scheme from global scheme

- pkg/cli/admin/release/git.go
Currently, `oc adm release info` changelog associates bump PRs to incorrect PR numbers, when the repository is a fork of an upstream repository. This PR eliminates these incorrect PR numbers by adding `--first-parent` to git log and only
shows the actual PR which already includes the diff.
`--first-parent` will only be added to merge commits and squash merges continue as is.
<details>
<summary>Output won't be changed for typical PRs</summary>
Output is identical with https://amd64.ocp.releases.ci.openshift.org/releasestream/4.15.0-0.nightly/release/4.15.0-0.nightly-2023-09-27-150522
```sh
$ ./oc adm release info registry.ci.openshift.org/ocp/release:4.15.0-0.nightly-2023-09-27-150522 --changelog='/tmp/test_changelog' --changes-from=registry.ci.openshift.org/ocp/release:4.15.0-0.nightly-202 …
```
> WRKLDS-537: oc adm release info: Add --first-parent to git log for simplification

- pkg/helpers/newapp/newapptest/newapp_test.go
docker mysql image frequently fails and causes unit test job's failure. This PR uses quay redis image instead docker image for the sake of unit test job's stability.
> OCPBUGS-20181: Use quay redis image instead docker mysql

- pkg/cli/admin/ocpcertificates/regeneratemco/rotatecerts.go
It turns out that cfg.Status.PlatformStatus.$PLATFORM can be nil, so add this check to not panic.
If the IP field doesn't exist we will go add the api-int url so this should otherwise not be a problem.
> OCPBUGS-20063: regeneratemco: explicitly check for PlatformStatus field

- pkg/cli/debug/debug.go
In `oc debug`, there are 2 types of tasks whose are not attached to terminal;
* short lived ones are handled directly and their exit codes are retrieved from the terminated pod's status(e.g. `oc debug node/worker -- /bash/bin -c "echo TEST"`).
* long lived ones are watched as long as they send logs to the client(e.g. `oc debug node/worker -- /bash/bin -c "sleep 5"`).
However, there is not exit code handler mechanism for the long lived ones, whenever logs are done, `oc debug` returns.
The problem is there is no clear boundaries between short lived and long lived ones. A `oc debug` command execution can fall into short lived and in another execution it can fall into long lived. Determination is done by informer's event retrieval periods and that creates undeterministic behavior.
To overcome …
> OCPBUGS-20342: Reflect container's exit code for long running tasks not attached to terminal

- pkg/cli/admin/release/mirror.go
When mirroring a multiarch payload via `oc adm release mirror --from=... --to-image-stream=release --keep-manifest-list=true`, the ImageStreamTags are created with the default ImportPolicy.ImportMode (Legacy). Therefore, the release is not mirrored as multiarch/manifest-list, but will be mirrored as a single-arch manifest depending on the architecture of the cluster's node running the internal registry.
> OCPBUGS-20474: Set ImportPolicy to PreserveOriginal to honor --keep-manifest-list when mirroring a payload to an image stream

- pkg/cli/admin/upgrade/upgrade.go
Avoid confusion like we had with `oc adm upgrade channel`, where folks running older `oc` (where `channel` didn't exist) had the command no-op and exit 0.  With this change, that sort of thing will give:
```console
$ oc adm upgrade does-not-exist
error: unknown command "does-not-exist"
See 'oc adm upgrade -h' for help and examples
```
> OCPBUGS-9340: pkg/cli/admin/upgrade: Warn on unrecognized subcommands

- pkg/cli/admin/upgrade/status/status.go
- pkg/cli/admin/upgrade/upgrade.go
Initial scaffolding, based on the existing code for status rendering in `oc adm upgrade`.  I'm gating the new subcommand behind an `OC_ENABLE_CMD_UPGRADE_STATUS` feature gate to avoid surprising users with a volatile command while the implementation settles down.
```console
$ ./oc adm upgrade  status
error: unknown command "status"
See 'oc adm upgrade -h' for help and examples
$ OC_ENABLE_CMD_UPGRADE_STATUS=true ./oc adm upgrade --help
...
Available Commands:
channel       Set or clear the update channel
status        Display the status of current cluster version updates.
...
$ OC_ENABLE_CMD_UPGRADE_STATUS=true ./oc adm upgrade status
The cluster version is not updating (Progressing=False).
Reason:
Message: Cluster version is 4.13.10
```
> pkg/cli/admin/update: Add tech-preview 'oc adm upgrade status'

- pkg/cli/admin/groups/new/new.go
- pkg/cli/admin/groups/sync/prune.go
- pkg/cli/admin/groups/sync/sync.go
- pkg/cli/admin/groups/users/add.go
- pkg/cli/admin/policy/modify_roles.go
- pkg/cli/admin/prune/auth/prune_command.go
- pkg/cli/admin/verifyimagesignature/verify-signature.go
- pkg/cli/create/user.go
- pkg/cli/create/user_identity_mapping.go
- pkg/cli/whoami/whoami.go
All commands using the `userv1` clients should be wrapped now.
```
$ for file in $( git grep -l 'clientset/versioned/typed/user/v1' | grep -v vendor ); do if ! grep -q 'CheckOAuthDisabledErr' $file; then echo $file; fi; done
pkg/cli/admin/groups/sync/interfaces.go    # just interfaces, no impl
pkg/cli/admin/prune/auth/group_test.go     # test
pkg/cli/admin/prune/auth/user.go           # helper func, caller handles it
pkg/cli/admin/prune/auth/user_test.go      # test
pkg/helpers/describe/describer.go          # TODO: need to figure this out
pkg/helpers/groupsync/grouplister.go       # helper func, caller handles it
pkg/helpers/groupsync/grouplister_test.go  # test
pkg/helpers/groupsync/grouppruner.go       # helper func, caller handles it
pkg/helpers/groupsync/grouppruner_test.go  # test …
```
> oc/*: gracefully fail when user group is not configured

- pkg/cli/admin/upgrade/status/status.go
As a cluster admin, I want to understand how the update is going, relative to [my expectations around duration][1].  If it's waiting on the Kube API server 5 minutes into the update, that's expected.  If it's waiting on the Kube API server an hour into the update, that's unexpected.  There is not a lot of information here, but while it is a small amount of context, it only consumes a few characters.
```console
$ OC_ENABLE_CMD_UPGRADE_STATUS=true ./oc adm upgrade status
An update is in progress for 44m40s: Working towards 4.13.17: 683 of 843 done (81% complete), waiting on network
```
[1]: https://docs.openshift.com/container-platform/4.14/updating/understanding_updates/understanding-openshift-update-duration.html
> pkg/cli/admin/upgrade/status: Add update duration

- pkg/cli/whoami/whoami.go
- pkg/cli/whoami/whoami_test.go
- pkg/helpers/project/whoami.go
Currently, `oc whoami` assumes that internal oauth is enabled and that's
why, it fails when an error is gotten from server. However, cluster might
be configured to rely on external OIDC issuer and internal oauth server
might be disabled. Even in that case, `oc whoami` should return the
correct data.
Same rules also apply for project whoami. It can use
selfsubjectreview endpoint as well.
This PR prioritizes asking to selfsubjectreview endpoint to
get this information and if selfsubjectreview fails, it falls back to
oauth server's user object.
> WRKLDS-874: oc whoami: Ask from selfsubjectreview and fallback to internal oauth

- hack/clibyexample/template
- hack/clibyexample/template-admin
Per https://github.com/redhat-documentation/modular-docs/issues/203, documentation changed the content type variable we need to use from `:_content-type:` to `:_mod-docs-content-type:`.
This PR fixes that in the templates that are used when auto-generating the CLI reference docs.
> Updating content type variable name for CLI docs generation

- pkg/cli/admin/upgrade/status/examples/README.md
- pkg/cli/admin/upgrade/status/examples/not-upgrading-co.yaml
- pkg/cli/admin/upgrade/status/examples/not-upgrading-cv.yaml
- pkg/cli/admin/upgrade/status/examples/not-upgrading.output
- pkg/cli/admin/upgrade/status/examples_test.go
- pkg/cli/admin/upgrade/status/status.go
While `oc adm upgrade status` is under development, logic is client-side, and
behind feature gate, it is useful to avoid relying on an actual upgrading
cluster in an interesting state at hand.
This will also allow us to capture interesting "stuck" upgrade cases and
back-test further development on previously seen interesting states.
I have added a simple improvement commit to this PR (emiting `<none>` when a reason or message is empty) to illustrate:
```console
$ OC_ENABLE_CMD_UPGRADE_STATUS=true ./oc --context build01 adm upgrade status
error: You must be logged in to the server (Unauthorized)
// my $KUBECONFIG does not have an authorized b01 context so I cannot test 
$ OC_ENABLE_CMD_UPGRADE_STATUS=true ./oc --context build01 adm upgrade status \ …
```
> OTA-1035: Allow testing `adm upgrade status` on mock data

- pkg/cli/admin/inspect/inspect.go
When error occurs during inspection, current message `errors occurred while gathering data` may mislead
users about that the command short cuts inspection process and exits. However, in reality, command prints all the logs
in aggregated format after completing the inspection.
This PR basically just adds `inspection completed` message ahead of the error logs to emphasize to user that
inspection is completed in best effort and the rest is the errors we get.
> OCPBUGS-23071: Mention inspection completion in the error message

- images/cli-artifacts/Dockerfile.rhel
Fixes rolled out for FIPS make it impossible for a binary compiled on RHELX to run on RHELY (in a FIPS compliant way) if the RHELY host is running with FIPS enabled.
This is because the binary will not find a compatible OpenSSL library and fall back to using internal Go crypto. Only OpenSSL is FIPS certified.
With the introduction of "FIPS or Die", binaries run in FIPS mode but which cannot use OpenSSL will exit with an error. Customers using RHEL7 with FIPS enabled, therefore, need a RHEL7 based oc.
> ART-8372: el7 version of oc in 4.11

- pkg/cli/process/process.go
https://github.com/openshift/oc/pull/1318 fixes only when the template is passed
directly. But the problem still exists, when the template is passed in a file.
This PR overwrites the namespace in template with the one passed explicitly
in command, when template's namespace and explicit namespace is mismatched.
> OCPBUGS-24375: Overwrite template's namespace with the explicit one

- pkg/cli/cli.go
It seemed reasonable to add `WithDeprecatedPasswordFlag` to sync with kubectl in https://github.com/openshift/oc/pull/1424#discussion_r1269268904. However, 
unexpectedly this caused a slight behavioral change in oc command as filed in
https://github.com/openshift/oc/issues/1615 and the referenced issue to this PR.
The reason of the failure is when password is not nil(instead it is empty string ""), 
config flags prompts user to enter username and password to move forward https://github.com/kubernetes/kubernetes/blob/a504aed54d028dbc8ea2508142c94d309f5f1ec6/staging/src/k8s.io/cli-runtime/pkg/genericclioptions/config_flags.go#L235. However, prior oc behavior is
password should be nil and it returns non interactive config https://github.com/kubernetes/kubernetes/blob/a504aed54d028dbc8ea250814 …
> OCPBUGS-24225: Remove deprecated password defaulting in default config flag

- .ci-operator.yaml
- go.mod
- go.sum
- images/cli-artifacts/Dockerfile.rhel
- images/cli/Dockerfile.rhel
- images/deployer/Dockerfile.rhel
- images/tools/Dockerfile
Manual attempt to also bump go, replacing;
* https://github.com/openshift/oc/pull/1627
* https://github.com/openshift/oc/pull/1626
* https://github.com/openshift/oc/pull/1625
* https://github.com/openshift/oc/pull/1621
> OCPBUGS-25021: Bump ocp images to 4.16 in addition to go 1.21

- images/cli-artifacts/Dockerfile.rhel
This PR generates RHEL9 FIPS enabled compatible oc binaries in linux_amd64,
linux_arm64, linux_ppc64le architectures and saves them as oc.rhel9(this will be backported to 4.15 and 4.14).
> OCPBUGS-23386: Generate FIPS compatible RHEL9 oc binary

- pkg/cli/tag/tag.go
- pkg/cli/tag/tag_test.go
skip validation for deletion as existing tags might have been created with an invalid name and users must be able to delete them.
> OCPBUGS-25703: validate tag name on creation

- pkg/cli/admin/upgrade/rollback/rollback.go
- pkg/cli/admin/upgrade/rollback/rollback_test.go
- pkg/cli/admin/upgrade/upgrade.go
The "which release to roll back to?" criteria are matched to openshift/cluster-version-operator@12fdd0456b
(openshift/cluster-version-operator#996), where, based on [OTA-553](https://issues.redhat.com/browse/OTA-553), Lala, Scott, and Subin all agreed that rollbacks to the cluster's previous release should not be blocked, as long as the previous and current version had the same `major.minor` version (i.e. "within a z-stream", using `x.y.z` naming for `major.minor.patch`).  We agreed to ignore whether the previous history entry is `Completed` or `Partial`, expecting that most users who are interested in rolling back will make that decision at the first sign of trouble, and not after attempting a few roll-forward retargets.
I'm currently blocking `Progressing!=False` from rolling back, to …
> OTA-492: pkg/cli/admin/upgrade/rollback: New rollback command

- pkg/cli/admin/release/new.go
- pkg/cli/rsync/copy_tar.go
As getting warnings from snyk checks about some unsanitized input[1], to have a
green CI check, this PR sanitizes the path inputs.
[1] https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_oc/1644/pull-ci-openshift-oc-master-security/1737775363041267712
> NO-JIRA: Sanitize path using filepath Clean

- pkg/cli/admin/release/extract.go
We'll have 4.14 release notes about `--included`, but not everyone reads release notes.  This new logging attempts to get in front of folks using a 4.13-style workflow like [this][1], to help shift them towards a 4.14-style workflow (like openshift/openshift-docs#62148  is setting up)
[1]: https://docs.openshift.com/container-platform/4.13/authentication/managing_cloud_provider_credentials/cco-mode-sts.html#cco-ccoctl-creating-individually_cco-mode-sts
> OCPBUGS-19807: pkg/cli/admin/release/extract: Log a warning on --credentials-requests without --included

- images/cli-artifacts/Dockerfile.rhel
- pkg/cli/admin/release/extract_tools.go
As explained in the referenced bug, oc compiled in RHEL8 does not work
on FIPS enabled RHEL9 environment. However, we need to provide a way to
users to enable extraction of oc compiled in RHEL9 to work on FIPS enabled clusters.
This PR adds new command targets in `oc adm release extract` command that
users can extract oc specific to their RHEL versions as a continuation of 
https://github.com/openshift/oc/pull/1632
<details>
<summary>Single command extraction</summary>
```sh
$ ./oc adm release extract registry.ci.openshift.org/ocp/release:4.16.0-0.nightly-2024-01-03-193825 --to=/tmp/test_extract --command=oc.rhel9
$ ./oc adm release extract registry.ci.openshift.org/ocp/release:4.16.0-0.nightly-2024-01-03-193825 --to=/tmp/test_extract --command=oc.rhel8
$ ./oc adm release extract …
```
> OCPBUGS-25461: Add RHEL9 and RHEL8 based oc as new targets in command extraction

- hack/verify-kube-version.sh
- images/cli/Dockerfile.rhel
- pkg/cli/admin/release/new.go
This adds a kubectl version to the Dockerfile so that the release controller can better represent what level of kube is present in our payloads. As our mismatch times extend, this makes certain classes of failures obvious and ensure we don't have an accident shipping.
/assign @soltysh @ardaguclu  @wking
> NO-JIRA: report kubectl version to the release controller

- pkg/helpers/newapp/cmd/newapp.go
This is required to make the build test pass in https://github.com/openshift/openshift-apiserver/pull/400.
This was fixed a while ago as part of https://github.com/openshift/oc/pull/1272 in 4.12 onward.
> OCPBUGS-26599: release-4.11: use correct namespace with sample templates

- pkg/cli/admin/release/config.go
- pkg/cli/admin/release/info.go
4.14 to 4.16 show this
`oc adm release info registry.build05.ci.openshift.org/ci-op-sv0zdi1v/release:latest registry.ci.openshift.org/ocp/release:4.16.0-0.ci-2024-01-11-182726` produces
```
FeatureGate changes for "Default" (4 enabled, 14 disabled, 2 removed)
Enabled:
ExternalCloudProvider
ExternalCloudProviderGCP
KMSv1
OpenShiftPodSecurityAdmission
Disabled:
ClusterAPIInstall
DNSNameResolver
DisableKubeletCloudCredentialProviders
GCPClusterHostedDNS
InstallAlternateInfrastructureAWS
MachineConfigNodes
ManagedBootImages
MetricsServer
MixedCPUsAllocation
NetworkLiveMigration
OnClusterBuild
PinnedImages
SignatureStores
VSphereControlPlaneMachineSet
Removed:
AdmissionWebhookMatchConditions
RetroactiveDefaultStorageClass
FeatureGate changes for "TechPreviewNoUpgrade" (14 enabled, 2 disabled, …
```
> NO-ISSUE: add information about featuregate diff in a particular release

- pkg/cli/admin/inspect/inspect.go
- pkg/cli/admin/inspect/pod.go
this solution is not very robust, but rotated logs can considerably increase the size of the gathered logs, so we do our best to support filtering them as well.
---
I only managed to test this outside the context of a must-gather, since the must-gather will use the `oc` binary present in its image. Follow these steps to test it:
```
go run ./cmd/oc adm inspect --rotated-pod-logs --since-time=2024-01-10T10:00:00Z ns/openshift-cluster-version
ll inspect.local.4575015416930189447/namespaces/openshift-cluster-version/pods/cluster-version-operator-6d799d6cc6-zwbcb/cluster-version-operator/cluster-version-operator/logs/rotated
```
Here's an example from one of my runs on openshift local running with `--since-time=2024-01-10T10:00:00Z`
``` …
```
> WRKLDS-1010: pkg/cli/admin/inspect: use since/since-time for rotated logs

- pkg/cli/admin/mustgather/mustgather.go
- pkg/cli/admin/mustgather/mustgather_test.go
- creates a gather.log file under each image directory to capture the gather container logs in case the collection fails with an error.
Tested by running:
```
$ oc adm must-gather -- ls
```
> WRKLDS-1012: oc adm must-gather: pull gather container logs

- pkg/cli/admin/release/image_mapper.go
Currently, when we bump oc to newer k8s versions, our CI jobs are failing due to kubectl version mismatch error. The reason is that when we bump oc to newer kubectl(i.e. 1.29.0), cli and cli-artifact images manifest this version. On the other hand, other images in other operators have not-bumped kubectl version(i.e. 1.28.2).
This PR only populates kubectl versions in cli and cli-artifact images(because they are the source of truth) but in addition to that this PR checks the other images as well to have a consistency of a rule that all images should match either kubectl version in cli, cli-artifact or match with each other (all versions in other images at least should equal to 1.28.2).
<details>
<summary>valid image sets</summary>
```
cli 1.29.0
cli-artifact 1.29.0
others all 1.28.2
``` …
> NO-JIRA: Consider kubectl version checks only from cli and cli-artifact images

- pkg/cli/admin/release/image_mapper.go
- pkg/cli/admin/release/info.go
- pkg/cli/admin/release/info_test.go
With this PR https://github.com/openshift/oc/pull/1656, we relaxed the kubectl component version
check by only allowing kubectl version in cli and cli-artifacts images and kubectl version between 
other images. However, as seen in this revert https://github.com/openshift/oc/pull/1660, there are other oc commands
having this strict component version check which caused failures in HCP.
This PR adopts simpler approach for kubectl specific component version checking. It simply
populates all the kubectl versions in a set and if the length is greater than 2(actual kubectl version 1.29.0 and the current ones 1.28.2) which means that this is indeed kubectl version mismatch.
> NO-JIRA: Simplified kubectl component version check

- pkg/cli/admin/mustgather/mustgather.go
All openshift operators must include FallbackToLogsOnError to ease debugging.
> OCPBUGS-28230: add FallbackToLogsOnError for easier debugging

- pkg/cli/admin/inspect/inspect.go
Ideally this would be done in the `Validate` method, but `Complete` is invoked before `Validate`.
--
For reference, this is what the code on master return:
```
oc adm inspect --since-time=2024-01-25 ns/openshift-cluster-version
error: parsing time "2024-01-25" as "2006-01-02T15:04:05Z07:00": cannot parse "" as "T"
```
And this is what the new code in this PR return (it also matches the error for an invalid `--since-time` value from `oc adm must-gather`):
```
go run ./cmd/oc adm inspect --since-time=2024-01-25 ns/openshift-cluster-version
error: --since-time only accepts times matching RFC3339, eg '2006-01-02T15:04:05Z'
```
> NO-JIRA: pkg/cli/admin/inspect: format RFC3339 parse error

- pkg/cli/admin/copytonode/command.go
- pkg/cli/admin/pernodepod/command.go
Before:
```
--parallelism='10%!'(MISSING):
parallelism is a raw number or a percentage of the nodes to work with concurrently.
```
After with a percent:
```
--parallelism='10%':
parallelism is a raw number or a percentage of the nodes to work with concurrently.
```
or with a default digit:
```
--parallelism='1':
parallelism is a raw number or a percentage of the nodes to work with concurrently.
```
/assign @ardaguclu
> NO-JIRA: Fix --parallelism flag formatting in help

- pkg/cli/admin/inspect/pod.go
Looks like previous logs were missed when the `--since` and `--since-time` flags were first introduced on `oc adm inspect`.
> OCPBUGS-27957: pkg/cli/admin/inspect: use since/since-time for previous container logs

- images/cli-artifacts/Dockerfile.rhel
With this https://github.com/openshift/oc/pull/1647, we started allowing extraction of `oc.rhel8`.
However, it seems that symlinked binaries(i.e. `oc.rhel8`) are simply ignored during file path
traversal in tarballs. That results in the error message `oc.rhel8` is not found being raised. 
To solve the problem, in this PR we are now copying oc.rhel8 binaries from already compiled oc instead of
symlinking.
> OCPBUGS-28540: Copy oc.rhel8 instead of symlink

- pkg/cli/admin/copytonode/command.go
- pkg/cli/admin/pernodepod/command.go
This reverts commit d6762a7cc46eadcb29a420316373b11fae90b6d5.
/assign @ardaguclu
> OCPBUGS-29039: fix copy-to-node 

- images/cli-artifacts/Dockerfile.rhel
- pkg/cli/admin/release/extract_tools.go
This PR is manual backport of a group of PRs to enable the extraction of rhel9 and rhel8 based oc binaries.
* https://github.com/openshift/oc/pull/1632
* https://github.com/openshift/oc/pull/1647
* https://github.com/openshift/oc/pull/1669
This PR also covers https://github.com/openshift/oc/pull/1665
These PRs are prerequisite of this PR;
* https://github.com/openshift-eng/ocp-build-data/pull/4303
* https://github.com/openshift/oc/pull/1669
> [release-4.15] OCPBUGS-28204: Add RHEL9 and RHEL8 based oc as new targets in command extraction

- images/tools/Dockerfile
Something has recently changed with the parent images of the tools image where it no longer has python causing CI failures. Adding `python3` to the tools image.
> TRT-1503: Tools image no longer has python;adding

- pkg/cli/admin/release/image_mapper.go
- pkg/cli/admin/release/image_mapper_test.go
- pkg/cli/admin/release/info.go
- pkg/cli/admin/release/info_test.go
- pkg/cli/admin/release/new.go
There are images that are based on `cli` image in the release payload and those images also manifest their kubectl versions (i.e. [cluster-samples-operator](https://github.com/openshift/cluster-samples-operator/blob/master/manifests/image-references) [1]). It is reasonable to assume that all the kubectl versions should match, because base image is the same for all of them. However, rebuilt strategy of some images simply rely on a new commit in their repository. That means if there is no new commit merged for a repository that the image is residing in, this image will not be rebuilt and still manifests an old kubectl version. That causes a new release payload generation mechanism a failure (even a minor kubectl version bump in oc would cause a org-wide failures).
Due to this uncontrolled …
> NO-JIRA: Print log rather than returning an error when kubectl version mistmaches

- OWNERS_ALIASES
- pkg/cli/admin/admin.go
- pkg/cli/admin/inspectalerts/OWNERS
- pkg/cli/admin/inspectalerts/inspectalerts.go
The new subcommand is gated by `OC_ENABLE_CMD_INSPECT_ALERTS` to avoid customers accidentally using it while it's tech-preview:
```console
$ OC_ENABLE_CMD_INSPECT_ALERTS=true oc adm inspect-alerts | jq -r '[.[] | .startsAt + " " + .endsAt + " " + .status.state + " " + (.labels | .severity + " " + .alertname) + " " + .annotations.summary] | sort[]'
2024-01-19T20:13:28.083Z 2024-01-31T05:23:28.083Z suppressed none Watchdog An alert that should always be firing to certify that Alertmanager is working properly.
2024-01-19T20:14:13.174Z 2024-01-31T05:24:13.174Z suppressed info ClusterNotUpgradeable One or more cluster operators have been blocking minor version cluster upgrades for at least an hour.
2024-01-19T20:14:20.600Z 2024-01-31T05:24:20.600Z suppressed warning TechPreviewNoUpgrade …
```
> OTA-1080: pkg/cli/admin/inspectalerts: New tech-preview inspect-alerts subcommand

- pkg/cli/login/login.go
- pkg/cli/login/loginoptions.go
Normally, oc login extracts the issuer url from API server but in cases where multiple oidc providers exist, user may want to explicitly specify issuer url to authenticate. That's why, this PR introduces `--issuer-url` flag in oc login to be passed to `oc get-token` oidc cred exec plugin of oc.
> OCPBUGS-30162: Introduce --issuer-url flag in oc login

- pkg/cli/image/extract/extract.go
- pkg/cli/image/imagesource/file.go
- pkg/cli/image/imagesource/file_unix.go
- pkg/cli/image/imagesource/file_windows.go
Image label (`operators.operatorframework.io.index.configs.v1`), mappings and other code parts uses Unix path separators (`/`). `github.com/docker/docker/pkg/archive` implementation produces windows path separators when running on Windows platform. ToSlash and FromSlash allows to treat all path seperators as Unix path seperators.
> OCPBUGS-30212: oc adm catalog mirror: use ToSlash and FromSlash to unify the path separators

- images/tools/Dockerfile
In the disconnected env it's really hard to add a new image or rpms. Thus, making the sosreport part of the tools image removes the need for pulling another image/installing an rpm.
> WRKLDS-1103: tools: extend the image with sosreport

- pkg/cli/admin/release/extract.go
- pkg/cli/admin/release/git.go
- pkg/cli/admin/release/info.go
This PR adds the `--filter=blob:none --bare` flags to the `git clone` commands, which significantly reduces disk space usage (for example, for 4.14.0->4.15.0, reduction from 31GB to 900MB).
> WRKLDS-1128: cli/admin/release/git: use optimized git flags

- pkg/helpers/newapp/newapptest/newapp_test.go
We invested a good amount of effort to maintain the unit tests for `oc newapp` (aka `TestNewApp*`) by migrating to the equivalents that are alive, when the images they use were removed. However, after all the images have been removed from `quay.io/centos7` (e.g. `quay.io/centos7/ruby-27-centos7`, `quay.io/centos7/redis-5-centos7`), it seems that there is nowhere we can go.
Creating new images and maintaining them separately just for these tests would be an option but it doesn't seems to be the reasonable one. That's why, this PR removes the tests depending on these images. Because we don't/won't make changes to this command (`oc newapp`).
> OCPBUGS-31484: Remove some of newapp unit tests relying on external deprecated images

- pkg/cli/admin/release/extract.go
- pkg/cli/admin/release/git.go
- pkg/cli/admin/release/info.go
As we discussed in https://github.com/openshift/oc/pull/1715#issuecomment-2025145649, we will reintroduce this feature when oc's base image is set to RHEL9.
Reverts openshift/oc#1708
> WRKLDS-1128: revert cli/admin/release/git: use optimized git flags

- pkg/cli/image/info/info.go
`--filter-by-os` flag is ignored (even with invalid value `--filter-by-os=invalid`), when it is used against an single image. This PR adds this into the long text.
> OCPBUGS-31615: Add help text the behavior of filter-by-os against single image

- pkg/cli/admin/release/extract_tools.go
Allow the openshift-baremetal-install binary to also be extracted using the openshift-install-fips command. This is clearer for users who need this binary only for FIPS compliance reasons.
> WRKLDS-1171: Add openshift-install-fips target to oc release extract

- pkg/cli/login/login.go
- pkg/cli/login/loginoptions.go
In oc login, `certificate-authority` global flag provided by oc is used to authenticate to API server, when API Server's
CA bundle is self-signed. We tried to use it against external OIDC issuers as well but it is not correct behavior because external OIDC issuer's CA bundle may differ from API server.
This PR introduces a new `oidc-certificate-authority` flag which will be used to pass to external OIDC issuer during authentication. This separation enables two different CA bundles can be used at the same invocation and global `certificate-authority` flag is still used against API server.
> OCPBUGS-31498: Add OIDC specific certificate authority bundle flag

- pkg/cli/admin/upgrade/status/examples/4.14.1-degraded.output
- pkg/cli/admin/upgrade/status/examples/4.14.1-paused-worker-pool.output
- pkg/cli/admin/upgrade/status/examples/4.14.1-workers-started-updating-multiple-pools.output
- pkg/cli/admin/upgrade/status/examples/4.15.0-ec2-b02-cos-not-annotated.output
- pkg/cli/admin/upgrade/status/examples/4.15.0-ec2-early.output
- pkg/cli/admin/upgrade/status/examples/4.15.0-ec2-unavailable-mco-20m.output
- pkg/cli/admin/upgrade/status/examples/4.16.0-ec2-control-plane-updated-pdb-prohibits-draining.output
- pkg/cli/admin/upgrade/status/status.go
- pkg/cli/admin/upgrade/status/workerpool.go
The goal of this pull request is to display additional information upon executing `oc adm upgrade status`.
The additional information consists of the status of control plane nodes.
This pull request references https://issues.redhat.com/browse/OTA-1036
> OTA-1036: `adm upgrade status`: Add control plane nodes status

- pkg/cli/admin/prune/prune.go
- pkg/cli/admin/prune/renderedmachineconfigs/OWNERS
- pkg/cli/admin/prune/renderedmachineconfigs/renderedmachineconfigs.go
This PR adds a new option in the `oc adm prune` family to remove unused rendered machine configs. It comprises of two subcommands:
**Delete unused rendered MCs**
This is the main command and it would take in the following arguments:
- Pool name, which indicates the owner of the rendered MCs to target. This argument is not required.If not set, all pools will be evaluated.
- Count, which describes a max number of rendered MCs to delete, oldest first. This argument is not required.
- Confirm flag, which will cause the prune to take place. If not set, the command will be run in dry run mode. This argument is not required.
```
$ oc adm prune renderedmachineconfigs --pool-name=worker
$ oc adm prune renderedmachineconfigs --count=10  --pool-name=worker
$ oc adm prune renderedmachineconfigs …
```
> MCO-1056: MCO-1057: Implement oc adm prune machineconfigs command

- pkg/cli/admin/upgrade/status/examples/4.14.1-degraded.detailed-output
- pkg/cli/admin/upgrade/status/examples/4.14.1-paused-worker-pool.detailed-output
- pkg/cli/admin/upgrade/status/examples/4.14.1-workers-started-updating-multiple-pools.detailed-output
- pkg/cli/admin/upgrade/status/examples/4.15.0-ec2-b02-cos-not-annotated.detailed-output
- pkg/cli/admin/upgrade/status/examples/4.15.0-ec2-early.detailed-output
- pkg/cli/admin/upgrade/status/examples/4.15.0-ec2-unavailable-mco-20m.detailed-output
- pkg/cli/admin/upgrade/status/examples/4.16.0-ec2-control-plane-updated-pdb-prohibits-draining.detailed-output
- pkg/cli/admin/upgrade/status/examples/4.16.0-ec2-control-plane-updated-pdb-prohibits-draining.output
- pkg/cli/admin/upgrade/status/examples/README.md
- pkg/cli/admin/upgrade/status/examples/not-upgrading.detailed-output
- pkg/cli/admin/upgrade/status/examples_test.go
- pkg/cli/admin/upgrade/status/status.go
- pkg/cli/admin/upgrade/status/workerpool.go
Deviate from the mockup and make `--detailed` accept an enum value instead of being a boolean. This allows expanding different sections which can be useful in different scenarios.
For now, allow the following values:
- `none`: non-detailed output, default
- `nodes`: nodes sections are not capped to 10 nodes
- `health`: health insights provide further details (not implemented yet)
- `all`: all sections capable to emit detailed output do so
Also, test `--detailed=all` in the examples test.
> OTA-1174: `upgrade status`: add `--detailed=nodes` that shows all nodes

- pkg/cli/image/extract/extract.go
`$ oc image extract 'quay.io/multi-arch/yq:3.3.0' --file '/yq' --filter-by-os 'darwin/amd64'` panics: 
```bash
panic: no ':' separator in digest ""
goroutine 14 [running]:
github.com/opencontainers/go-digest.Digest.sepIndex({0x0, 0x0})
/Users/fxie/Projects/oc/vendor/github.com/opencontainers/go-digest/digest.go:153 +0x90
github.com/opencontainers/go-digest.Digest.Algorithm(...)
/Users/fxie/Projects/oc/vendor/github.com/opencontainers/go-digest/digest.go:122
github.com/openshift/oc/pkg/cli/image/extract.(*ExtractOptions).Run.func1.1()
/Users/fxie/Projects/oc/pkg/cli/image/extract/extract.go:413 +0x4e0
github.com/openshift/oc/pkg/cli/image/workqueue.(*worker).Try.func1()
/Users/fxie/Projects/oc/pkg/cli/image/workqueue/workqueue.go:137 +0x30 …
```
> NO-JIRA: Print an error msg instead of panicking when all image manifests are filtered out

- images/recycler/Dockerfile.rhel
- images/tools/Dockerfile
> OCPBUGS-20097: Migrate tools image to RHEL9

- pkg/cli/admin/release/extract_tools.go
This change adds ccoctl.rhel8 and ccoctl.rhel9 as targets for extract tools.
Depends on: https://github.com/openshift/cloud-credential-operator/pull/692
> OCPBUGS-32080: release: extract ccoctl.rhel8 and ccoctl.rhel9

- pkg/cli/admin/upgrade/status/examples/README.md
- pkg/cli/admin/upgrade/status/status.go
Previous commits used `--details` and `--detailed` inconsistently, lets unify on `--details` everywhere.
> OTA-1174: `update status`: unify on `--details`

- pkg/cli/admin/upgrade/status/controlplane.go
- pkg/cli/admin/upgrade/status/controlplane_test.go
- pkg/cli/admin/upgrade/status/examples/4.14.1-degraded.detailed-output
- pkg/cli/admin/upgrade/status/examples/4.14.1-degraded.output
- pkg/cli/admin/upgrade/status/examples/4.16.0-ec2-control-plane-updated-pdb-prohibits-draining.detailed-output
- pkg/cli/admin/upgrade/status/examples/4.16.0-ec2-control-plane-updated-pdb-prohibits-draining.output
- pkg/cli/admin/upgrade/status/status.go
Structure this output, so it gets all the usual pretty-printing, detail, etc. that the sad-ClusterOperator conditions are getting. Sometimes `Failing` will complain about sad ClusterOperators, and in that case we'll double up on that messaging.  But we're punting on "consolidate when multiple `updateInsights` complain about the same root cause" for now.  And sometimes `Failing` will complain about other resources, such as [`ProgressDeadlineExceeded` operator Deployments][1], and in that case the information is only flowing out through ClusterVersion, and not via the other resources we check when rendering status.
[1]: https://github.com/openshift/cluster-version-operator/blob/1acac06742fb0e3e49ffe2294864007f26a7799d/lib/resourcebuilder/apps.go#L122C124-L122C148
> OTA-1279: pkg/cli/admin/upgrade/status: Move Failing from free-form to updateInsight

- pkg/cli/admin/upgrade/status/examples/4.14.1-degraded.detailed-output
- pkg/cli/admin/upgrade/status/examples/4.14.1-degraded.output
- pkg/cli/admin/upgrade/status/examples/4.14.1-paused-worker-pool.detailed-output
- pkg/cli/admin/upgrade/status/examples/4.14.1-paused-worker-pool.output
- pkg/cli/admin/upgrade/status/examples/4.14.1-workers-started-updating-multiple-pools.detailed-output
- pkg/cli/admin/upgrade/status/examples/4.14.1-workers-started-updating-multiple-pools.output
- pkg/cli/admin/upgrade/status/examples/4.15.0-ec2-b02-cos-not-annotated.detailed-output
- pkg/cli/admin/upgrade/status/examples/4.15.0-ec2-b02-cos-not-annotated.output
- pkg/cli/admin/upgrade/status/examples/4.15.0-ec2-early.detailed-output
- pkg/cli/admin/upgrade/status/examples/4.15.0-ec2-early.output
- pkg/cli/admin/upgrade/status/examples/4.15.0-ec2-unavailable-mco-20m.detailed-output
- pkg/cli/admin/upgrade/status/examples/4.15.0-ec2-unavailable-mco-20m.output
- pkg/cli/admin/upgrade/status/examples/4.16.0-ec2-control-plane-updated-pdb-prohibits-draining.detailed-output
- pkg/cli/admin/upgrade/status/examples/4.16.0-ec2-control-plane-updated-pdb-prohibits-draining.output
- pkg/cli/admin/upgrade/status/status.go
Following up on 7977ec94ea (#1744), drop the remaining free-form output.  With this change, all happy-case stdout output should be via structured `updateInsight`.  The `Update Health` section at the end of the output is now the only cluster-scoped summary of overall update progress.  Generated the updated fixtures with:
```console
$ export OC_ENABLE_CMD_UPGRADE_STATUS=true
$ for X in pkg/cli/admin/upgrade/status/examples/*-cv.yaml; do ./oc adm upgrade status --mock-clusterversion "${X}" > "${X/-cv.yaml/.output}"; ./oc adm upgrade status --details=all --mock-clusterversion "${X}" > "${X/-cv.yaml/.detailed-output}"; done
```
> OTA-1154: pkg/cli/admin/upgrade/status: Drop free-form Progressing output line

- .ci-operator.yaml
- images/cli-artifacts/Dockerfile.rhel
- images/cli/Dockerfile.rhel
- pkg/cli/debug/debug.go
This PR bumps the base image of cli image to RHEL9. This is the last remaining piece after the bump of tools image in https://github.com/openshift/oc/pull/1652.
> WRKLDS-1251: Switch cli image to RHEL9 base image

- pkg/cli/admin/release/extract.go
- pkg/cli/admin/release/git.go
- pkg/cli/admin/release/info.go
This commit adds back the code changes from #1708 now that the `tools` image is based on RHEL 9 and can properly run git with these flags.
> OTA-1275: cli/admin/release/git: use optimized git flags

- pkg/cli/admin/migrate/icsp/icsp.go
- pkg/cli/admin/migrate/icsp/icsp_test.go
`oc adm migrate icsp` parses the icsp file using the separator to get all the icsp manifests and convert to single idms file.
> OCPNODE-2281: Support multiple icsps in migrate icsp

- pkg/cli/admin/upgrade/status/examples/4.16.0-ec2-control-plane-updated-pdb-prohibits-draining-node.yaml
- pkg/cli/admin/upgrade/status/examples/4.16.0-ec2-control-plane-updated-pdb-prohibits-draining.detailed-output
- pkg/cli/admin/upgrade/status/examples/4.16.0-ec2-control-plane-updated-pdb-prohibits-draining.output
- pkg/cli/admin/upgrade/status/status.go
- pkg/cli/admin/upgrade/status/workerpool.go
- pkg/cli/admin/upgrade/status/workerpool_test.go
The main goal of this pull request is to fix an occurring error that resulted in the error
message: `error: resource name may not be empty`
This was caused by not checking the value of the
machineconfiguration.openshift.io/currentConfig and
machineconfiguration.openshift.io/desiredConfig annotations of nodes.
In the event, the annotation was not set or was empty, the command would
try to get a MachineConfig with an empty name from the API server.
The commit also adds additional functionalities and testing for cases
when different MCD annotations are missing.
The general strategy is to declare the states of nodes only when they
are provably in the specific states.
This pull request references https://issues.redhat.com//browse/OCPBUGS-32682
> OCPBUGS-32682: Fix the retrieval of API objects with an empty name

- pkg/cli/admin/upgrade/status/controlplane.go
- pkg/cli/admin/upgrade/status/controlplane_test.go
- pkg/cli/admin/upgrade/status/examples/4.14.1-degraded.detailed-output
- pkg/cli/admin/upgrade/status/examples/4.14.1-degraded.output
- pkg/cli/admin/upgrade/status/examples/4.14.1-paused-worker-pool.detailed-output
- pkg/cli/admin/upgrade/status/examples/4.14.1-paused-worker-pool.output
- pkg/cli/admin/upgrade/status/examples/4.14.1-workers-started-updating-multiple-pools.detailed-output
- pkg/cli/admin/upgrade/status/examples/4.14.1-workers-started-updating-multiple-pools.output
- pkg/cli/admin/upgrade/status/examples/4.15.0-ec2-b02-cos-not-annotated.detailed-output
- pkg/cli/admin/upgrade/status/examples/4.15.0-ec2-b02-cos-not-annotated.output
- pkg/cli/admin/upgrade/status/examples/4.15.0-ec2-early-cv.yaml
- pkg/cli/admin/upgrade/status/examples/4.15.0-ec2-early.detailed-output
- pkg/cli/admin/upgrade/status/examples/4.15.0-ec2-early.output
- pkg/cli/admin/upgrade/status/examples/4.15.0-ec2-unavailable-mco-20m.detailed-output
- pkg/cli/admin/upgrade/status/examples/4.15.0-ec2-unavailable-mco-20m.output
- pkg/cli/admin/upgrade/status/examples/4.16.0-ec2-control-plane-updated-pdb-prohibits-draining.detailed-output
- pkg/cli/admin/upgrade/status/examples/4.16.0-ec2-control-plane-updated-pdb-prohibits-draining.output
This pull request will show additional information regarding the upgrade.
A new line in the control plane section shows information regarding the upgrade target version and the previous version.
For example:
```text
= Control Plane =
Assessment:      Progressing
Target Version:  4.14.1 (from 4.14.0)
Completion:      97%
Duration:        14m4s
Operator Status: 32 Healthy, 1 Unavailable
```
In the event that the previous update was an incomplete update (a partial update) and the control plane is currently updating, a new insight is generated, as this fact may influence the upgrade.
This pull request references https://issues.redhat.com/browse/OTA-1156
> OCPBUGS-33898: `adm update status`: Show information about the upgrade target version

- pkg/cli/admin/upgrade/status/alerts.go
- pkg/cli/admin/upgrade/status/alerts_test.go
- pkg/cli/admin/upgrade/status/examples/4.15.0-ec2-unavailable-mco-20m-alerts.json
- pkg/cli/admin/upgrade/status/examples/4.15.0-ec2-unavailable-mco-20m.detailed-output
- pkg/cli/admin/upgrade/status/examples/4.15.0-ec2-unavailable-mco-20m.output
- pkg/cli/admin/upgrade/status/health.go
- pkg/cli/admin/upgrade/status/mockresources.go
- pkg/cli/admin/upgrade/status/status.go
adds alerts that fire during the upgrade to
`upgrade health` section.
by default all the alerts that started firing after initiating the
upgrade will appear in the upgrade health section
we also have allowed alerts that will show alerts that started 
firing before the upgrade was started.
> OCPBUGS-33896: add alert data to upgrade health in oc adm upgrade status

- images/cli-artifacts/Dockerfile.rhel
- pkg/cli/admin/release/extract_tools.go
Default oc compiled on s390x is only working on RHEL9 (after we have changed the base image to RHEL9). Therefore, users still on s390x RHEL8 are getting failures. 
This PR adds s390x based oc (both oc.rhel8 and oc.rhel9) into the extraction list. So that, users can explicitly use s390x based oc.rhel8.
> OCPBUGS-33651: Add s390x based oc into extraction target

- pkg/cli/admin/upgrade/rollback/rollback.go
- pkg/cli/admin/upgrade/upgrade.go
In case the hidden-ness from 73074c32ba (#1642) is not sufficient to scare users away, add a gating environment variable.  We also use a gating env. var. for `status` (701c2eee92, #1554) and `inspect-alerts` (229c2a8460, #1674).
Also reword the LongDesc to avoid saying "supported" (which readers might misconstrue as "what Red Hat support will do if we open a case").  I'm just trying to talk about "what the cluster-version operator will do if you request a rollback", and hopefully the new wording makes this more clear.
> OCPBUGS-33905: pkg/cli/admin/upgrade/rollback: Gate on OC_ENABLE_CMD_UPGRADE_ROLLBACK

- pkg/cli/admin/inspectalerts/inspectalerts.go
We have seen instances where Thanos responses contained html, apparently by because it is briefly down. We can be slightly more robust to that by detecting non-OK status code right away, instead of passing content body out:
```
Ignoring alerts in 'Update Health'. Error unmarshaling alerts: %w invalid character '<' looking for beginning of value
```
Also improve debugging by allowing to emit http call details and response body on higher verbosity settings, consistent with `client-go` calls to apiserver.
Additionally, improve the error handling by refactoring the `getWithBearer`  method, Previously, it iterated over URIs from a route but instead of searching for success it actually searched until first failure, which is against the point of iterating over possible URIs in the first place. …
> OCPBUGS-33896: `status/inspect-alerts`: handle non-200 by Thanos

- pkg/cli/create/build.go
- pkg/cli/create/clusterquota.go
- pkg/cli/create/create.go
- pkg/cli/create/deploymentconfig.go
- pkg/cli/create/identity.go
- pkg/cli/create/imagestream.go
- pkg/cli/create/imagestreamtag.go
- pkg/cli/create/route.go
- pkg/cli/create/routeedge.go
- pkg/cli/create/routepassthrough.go
- pkg/cli/create/routereenecrypt.go
- pkg/cli/create/scheme.go
- pkg/cli/create/user.go
- pkg/cli/create/user_identity_mapping.go
- pkg/cli/expose/expose.go
- pkg/cli/expose/scheme.go
- pkg/helpers/scheme/scheme.go
for some reason, when loading ungroupified legacy schemes `oc set env` overrides `apiVersion` values of openshift objects, removing the api group, which makes them invalid in recent versions of openshift.
* remove global loading of legacy schemes
* create custom schemes for create and expose commands
* override upstream expose print flag type setter to use the custom expose scheme
* regression tests for `oc`
* ensure that `oc set env` no longer overrides the `apiVersion` of routes and deployment configs
* ensure we don't regress https://issues.redhat.com/browse/OCPBUGS-15772; in other words, make sure `oc set route-backends` and `oc edit route` work in microshift
* ?
> OCPBUGS-32108: stop loading legacy schemes on global scheme 

- pkg/cli/admin/upgrade/status/alerts.go
- pkg/cli/admin/upgrade/status/alerts_test.go
- pkg/cli/admin/upgrade/status/examples/4.14.1-degraded.detailed-output
- pkg/cli/admin/upgrade/status/examples/4.14.1-degraded.output
- pkg/cli/admin/upgrade/status/examples/4.15.0-ec2-unavailable-mco-20m-alerts.json
- pkg/cli/admin/upgrade/status/examples/4.15.0-ec2-unavailable-mco-20m.detailed-output
- pkg/cli/admin/upgrade/status/examples/4.15.0-ec2-unavailable-mco-20m.output
- pkg/cli/admin/upgrade/status/examples/4.16.0-ec2-control-plane-updated-pdb-prohibits-draining.detailed-output
- pkg/cli/admin/upgrade/status/examples/4.16.0-ec2-control-plane-updated-pdb-prohibits-draining.output
- pkg/cli/admin/upgrade/status/health.go
- pkg/cli/admin/upgrade/status/health_test.go
- skip alerts without required labels
- add context on why we show the insight (started firing during update or is known to affect updates)
- skip alerts with info level
- explicitly mention the alert does not have a runbook
> OCPBUGS-33896: `upgrade status`: polish alert insights

- pkg/cli/image/archive/archive.go
A previous commit refactored OpenFileSequential since it was deprecated, and replaced it with OpenFile.
https://github.com/openshift/oc/commit/7a8c458fbbf06a1c8411e4199d61e6d43bf67334
This commit just updates the comment to be accurate, since I stumbled on it walking through the code.
> NO-JIRA: Update comment about using OpenFileSequential

- pkg/cli/admin/inspectalerts/inspectalerts.go
- pkg/cli/admin/upgrade/status/alerts.go
- pkg/cli/admin/upgrade/status/alerts_test.go
- pkg/cli/admin/upgrade/status/examples/4.14.1-degraded.detailed-output
- pkg/cli/admin/upgrade/status/examples/4.14.1-degraded.output
- pkg/cli/admin/upgrade/status/examples/4.15.0-ec2-unavailable-mco-20m-alerts.json
- pkg/cli/admin/upgrade/status/examples/4.15.0-ec2-unavailable-mco-20m.detailed-output
- pkg/cli/admin/upgrade/status/examples/4.15.0-ec2-unavailable-mco-20m.output
- pkg/cli/admin/upgrade/status/examples/4.16.0-ec2-control-plane-updated-pdb-prohibits-draining.detailed-output
- pkg/cli/admin/upgrade/status/examples/4.16.0-ec2-control-plane-updated-pdb-prohibits-draining.output
- pkg/cli/admin/upgrade/status/health.go
- pkg/cli/admin/upgrade/status/health_test.go
- pkg/cli/admin/upgrade/status/mockresources.go
- pkg/cli/admin/upgrade/status/status.go
Replaces automated #1771 because multiple PRs were needed for OCPBUGS-33896.
Backports #1771 #1782 and #1787 to release 4.16:
- **add alerts to update health in oc adm upgrade status**
- **add mock tests for alerts in oc adm upgrade status**
- **OCPBUGS-33896: `status/inspect-alerts`: handle non-200 by Thanos**
- **inspectalerts: use client-go wrappers for thanos call debugging**
- **inspectalerts: refactor `getWithBearer` to try all urls in route**
- **`upgrade status`: polish alert insights**
> [release-4.16] OCPBUGS-33917: add alert data to upgrade health in oc adm upgrade status 

- pkg/cli/admin/mustgather/mustgather.go
instead, set the cluster role binding owner reference to the temporary
must-gather namespace. when the namespace is deleted, kubernetes handles
the deletion of the cluster role binding for us.
in cases where must-gather runs ends in failure, this change ensures
that once users manually delete the namespace, the cluster role binding
is also deleted.
> OCPBUGS-31848: don't manually delete must-gather's cluster role binding

- pkg/cli/debug/debug.go
[OCPBUGS-36328](https://issues.redhat.com/browse/OCPBUGS-36328)
Manual cherry-pick of #1763
> OCPBUGS-36328: Set required-scc annotation to privileged for node debug pods

- pkg/cli/admin/release/extract_tools.go
In parallel with: https://github.com/openshift/installer/pull/8515
This is necessary so the installer knows if it is using a single arch payload vs a multi arch payload. 
ATM customers can't recognize the difference without having to query the container registry. 
This is also the first step to enable deploying clusters with ARM control planes and x86 compute nodes (and vice versa)
https://issues.redhat.com/browse/MULTIARCH-4567
> : MULTIARCH-4568: Inject ReleaseArch into openshift-install

- pkg/cli/debug/debug.go
[OCPBUGS-36329](https://issues.redhat.com/browse/OCPBUGS-36329)
Cherry-pick of #1763
> [release-4.15] OCPBUGS-36329: Set required-scc annotation to privileged for node debug pods

- pkg/cli/admin/upgrade/rollback/rollback.go
- pkg/cli/admin/upgrade/rollback/rollback_test.go
- pkg/cli/admin/upgrade/upgrade.go
Reverts #1806, now that folks are saying they want this `rollback` subcommand restored.
> OCPBUGS-37345: Revert "OCPBUGS-35994: pkg/cli/admin/upgrade/rollback: Drop this command"

- pkg/cli/admin/copytonode/command.go
- pkg/cli/admin/node/logs.go
- pkg/cli/admin/nodeimage/create.go
- pkg/cli/admin/ocpcertificates/certregen/command.go
- pkg/cli/admin/ocpcertificates/monitorregeneration/command.go
- pkg/cli/admin/rebootmachineconfigpool/command.go
- pkg/cli/admin/restartkubelet/command.go
- pkg/cli/admin/waitforstable/command.go
- pkg/cli/config/adminkubeconfig/new_admin_kubeconfig.go
- pkg/cli/config/kubeletbootstrapkubeconfig/new_kubelet_bootstrap_kubeconfig.go
- pkg/cli/config/refreshcabundle/refresh_ca_bundle.go
- pkg/cli/debug/debug.go
- pkg/cli/gettoken/gettoken.go
- pkg/cli/image/mirror/mirror.go
- pkg/cli/login/login.go
- pkg/cli/version/version.go
Minor updates to the CLI text for grammar and consistency (since this is pulled into product docs as the CLI reference docs).
For example, short names and example comments should have no ending punctuation, but long descriptions should.
> NO-JIRA: Minor wording tweaks for CLI help

- pkg/cli/admin/nodeimage/create.go
This patch is required by https://github.com/openshift/installer/pull/8740 to retrieve the `infrastructures.config.openshift.io/cluster` [resource](https://github.com/openshift/installer/pull/8740/files#diff-b6c0ec51beec87580161335112657421a6874afa61790f8300295cbae1a90c96R377) for validating the supported platform types in node-joiner
> AGENT-854: add the required role to support platform type validation

- pkg/cli/admin/nodeimage/create.go
clusterversions is already part of the config.openshift.io API group. It does not belong in the certificates.k8s.io API group.
> WRKLDS-1316: Remove clusterversions from certificates api group

- pkg/cli/admin/upgrade/status/mco/layered_pool_state.go
From the comment above and the code below (using annotations), it feels like it should be `annotations` instead of `labels`.
/cc @Davoska @petr-muller
> NO-JIRA: upgrade-status: fix HasOSImage function

- pkg/cli/admin/nodeimage/create.go
This patch introduces a new set of flags to simplify simpler scenarios based on adding a single node. Instead of defining a complete yaml file (which could be more suitable and handy when handling multiples nodes), the user now can define a number of command line flags to finely configure the required parts of the single node to be added.
When single node flags will be used:
* The only mandatory flag is `mac-address`, to identify the host to be added. All the others will be optional
* The configuration file, if present in the working dir, will be ignored
> [WIP] WRKLDS-1318: flags for single node interface

- pkg/cli/admin/upgrade/status/examples/4.16.0-ec2-control-plane-updated-pdb-prohibits-draining.detailed-output
- pkg/cli/admin/upgrade/status/examples/4.16.0-ec2-control-plane-updated-pdb-prohibits-draining.output
- pkg/cli/admin/upgrade/status/mco/layered_node_state.go
- pkg/cli/admin/upgrade/status/workerpool.go
- pkg/cli/admin/upgrade/status/workerpool_test.go
This is a workaournd before https://issues.redhat.com/browse/MCO-1256 is implemented.
> OTA-1292: upgrade-status: bubble up the reason for unavailable nodes

- pkg/cli/admin/upgrade/status/examples/4.16.0-ec2-control-plane-updated-pdb-prohibits-draining-node.yaml
- pkg/cli/admin/upgrade/status/examples/4.16.0-ec2-control-plane-updated-pdb-prohibits-draining.detailed-output
- pkg/cli/admin/upgrade/status/examples/4.16.0-ec2-control-plane-updated-pdb-prohibits-draining.output
We discovered our existing test was triggering "weird" paths in the assessment code, because the input node was missing a MCO annotation while the node was ready (and it was missing only one annotation). While this is a possible scenario, it would likely need to be created manually by someone messing with annotations or the like. It did not represent the common scenario otherwise.
The typical scenario for missing annotations is a freshly provisioned node, before MCO has a chance to reconcile it. Such node is typically also not ready yet.
> NO-JIRA: `upgrade status`: improve tests for missing annotations

- pkg/cli/admin/upgrade/status/mco/layered_node_state.go
https://issues.redhat.com/browse/OTA-1292
Addressing the 3rd case from https://github.com/openshift/oc/pull/1838#pullrequestreview-2238631410
/cc @petr-muller @Davoska
> OTA-1292: upgrade-status: handle the OS image annotation better

- pkg/cli/idle/idle.go
Check https://search.dptools.openshift.org/?search=unable+to+scale+.*+but+still+listed+as+target+for+unidling%3A+Operation+cannot+be+fulfilled+on+.*%3A+the+object+has+been+modified%3B+please+apply+your+changes+to+the+latest+version+and+try+again&maxAge=48h&context=1&type=junit&name=4.18&excludeName=multi&maxMatches=5&maxBytes=20971520&groupBy=job 
and
https://sippy.dptools.openshift.org/sippy-ng/tests/4.18/analysis?test=%5Bsig-network-edge%5D%5BFeature%3AIdling%5D%20Unidling%20with%20Deployments%20%5Bapigroup%3Aroute.openshift.io%5D%20should%20work%20with%20TCP%20(when%20fully%20idled)%20%5BSuite%3Aopenshift%2Fconformance%2Fparallel%5D&filters=%7B%22items%22%3A%5B%7B%22columnField%22%3A%22name%22%2C%22operatorValue%22%3A%22equals%22%2C%22value%22%3A%22%5Bsig-network-edge%5D%5BFeature%3AIdl …
> make the idle command's scale update unconditional

- pkg/cli/admin/upgrade/upgrade.go
Making it more clear which release would be selected.
> OCPBUGS-30658: pkg/cli/admin/upgrade: --to-latest help "next" -> "latest"

- pkg/cli/image/mirror/mappings.go
Code actually has an ability to handle different tags with same layers. However, it is forgotten to update the tag list with the new list. This PR fixes this.
> OCPBUGS-39375: Update push targets of digest with new appended tags

- pkg/cli/admin/upgrade/recommend/recommend.go
- pkg/cli/admin/upgrade/recommend/recommend_test.go
- pkg/cli/admin/upgrade/upgrade.go
This PR will add the backbones for the new `oc adm upgrade recommend` subcommand.
The logic is copied over from an existing `github.com/openshift/oc/pkg/cli/admin/upgrade` package. The logic is to be changed over the upcoming iterations of development.
For the initial commit, the new `recommend` package contains the logic from the `github.com/openshift/oc/pkg/cli/admin/upgrade` package as of the 93286c9260285c104259f0c50704c4b880c4fec3 commit. Only the logic regarding the default output of the `oc adm upgrade` command and outputs regarding available or available but not recommended updates was copied over.
This logic was placed behind a feature gate environment variable named `OC_ENABLE_CMD_UPGRADE_RECOMMEND`. The new subcommand can be tested by running:
```
$ …
```
> OTA-1271: Create the `oc adm upgrade recommend` subcommand

- pkg/cli/debug/debug.go
Without the `HOST` environment variable, I ran `sos report` on a node and it printed out (please see the `Size`);
```sh
Your sosreport has been generated and saved in:
/var/tmp/sosreport-node.tar.xz
Size	4.66MiB
```
After manually setting `HOST=/host` (please see the change of `Size`);
```sh
Your sosreport has been generated and saved in:
/host/var/tmp/sosreport-node.tar.xz
Size	12.35MiB
```
It looks like this unlocks some more reports. 
Users can manually export this environment variable and it works. However, it requires having this knowledge beforehand and most will move forward with the small size sos report. 
Alternatively we can update our oc debug document by mentioning this behavior and recommend them to run `export HOST=/host`. This still puts in a risk of moving forward with …
> OCPBUGS-41519: Add HOST env var in oc debug for sos report collects more

- pkg/cli/admin/upgrade/status/examples/4.16.0-ec2-control-plane-updated-pdb-prohibits-draining.detailed-output
- pkg/cli/admin/upgrade/status/examples/4.16.0-ec2-control-plane-updated-pdb-prohibits-draining.output
- pkg/cli/admin/upgrade/status/mco/layered_node_state.go
- pkg/cli/admin/upgrade/status/mco/layered_node_state_test.go
- pkg/cli/admin/upgrade/status/workerpool.go
- pkg/cli/admin/upgrade/status/workerpool_test.go
https://issues.redhat.com/browse/OTA-1292
Addressing the 4th case from https://github.com/openshift/oc/pull/1838#pullrequestreview-2238631410
/cc @petr-muller @Davoska
> OTA-1292: upgrade-status: improve messages for NotReady/DiskPressure/NetworkUnavailable

- pkg/cli/admin/prune/deployments/data.go
This PR covers the other places missed in https://github.com/openshift/oc/pull/1797
> OCPBUGS-42143: Check cast result in adm prune deployments to prevent panic

- pkg/cli/admin/nodeimage/create.go
- pkg/cli/admin/nodeimage/create_test.go
The "oc adm node-image create" command currently expects the filename to be node.x86_64.iso which doesn't work for non x86_64 architectures. Updated RsyncOptions to copy any iso file to include files for any CPU architecture.
Authored by @andfasano
> OCPBUGS-38450:  Fix copy artifacts for all CPU architectures

- pkg/cli/admin/upgrade/recommend/examples/4.14.1-both-available-and-conditional-cv.yaml
- pkg/cli/admin/upgrade/recommend/examples/4.14.1-both-available-and-conditional.include-not-recommended-output
- pkg/cli/admin/upgrade/recommend/examples/4.14.1-both-available-and-conditional.output
- pkg/cli/admin/upgrade/recommend/examples/README.md
- pkg/cli/admin/upgrade/recommend/examples_test.go
- pkg/cli/admin/upgrade/recommend/mockresources.go
- pkg/cli/admin/upgrade/recommend/recommend.go
Borrowing the framework from `pkg/cli/admin/upgrade/status`, so we can iterate on this tech-preview command without having to launch test-clusters to confirm we are getting the output we expect for covered situations.  Preparatory work for [OTA-1272](https://issues.redhat.com//browse/OTA-1272).
> OTA-1272: pkg/cli/admin/upgrade/recommend: Add end-to-end output test coverage

- pkg/cli/admin/inspect/inspect.go
- pkg/cli/admin/inspect/namespace.go
Daemonset pods running on worker nodes generate high volume of log which increase storage size of must-gather output drastically in addition to the longer collection duration. On the other hand, our primary focus is to collect logs from control  plane rather than data plane. So that it looks reasonable to **not** collect daemonset pods running on data plane if the cluster's worker node count is greater than 18 (still collect logs of the pods whose are running on control plane of given daemonset).
This PR also introduces node-selector flag into the oc adm inspect command. This will work as a workaround, if someone want to collect logs of those skipped pods like this;
```
oc adm inspect namespace openshift-multus --node-selector='node-role.kubernetes.io/worker'
```
> OCPBUGS-37344: Skip inspection of the daemonset pods running on data plane

- pkg/cli/admin/nodeimage/create.go
- pkg/cli/admin/nodeimage/create_test.go
By default the name of the output image is the one naturally provided by the node-joiner - since it includes also the target architecture prefix. The renaming must be applied only if specified by the user.
> OCPBUGS-42528: fix outputname flag for node-image create command

- pkg/cli/admin/mustgather/mustgather.go
Command shows the default value already in;
```
--volume-percentage=30:
Specify maximum percentage of must-gather pod's allocated volume that can be used. If this limit is exceeded,
must-gather will stop gathering, but still copy gathered data.
```
It is redundant to print default value, as special character `%` also breaks the help text.
> OCPBUGS-42601: Remove redundant defaulting message in description

- pkg/cli/create/user.go
This PR adds a validation to error out if user name contains new line.
> OCPBUGS-42775: Do not allow new line in user in create user

- pkg/cli/admin/inspect/discovery.go
- pkg/cli/admin/inspect/inspect.go
Required for reading the content back out.
> API-1835: gather discovery when using inspect

- pkg/cli/admin/upgrade/recommend/examples/4.12.16-longest-not-recommended.output
- pkg/cli/admin/upgrade/recommend/examples/4.12.16-longest-not-recommended.show-outdated-releases-output
- pkg/cli/admin/upgrade/recommend/examples/4.12.16-longest-not-recommended.version-4.12.51-output
- pkg/cli/admin/upgrade/recommend/examples/4.12.16-longest-recommended.output
- pkg/cli/admin/upgrade/recommend/examples/4.12.16-longest-recommended.show-outdated-releases-output
- pkg/cli/admin/upgrade/recommend/examples/4.12.16-longest-recommended.version-4.12.51-output
- pkg/cli/admin/upgrade/recommend/examples/4.14.1-all-recommended.show-outdated-releases-output
- pkg/cli/admin/upgrade/recommend/examples/4.14.1-all-recommended.version-4.12.51-output
- pkg/cli/admin/upgrade/recommend/examples_test.go
- pkg/cli/admin/upgrade/recommend/recommend.go
This allows us to drop the detailed, multi-line entries from the long `--show-outdated-releases` output.  Now that form just gives us an overview of releases with `reason` slugs for any updates with assessed issues.  Cluster administrators who see something in that overview that they are interested in can make a subsequent call with `--version VERSION` to get the long-form details on that particular target.
I'm keeping the long-form output for release-exposed risks in the default rendering though, because part of the motivation behind d8cac253ac (#1889) is to surface those longest-hop risk messages for cluster administrators, in case the issue is something like `EvaluationFailed`, which says more about the current cluster state than it does about the health of the update.
Because the …
> OTA-1273: pkg/cli/admin/upgrade/recommend: Add --version option for specific releases

- pkg/cli/admin/nodeimage/create.go
- pkg/cli/admin/nodeimage/create_test.go
Currently only a message saying an error has occurred is displayed which doesn't provide any information indicating the cause.
The container logs may indicate why image generation did not succeed.
> OCPBUGS-43513: Show node-joiner container logs when error occurs

- pkg/cli/admin/ocpcertificates/regeneratemco/OWNERS
- pkg/cli/admin/ocpcertificates/regeneratemco/rotatecerts.go
Closes: [OCPBUGS-43309](https://issues.redhat.com/browse/OCPBUGS-43309)
This ensures that the machine-config-server-tls secret is of the `kubernetes.io/tls` type before attempting to rotate them. 
This is only an issue in 4.18+, as the vendored cert controller package was updated during the 1.31.1 rebase. (https://github.com/openshift/oc/pull/1877, [diff](https://github.com/openshift/oc/pull/1877/commits/eac0d7de9cdc8a5e0c085415ea45577f14c32821#diff-33ef32bf6c23acb95f5902d7097b7a1d5128ca061167ec0716715b0b9eeaa5f6R39)) 
In the current master of library-go, the cert controller only permits secrets of the type `kubernetes.io/tls` to be rotated, and therefore this "preflight check" is necessary before running the controller sync.
> OCPBUGS-43309: The "oc adm ocp-certificates regenerate-machine-config-server-serving-cert" command is failing

- pkg/cli/admin/upgrade/upgrade.go
Folks might want to break through cluster-version-operator-side guards to test `--to-multi-arch` updates as well.
Also error on `--to-multi-arch` with `--to-latest`.   `--to-multi-arch` is about transitioning from single-arch to multi-arch without changing the version, so all of the "pick a new target version/release" options are incompatible.
> OCPBUGS-8259: pkg/cli/admin/upgrade: Propagate --force for --to-multi-arch

- pkg/helpers/newapp/newapptest/newapp_test.go
It seems that `openshift/origin` does not exist in quay anymore, so that a unit test in oc is perma-failing. This PR switches to existing image to unblock the CI.
> NO-JIRA: Fix newapp unit test failure by using different image

- pkg/cli/admin/upgrade/recommend/examples/4.12.16-longest-not-recommended.output
- pkg/cli/admin/upgrade/recommend/examples/4.12.16-longest-not-recommended.show-outdated-releases-output
- pkg/cli/admin/upgrade/recommend/examples/4.12.16-longest-not-recommended.version-4.12.51-output
- pkg/cli/admin/upgrade/recommend/examples/4.12.16-longest-recommended.output
- pkg/cli/admin/upgrade/recommend/examples/4.12.16-longest-recommended.show-outdated-releases-output
- pkg/cli/admin/upgrade/recommend/examples/4.12.16-longest-recommended.version-4.12.51-output
- pkg/cli/admin/upgrade/recommend/recommend.go
We've [had `Upgradeable` since 2019][1], but it is a confusing condition, because [the "between minor versions" wording][2] in the `message` isn't obvious to users who have not yet internalized [SemVer's `MAJOR.MINOR.PATCH` terminology][3].  [Conditional update risks landed in 2021][4] and give us a clear API for declaring exactly which update targets have the exposure.  This commit adds client-side code to the tech-preview `recommend` subcommand, so folks can get a feel for that user experience.  If it goes over well, we can shift the logic to the cluster-version operator so all clients can benefit.  The `alreadyHasUpgradeableRisk` check ensures we don't double up if the CVO eventually picks up this pivot.
[1]: https://github.com/openshift/api/pull/206
[2]: …
> OTA-902: pkg/cli/admin/upgrade/recommend: Treat Upgradeable=False as a conditional update risk

- pkg/cli/admin/release/image_mapper.go
- pkg/cli/admin/release/image_mapper_test.go
- pkg/cli/admin/release/new.go
While working towards fixing [OCPBUGS-19824](https://issues.redhat.com/browse/OCPBUGS-19824) and [OCPBUGS-30080](https://issues.redhat.com/browse/OCPBUGS-30080) I needed to familiarize myself with this code. Taking opportunities for small improvements as I go.
Separating commits for easy review (and to allow easy removing some changes if not desired for any reason), but I think we can squash-merge them:
- **adm release: remove unused code**
- **adm release: port deprecated functions**
- **adm release: minor cleanups**
- **adm release: compile regex just once**
- **adm release: simplify regexes**
> NO-JIRA: adm release: cleanups

- pkg/cli/admin/nodeimage/basenodeimagecommand.go
- pkg/cli/admin/nodeimage/create.go
- pkg/cli/admin/nodeimage/create_test.go
- pkg/cli/admin/nodeimage/monitor.go
- pkg/cli/admin/nodeimage/monitor_test.go
This patch refactors the `create` command output by streaming the workflow report generated (and continuously updated) by the node-joiner tool during the command execution, in order to provide a more informative live feedback to the user.
In case of command error the report is automatically saved in the asset folder as `report.json`, and error details are saved within.
If the command doesn't not complete correctly (for any reason), the pod logs are also stored in the report.json (if available.
A new command option flag `--report` is provided to allow saving always the report file.
(note: the new improved output (as well as the report.json) will be available only for 4.18+)
Sample output:
```
2024-11-15T15:03:00Z [node-image create] Launching command
2024-11-15T15:03:05Z [node-image …
```
> AGENT-1000: improve oc adm node-image output

- pkg/cli/admin/release/new.go
Full `imageData` was passed to the callback but existing callbacks only needed the containing directory. Therefore the callback signature can be simplified to `func(directory, content, operator)`
/cc @wking @DavidHurta
> NO-JIRA: adm release: simplify manifest iteration

- pkg/cli/admin/inspect/proxy.go
- pkg/cli/admin/inspect/proxy_test.go
- pkg/cli/admin/inspect/resource.go
- pkg/cli/admin/inspect/route.go
- pkg/cli/admin/inspect/route_test.go
- pkg/cli/admin/inspect/secret.go
- pkg/cli/admin/inspect/secret_test.go
Proxy resource can contain sensitive information and inspect command should obfuscate all these fields. This PR achieves this.
> OCPBUGS-45022: Obfuscate sensitive data in Proxy resource while inspection

- pkg/cli/admin/upgrade/status/examples/to-multi-arch.detailed-output
- pkg/cli/admin/upgrade/status/examples/to-multi-arch.output
- pkg/cli/admin/upgrade/status/workerpool.go
Address https://github.com/openshift/oc/pull/1920#discussion_r1854403418
I thought we would need something from the MCO side to recognize the transactions between node phases (as the operator image pull spec is a new thing). While thinking about it again, MCO must have known if it needs to update the nodes without the pull spec and found the annotations. I checked the machine configs for multi-arch migration (see the following bash output): `master` (`worker` respectively) has two with `4.18.0-ec.3` and each of them should be for before-and-after the update.
The `status` command does not need to use these annotations as [the version annotation](https://github.com/openshift/oc/blob/21c3b92e2d5aa8771795f147178369414f15605a/pkg/cli/admin/upgrade/status/workerpool.go#L245) is enough until the …
> OTA-1393: status: recognize multi-arch in node phase

- .ci-operator.yaml
- go.mod
- images/cli-artifacts/Dockerfile.rhel
- images/cli/Dockerfile.rhel
- images/tools/Dockerfile
This PR is proposed as a replacement of https://github.com/openshift/oc/pull/1935 and the others that will be opened automatically.
> OCPBUGS-45454: Update to 4.19 and Go 1.23.0

- pkg/cli/rollout/rollout.go
DeploymentConfig has been deprecated and we recommend to use Deployment instead. However, `oc rollout` command's descriptions and examples are still pointing to DC. 
This PR updates;
* `oc rollout`  with `kubectl rollout`
* `oc rollout history` with `kubectl rollout history`
* `oc rollout pause` with `kubectl rollout pause`
* `oc rollout resume` with `kubectl rollout resume`
* `oc rollout undo` with `kubectl rollout undo`
* `oc rollout status` with `kubectl rollout status`
This PR leaves;
* `oc rollout cancel`
* `oc rollout latest`
* `oc rollout retry`
as is, since these commands only work on DeploymentConfig.
DeploymentConfig works properly in all these commands and we won't change this. This PR's aim is to remove DeploymentConfig from the examples and descriptions. This PR should be …
> OCPBUGS-45177: rollout: Update examples and descriptions aligning with kubectl

- pkg/cli/admin/nodeimage/create.go
- pkg/cli/admin/nodeimage/create_test.go
This patch takes care of copying only the required artifacts from the node-joiner pod  when the --pxe command flag is used (instead the copy the whole folder)
> OCPBUGS-45311: fix oc adm node-image create --pxe command to copy the correct artifacts

- pkg/cli/admin/nodeimage/create.go
They were introduced recently for "oc adm node-image create" and should be marked as experimental until next release.
> OCPBUGS-45991: Mark --report and --pxe flags as experimental

- pkg/cli/admin/release/extract_tools.go
Catching up with [additional 4.14 capabilities][1].  As with `MachineAPI`, all of the new capabilities were enabled in all 4.13 clusters, and because [capabilities cannot be uninstalled][2], that means they'll be enabled, possibly implicitly, after an update to 4.14.  Including them here ensures that we extract the `ImageRegistry` CredentialsRequest in:
```console
$ oc adm release extract --included --credentials-requests --to credentials-requests quay.io/openshift-release-dev/ocp-release:4.14.0...
```
when connecting to a currently-4.13 cluster.  [OTA-1010][3] is tracking a more sustainable long-term approach.
[1]: https://github.com/openshift/cluster-version-operator/pull/950/commits/ba3aeb9ab9d6d20a7355f80db4c47950b307a893#diff-f3e6bd2d0c764f1c28fd5d20520a2224b1f3cb5306500aeefd056a4efc8 …
> OCPBUGS-18961: pkg/cli/admin/release/extract_tools: Enable ImageRegistry, etc. on 4.13-to-4.14

- pkg/cli/admin/release/image_mapper.go
- pkg/cli/admin/release/new.go
Previously the substitution was performed only on manifests extracted from images that supplied `image-references`. It should be possible to perform the basic version (but not component versions like 0.0.1-snapshot-component or things like pullspecs) substitution on such manifests safely.
> OCPBUGS-19824: release new: replace 0.0.1-snapshot in all manifests

- pkg/cli/admin/network/pod_network.go
`oc adm pod-network` command only works on OpenShift SDN which has been deprecated long time ago. So still advertising this command in help output is misleading. 
This PR marks this command as hidden, so `oc adm --help` will not print it. Besides, this PR marks this command as deprecated, so there will be a deprecation message during its usage.
```sh
$ ./oc adm pod-network
Command "pod-network" is deprecated, pod-network command only works on OpenShift SDN which has been deprecated.
Manage pod network in the cluster
```
Other than that, users still rely on the functionality of this command will continue using it as is (just an additional deprecation message that should not cause any issues).
> OCPBUGS-46361: Mark adm pod-network command as hidden and depcated

- pkg/cli/admin/nodeimage/monitor.go
This commit updates the isMonitoringDone function to retry and not exit if the error from reading the node-joiner pod is
Get "https://api.ostest.test.metalkube.org:6443/api/v1/namespaces/openshift-node-joiner-zfbp9/pods/node-joiner-monitor-4lx8l": EOF
This happens if the oc client is temporarily disconnected from the api server. The error returned is type net/url/Error.
> OCPBUGS-38975: monitor should not exit for temp api disconnect

- pkg/cli/admin/upgrade/status/examples/README.md
Catching the docs up with 10c41f5262 (#1740).
Also drop the enumeration that started when the file was created in 57e984491c (#1595).  Folks who care how many inputs and outputs there currently are can count for themselves, and this content is easier to maintain without having to bump later entry numbers when inserting an earlier entry.
> NO-ISSUE: admin/upgrade/status/examples/README: Document *-alerts.json

- go.mod
- go.sum
- vendor/modules.txt
> OCPBUGS-49450: Address `github.com/docker/docker` CVE

- go.mod
- go.sum
- vendor/modules.txt
> [release-4.18] OCPBUGS-49604: Address `github.com/docker/docker` CVE

- OWNERS_ALIASES
- pkg/cli/admin/top/top.go
- pkg/cli/admin/toppvc/OWNERS
- pkg/cli/admin/toppvc/persistentvolumeclaims.go
- pkg/cli/admin/toppvc/printer.go
The code makes use of a Prometheus query to implement the `oc adm top persistentvolumeclaims` and show usage statistics for bound persistentvolumeclaims, as follows:
```
oc adm top pvc --insecure-skip-tls-verify=true -n reproducer-pvc
NAMESPACE      NAME               USAGE(%) 
reproducer-pvc pvc-reproducer-pvc 98.28    
reproducer-pvc pvc-test-pvc       14.56    
```
It supports the following flags:
```
-A, --all-namespaces=false:
If present, list the pvc usage across all namespaces. Namespace in current context is ignored even if
specified with --namespace
--insecure-skip-tls-verify=false:
If true, the server's certificate will not be checked for validity. This will make your HTTPS connections
insecure
```
> STOR-2040: CLI command to display bound pvc filesystem usage percentage

- go.mod
- go.sum
- vendor/modules.txt
> [release-4.17] OCPBUGS-49605: Address `github.com/docker/docker` CVE

- pkg/helpers/source-to-image/tar/tar.go
Security jobs are failing by warning us about unsanitized tar file. This PR sanitizes tar header file.
> NO-JIRA: Sanitize tar header name as it is used in path

- pkg/cli/admin/upgrade/recommend/alerts.go
- pkg/cli/admin/upgrade/recommend/examples/4.12.16-longest-not-recommended.output
- pkg/cli/admin/upgrade/recommend/examples/4.12.16-longest-not-recommended.show-outdated-releases-output
- pkg/cli/admin/upgrade/recommend/examples/4.12.16-longest-not-recommended.version-4.12.51-output
- pkg/cli/admin/upgrade/recommend/examples/4.12.16-longest-recommended.output
- pkg/cli/admin/upgrade/recommend/examples/4.12.16-longest-recommended.show-outdated-releases-output
- pkg/cli/admin/upgrade/recommend/examples/4.12.16-longest-recommended.version-4.12.51-output
- pkg/cli/admin/upgrade/recommend/examples/4.14.1-all-recommended.output
- pkg/cli/admin/upgrade/recommend/examples/4.14.1-all-recommended.show-outdated-releases-output
- pkg/cli/admin/upgrade/recommend/examples/4.14.1-all-recommended.version-4.12.51-output
- pkg/cli/admin/upgrade/recommend/examples/4.16.27-degraded-monitoring-alerts.json
- pkg/cli/admin/upgrade/recommend/examples/4.16.27-degraded-monitoring-cv.yaml
- pkg/cli/admin/upgrade/recommend/examples/4.16.27-degraded-monitoring.output
- pkg/cli/admin/upgrade/recommend/examples/4.16.27-degraded-monitoring.show-outdated-releases-output
- pkg/cli/admin/upgrade/recommend/examples/4.16.27-degraded-monitoring.version-4.12.51-output
- pkg/cli/admin/upgrade/recommend/examples_test.go
- pkg/cli/admin/upgrade/recommend/mockresources.go
- pkg/cli/admin/upgrade/recommend/precheck.go
- pkg/cli/admin/upgrade/recommend/recommend.go
- pkg/cli/admin/upgrade/status/alerts.go
Retrieving alerts and rendering the interesting ones, as described in [OTA-1426](https://issues.redhat.com/browse/OTA-1426).  See the individual commit messages for me trying to walk through building this in steps, and the new `pkg/cli/admin/upgrade/recommend/examples/4.16.27-degraded-monitoring.output` for the most direct example of the new logic.
> OTA-1426: pkg/cli/admin/upgrade: Check and display interesting alerts

- pkg/cli/admin/toppvc/persistentvolumeclaims.go
Hi Team, 
PTAL for the issue:
https://issues.redhat.com/browse/OCPBUGS-50682
https://issues.redhat.com/browse/OCPBUGS-50683 
Output Verification after fix:
oc adm top pvc --insecure-skip-tls-verify=true -n testropatil 
error: no persistentvolumeclaims found or mounted in testropatil namespace.
oc adm top pvc --insecure-skip-tls-verify=true -n testropatil 
NAMESPACE   NAME         USAGE(%) 
testropatil mypvc-fs-gp2 0.00%    
testropatil mypvc-fs-gp3 0.00%
> OCPBUGS-50682: OCPBUGS-50683: Correct oc adm top pvc messages

- pkg/cli/admin/upgrade/recommend/examples/4.12.16-longest-not-recommended.output
- pkg/cli/admin/upgrade/recommend/examples/4.12.16-longest-not-recommended.show-outdated-releases-output
- pkg/cli/admin/upgrade/recommend/examples/4.12.16-longest-not-recommended.version-4.12.51-output
- pkg/cli/admin/upgrade/recommend/examples/4.12.16-longest-recommended.output
- pkg/cli/admin/upgrade/recommend/examples/4.12.16-longest-recommended.show-outdated-releases-output
- pkg/cli/admin/upgrade/recommend/examples/4.12.16-longest-recommended.version-4.12.51-output
- pkg/cli/admin/upgrade/recommend/examples/4.14.1-all-recommended.output
- pkg/cli/admin/upgrade/recommend/examples/4.14.1-all-recommended.show-outdated-releases-output
- pkg/cli/admin/upgrade/recommend/examples/4.14.1-all-recommended.version-4.12.51-output
- pkg/cli/admin/upgrade/recommend/examples/4.16.27-degraded-monitoring.output
- pkg/cli/admin/upgrade/recommend/examples/4.16.27-degraded-monitoring.show-outdated-releases-output
- pkg/cli/admin/upgrade/recommend/examples/4.16.27-degraded-monitoring.version-4.12.51-output
- pkg/cli/admin/upgrade/recommend/recommend.go
The ClusterVersion spec property is `spec.upstream`, and that's a v1 API we cannot easily change.  But in freeform text here, we can get closer to [the "OpenShift Update Service" wording we use in docs][1].  I haven't included "OpenShift", because hopefully that context is obvious to folks running `oc ....`.  I haven't Title Cased, because I'm not listing a particular product/implementation; it's possible that the customer has pointed their cluster at a custom update service like [a raw GitHub file][3].  I've kept "Upstream" to make it easier for folks to associate with spec.upstream.  And I've left the GA `oc adm upgrade` alone on this, because it's been using "Upstream:" for years now, and this seems minor enough that I don't think it's worth disrupting things there.
[1]: …
> NO-ISSUE: pkg/cli/admin/upgrade/recommend: "Upstream" -> "Upstream update service"

- pkg/cli/admin/upgrade/recommend/examples/4.16.27-degraded-monitoring.version-4.16.32-output
- pkg/cli/admin/upgrade/recommend/examples/README.md
- pkg/cli/admin/upgrade/recommend/examples_test.go
Always testing 4.12.51 was easy, but is less interesting once we have one `no updates to 4.12 available` example.  Make the target version for each ClusterVersion dump configurable, so we can see what `--version <VERSION>` with working versions expands too on more recent dumps as well.
> NO-ISSUE: pkg/cli/admin/upgrade/recommend: Configureable version for test fixtures

- pkg/cli/admin/upgrade/status/controlplane.go
- pkg/cli/admin/upgrade/status/controlplane_test.go
[cvo#1165](https://github.com/openshift/cluster-version-operator/pull/1165) introduced uncertainty of the Failing condition (`Failing=Unknown`). This PR adjusts the impact summary in updateInsight accordingly.
> OCPBUGS-23514: status: Adjust impact summary for Failing=Unknown

- pkg/cli/debug/debug.go
`chroot /host` does not change the namespaces for the current process. In particular not joining the mount namespace is a continuous source of confusion for mounts not being propagated to the containers.
Suggest `nsenter` as a better alternative.
> NO-JIRA: debug: suggest nsenter instead of chroot

- pkg/cli/admin/toppvc/persistentvolumeclaims.go
- Go’s net/http client resolves DNS before proxying the request — proxies are only used after DNS resolution. So we'd better init Go HTTP Client with Standard HTTP Proxy if the proxy environment variables set.
**Local test wroked**
```console
$ export http_proxy=http://XXXX
$ export https_proxy=http://XXXX
$ oc adm top pvc --insecure-skip-tls-verify=true --v=8
I0324 22:52:59.943468   40954 loader.go:402] Config loaded from file:  /Users/wangpenghao/hc.kubeconfig
I0324 22:52:59.943835   40954 envvar.go:172] "Feature gate default state" feature="InformerResourceVersion" enabled=false
I0324 22:52:59.943855   40954 envvar.go:172] "Feature gate default state" feature="WatchListClient" enabled=false
I0324 22:52:59.943860   40954 envvar.go:172] "Feature gate default state" …
```
> OCPBUGS-54168: Use ProxyFromEnvironment when creating HTTP transport

- pkg/cli/admin/release/new.go
The actual `operators` content is never used, so it does not need to be sorted, and treating `nil` as a silent good case and `len()==0` as an error case does not look right (`writePayload` never produces an empty non-nil `operators`).
> NO-JIRA: `adm release new`: simplify no operator error condition

- pkg/cli/admin/release/new.go
There was code that was supposed to handle potentially nested path, but this path (parts) is hardcoded to be a single top-level directory, so none of the complexity is necessary and can be removed, including the special `writeNestedTarHeader` method.
Some declarations can be moved closer to where they are used, improving readability.
> NO-JIRA: `adm release new`: simplify `writePayload`

- pkg/cli/admin/release/new.go
Reverts openshift/oc#1997
https://redhat-internal.slack.com/archives/C06Q309QUDV/p1743183670944419
> NO-JIRA: Revert `adm release new`: simplify `writePayload`"

- pkg/cli/admin/release/annotations.go
- pkg/cli/admin/release/info.go
- pkg/cli/admin/release/info_test.go
- pkg/cli/admin/release/info_unix.go
- pkg/cli/admin/release/info_windows.go
It's often useful when looking up release images to know the list of RPM packages that shipped in the node image. Add new switches for this:
- `oc adm release info --rpmdb $IMG` will list all the packages in the node image for the given release image payload
- `oc adm release info --rpmdb-diff $IMG1 $IMG2` will diff the set of packages in the node image for the given release image payloads
The code is generic over the actual target image. By default, the node image is used, but `--rpmdb-image` can be used to select a different one.
The primary motivation for this is
https://github.com/openshift/enhancements/pull/1637, in which the node image will no longer be built within the CoreOS pipeline as a base image. Instead, it will be a layered image built in OpenShift CI/Konflux. As a result, …
> COS-3023: pkg/cli/admin/release/info: support generating RPM diffs

- pkg/cli/image/extract/extract.go
When the original PR (#1966) merged, we started to get the following error:
```
I0407 12:45:14.563409       1 release_info.go:369] Failed to generate RPM diff: exit status 1
$ /usr/bin/oc adm release info --rpmdb-cache=/tmp/rpmdb/ --output=json --rpmdb-diff quay.io/openshift-release-dev/ocp-release@sha256:3c7decd8e09329d5206a96bcc19838d25bdc3af9c9565f249aa91494c7beb7db quay.io/openshift-release-dev/ocp-release@sha256:1e9baecce90105b4c0aa695dadc2fac7e4b9fd54e0d2ede90e143e57df8e424a
error: fetching rpmdb for from image: downloading quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:8fac1110def727105bd11bbf49fef58072b970d40e9e55e5a645fcc54e00610a: unable to extract layer sha256:92aa75b30536c7a6425569a089281f13e3a280359eca40c2ed0cfa33c5a24134 from …
```
> COS-3023: Fixing rpmdiff permissions when running in container

- pkg/cli/admin/nodeimage/create.go
This PR introduces a conditional filter to include .ins and .addrsize PXE artifacts only when the target CPU architecture is s390x during ABI-based Day-2 node image creation using oc adm node-image create.
Changes:
Updated the create.go logic to check for s390x CPU architecture before including:
*.ins
*.addrsize
Testing
Tested by:
Running the oc adm node-image create for s390x and verified only s390x-relevant PXE files are generated.
Ensured no regression on other platforms — .ins and .addrsize are excluded when architecture is not s390x.
> OCPBUGS-52164: Add the generation of initrd.addrsize and generic.ins file for ABI Day2 Artifacts

- pkg/cli/admin/nodeimage/basenodeimagecommand.go
- pkg/cli/admin/nodeimage/mirrorbuilder.go
- pkg/cli/admin/nodeimage/mirrorbuilder_test.go
In order to handle disconnected environments for the node-image command, get the installer image from the configMap created by the installer instead of extracting it from the releaseImage.
> OCPBUGS-53106: Get installer image from configMap for node-image command

- pkg/cli/admin/mustgather/mustgather.go
must-gather image contains various kind of command executions. Some of them do not support filtering based on `--since-time` flag. So that, this creates confusions for users. This PR updates the flag description by clarifying this behavior.
> NO-JIRA: OCPBUGS-46604: Clarify behavior of since-time flag in oc adm must-gather command

- pkg/helpers/source-to-image/tar/tar.go
Extracting a tar file that contains colon in the name fails on Windows hosts, as this character is special for Windows. This PR replaces colon with hypen during extraction, if the host is Windows.
There are a couple of command in oc relies on this functionality like must-gather.
> OCPBUGS-55220: Replace colon to hypen in the filename while extracting tar on Windows

- pkg/cli/admin/mustgather/mustgather.go
These are unlikely to be helpful in debugging why a must-gather attempt failed (for that, you'd need to capture the must-gather namespace before deleting it), but they do make the fallback inspect artifacts more useful for folks trying to understand the issue that caused them to want to must-gather (e.g. "why is my cluster stuck mid-update?").
I'm hard-coding the `openshift-cluster-version` namespace for now, but future ClusterVersion may grow a `status.relatedObjects` (as ClusterOperator already have), and at some point in the future that might make the hard-coded namespace redundant and drop-able.
> OCPBUGS-56598: pkg/cli/admin/mustgather: Include ClusterVersion in fallback inspect

- pkg/cli/admin/nodeimage/create.go
- pkg/cli/admin/nodeimage/create_test.go
This patch addresses the https://issues.redhat.com/browse/OCPBUGS-49897 issue by disabling explicitly the rsync permissions transfer when copying the node-joiner pod artifacts to the configured destination folder.
> OCPBUGS-49897: avoid transfering permissions when copying artifacts from node-joiner pod

- pkg/cli/admin/release/extract.go
Because `o.File != ""` and `o.ExtractManifests` are mutually exclusive, there be at most ONE callback at each run. We do not have to handle the list of callbacks.
/cc @petr-muller
> NO-JIRA: Simplify TarEntryCallback

- pkg/cli/debug/debug.go
User Requirement: https://issues.redhat.com/browse/OCPSTRAT-846
Issue: https://issues.redhat.com/browse/OCPNODE-3426
As part of developing a user activity auditing feature for openshift nodes, we need a reliable way to identify the user who initiated a debug pod. Our current solution, leveraging the Security Profiles Operator, relies on injecting the request.UID into the debug pod's environment variables via a mutating admission webhook.
However, a fundamental challenge exists in identifying these "debug pods" within the webhook. While OpenShift's `oc debug node/<nodename>` command already injects an annotation (debug.openshift.io/source-container and debug.openshift.io/source-resource) to mark debug pods, Kubernetes webhooks, by design, only support label selectors (not annotation …
> OCPNODE-3426: Introduce a dedicated Pod label for the purpose of identifying debug pods

- pkg/cli/admin/inspect/namespace.go
OVN-Kubernetes (OVN-K) UserDefinedNetwork (UDN) is namespace-scope CRD that allows non-admin users create OVN-K user-defined networks w/o a cluster-admin intervention.
Collect UDN CRs to allow troubleshooting them.
> CORENET-5412: adm, inspect, ns: Collect UserDefinedNetwork CRs

- pkg/cli/admin/upgrade/recommend/recommend.go
- pkg/cli/admin/upgrade/upgrade.go
Most OpenShift feature gates are tracked in openshift/api.  This one is just the local environment variable, but we still want to meet [the usual tech-preview-to-GA promotion criteria][1]:
> * Tests must contain either `[OCPFeatureGate:<FeatureGateName>]` or the standard upstream `[FeatureGate:<FeatureGateName>]`.
This one isn't relevant to this feature, because the test-cases are ungated to run the tech-preview functionality against production clusters (openshift/origin#29831).  As [docs say][3]:
> Your cluster does not need to be a Technology Preview-enabled cluster in order for you to use the `oc adm upgrade recommend` command.
> * There must be at least five tests for each FeatureGate.
[Sippy][4] returns exactly five:
```
[Serial][sig-cli] oc adm upgrade recommend runs successfully, …
```
> OTA-1560: pkg/cli/admin/upgrade: Promote 'recommend' to general availability

- pkg/helpers/describe/describer.go
- pkg/helpers/describe/describer_test.go
The TemplateInstanceDescriber.DescribeTemplateInstance function was attempting to access templateInstance.Spec.Secret.Name without checking if Secret is nil first. Since Secret is an optional pointer field, this caused a nil pointer dereference panic when describing template instances that don't have a secret specified.
Added a nil check before accessing Secret.Name and provide appropriate fallback behavior by displaying "No secret specified for parameters" when no secret is present.
> OCPBUGS-60281: Fix panic in oc describe templateinstance when Secret is nil

- pkg/cli/login/loginoptions.go
- pkg/cli/login/loginoptions_test.go
When logged in using an ExecProvider and executing oc login -u as a followup, the stored ExecProvider is not preserved in the user object stored in the kubeconfig, causing subsequent oc commands to fail.
This patch makes sure ExecProvider is actually preserved on oc login -u.
I haven't tested the whole login flow, I only added some tests to ensure the config is being preserved.
> OCPBUGS-58393: oc login: Preserve ExecProvider on oc login -u

- pkg/cli/admin/upgrade/status/status.go
- pkg/cli/admin/upgrade/upgrade.go
- Stop gating the command on an env variable presence
- Hide the mock input flag
The `UpgradeStatus` feature gate became eligible for promotion (https://github.com/openshift/api/pull/2418  by passing the [ci/prow/verify-feature-promotion](https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_api/2418/pull-ci-openshift-api-master-verify-feature-promotion/1957733316027224064) check.
- [UpgradeStatus Feature Gate](https://sippy.dptools.openshift.org/sippy-ng/feature_gates/4.20?filters=%257B%2522items%2522%253A%255B%257B%2522columnField%2522%253A%2522feature_gate%2522%252C%2522operatorValue%2522%253A%2522equals%2522%252C%2522value%2522%253A%2522UpgradeStatus%2522%257D%255D%252C%2522linkOperator%2522%253A%2522and%2522%257D)
- [UpgradeStatus Fetature Gate …
> OTA-1581: Promote `oc adm upgrade status` to general availability

- pkg/cli/admin/mustgather/mustgather.go
Delete the temporary namespace after the backup gathering.
> WRKLDS-593: oc adm must-gather: Improve cleanup order

- pkg/cli/admin/inspect/admission_webhooks.go
- pkg/cli/admin/inspect/apiextensions.go
- pkg/cli/admin/inspect/inspect.go
- pkg/cli/admin/inspect/namespace.go
- pkg/cli/admin/inspect/pod.go
- pkg/cli/admin/inspect/proxy.go
- pkg/cli/admin/inspect/resource.go
- pkg/cli/admin/inspect/route.go
- pkg/cli/admin/inspect/secret.go
- pkg/cli/admin/inspect/writer.go
`context.Context` is now being passed around to support interrupting the whole inspection process.
`RunContext` method is the entry point.
There is no functional change.
Split from https://github.com/openshift/oc/pull/2062
> OCPBUGS-59311: pkg/.../inspect: Add support for context.Context

- pkg/cli/admin/mustgather/mustgather.go
- pkg/cli/admin/mustgather/mustgather_test.go
This is in preparation of proper signal handling.
Split from https://github.com/openshift/oc/pull/2062
> OCPBUGS-59311: oc adm must-gather: Add support for context

- pkg/cli/admin/nodeimage/create.go
- pkg/cli/admin/nodeimage/create_test.go
This PR adds validation for the --root-device-hint flag in the Create Node Image command.
Previously, providing an invalid format would cause the command to crash with a stack trace.
> OCPBUGS-62445: prevent crash when rootDeviceHints format is invalid
