images/cli/Dockerfile, images/cli/Dockerfile.rhel
Same build failure as https://github.com/openshift/openshift-controller-manager/pull/3
=> Install missing dependencies on OCP build

images/cli/Dockerfile.rhel
=> Make sure packages are installed

Makefile
=> Fix kubernetes git version in ART build

contrib/completions/bash/oc, contrib/completions/zsh/oc, pkg/cli/admin/node/logs.go
=> Bug 1669657 - Add --boot option to oc adm node-logs

images/cli/Dockerfile.rhel
This is needed to fix problems in https://github.com/openshift/release/pull/4807.
=> Add --force when linking other oc binaries

pkg/cli/admin/mustgather/mustgather.go
To resolve: https://github.com/openshift/oc/pull/21#discussion_r314258825
=> remove aggregateErrorOrNil func

pkg/cli/admin/upgrade/upgrade.go, pkg/cli/admin/upgrade/upgrade_test.go
=> Bug 1744289: sort available updates when printing

oc.spec
=> Fix kubectl in rpm

oc.spec
=> Cleanup spec

pkg/cli/admin/release/release.go
=> Bug 1610599: Remove RunE usage from oc

pkg/cli/debug/debug.go
Clarify the inputs to the debug command.
/assign mfojtik
=> debug: Improve docs of oc debug command to mention nodes

pkg/cli/admin/mustgather/mustgather.go
`oc adm must-gather` writes directly to `--dest-dir` when only using one plugin image, or to `--dist-dir`/`pod.Name` sub-directory when executing multiple plugin images.
This PR changes `oc adm must-gather` to always write to a sub-directory of `--dest-dir`. The sub-directory will be based on the resolved `imageID` of the plugin. For example, the default must-gather plugin would write to a sub-directory named 
`registry-svc-ci-openshift-org-ocp-4-2-2019-09-03-102629-sha256-99353133df86a6baacaeaeab602f0fc9638c8abc79ae768e4d516bb2fe4a0a3a`.
=> oc adm must-gather should always write output to sub dir

pkg/cli/admin/node/logs.go
=> Bug 1728111 - update oc adm node-logs with information about tail line limits

pkg/cli/admin/release/mirror.go
Don't call this unless both `o.From` and `o.To` are set, to avoid dying with:
```
error: Error creating mirror usage instructions: Unable to parse image reference '': repository name must have at least one component
```
when either the source or the target was actually an image-stream.
=> pkg/cli/admin/release/mirror: Conditional printImageContentInstructions

pkg/cli/admin/inspect/pod.go
This will teach inspect to download /debug/pprof/heap, profile and trace for containers that expose that endpoint using the metrics port (usually the apiserver).
/cc @deads2k 
(do not merge, pending manual testing)
=> inspect: collect /debug/pprof data

pkg/helpers/describe/projectstatus.go
=> Bug 1540560: fix oc status for daemonsets

pkg/helpers/graph/kubegraph/analysis/podspec.go
=> Bug 1542325: ignore pods when giving liveness suggestions

pkg/cli/newapp/newapp.go
=> Corrects error message

pkg/cli/newapp/newapp.go
Labels generated by `oc new-app` are not compatible with odo and Developer perspective in console. The generated labels should get aligned so that applications appear in the console consistently regardless of How they are created.
- DevTools recommended labels:
https://github.com/gorkem/app-labels/blob/master/labels-annotation-for-openshift.adoc
- Kubernetes recommended labels:
https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/
Refer - https://jira.coreos.com/browse/APPSVC-62
=> Align oc new-app generate labels with recommended label

pkg/cli/debug/debug.go
=> Bug 1767675: fix debug's comment

pkg/cli/admin/node/logs.go
=> Bug 1763807: print detailed error to user when getting node logs

pkg/cli/admin/upgrade/upgrade.go
Followup from #109.
/assign @smarterclayton 
cc @mffiedler
=> Bug 1759185: clarify upgrade's force flag description

pkg/cli/newapp/newapp.go
=> Bug 1770144: fix imagestream parsing to properly split its namespace part

cmd/oc/oc.go
=> Bug 1776100: don't install quota CRDs

pkg/cli/admin/inspect/pod.go
the insecurebackendproxy value is safe enough for us to use if we identify those logs
=> make inspect more resilient and slightly faster

cmd/oc/oc.go
Pick https://github.com/openshift/oc/pull/184 since the other reached context limits and I can't repush it.
=> [release-4.2] Bug 1776495: don't install quota CRDs

pkg/helpers/describe/describer_test.go
Go 1.13 brings in more import statements during test execution than
Go 1.12, resulting in the test seeing everything in openshift/api.
Exclude these types from needing describers for now.
=> test: Fix describer test to exclude extra types

pkg/cli/logs/logs.go
=> Bug 1784755: set insecure-skip-tls-verify-backend flag

go.mod, go.sum, vendor/github.com/openshift/library-go/alpha-build-machinery/make/lib/golang.mk, vendor/modules.txt
picks https://github.com/openshift/library-go/pull/653
/cc @soltysh
=> Respect -mod=vendor for go list

pkg/cli/set/probe.go
Fixes openshift/origin#24231
/assign @sallyom 
/cc @bszeti @xingxingxia
=> Set path based on requestURI, not just path

Makefile
=> Bug 1779519: fix version ldflags

go.mod, go.sum, vendor/k8s.io/kubectl/pkg/cmd/set/set_resources.go, vendor/k8s.io/kubectl/pkg/cmd/set/set_subject.go, vendor/modules.txt
=> Bug: 1773266: UPSTREAM: 85490 don't error if set-resources|subject patch empty

Makefile, vendor/github.com/getsentry/raven-go/Dockerfile.test
=> Bug 1793267: Add verify-deps target

go.mod, go.sum, pkg/cli/cli.go, pkg/cli/logs/logs.go, pkg/cli/logs/logs_test.go, vendor/k8s.io/kubectl/pkg/polymorphichelpers/logsforobject.go, vendor/modules.txt
=> Bug 1774366: Squash oc logs on top upstream logs command

pkg/cli/admin/catalog/build.go
Fixed bug: https://bugzilla.redhat.com/show_bug.cgi?id=1798961
=> Bug 1798961: correct the example info

pkg/cli/admin/catalog/mirror.go
Backports https://github.com/openshift/oc/pull/253 to release-4.3.
=> [release-4.3] Bug 1797730: Mirror images one by one for oc adm catalog mirror

go.mod, go.sum, vendor/k8s.io/kubectl/pkg/describe/versioned/describe.go, vendor/modules.txt
Brings https://github.com/openshift/kubernetes-kubectl/pull/15 into oc.
=> Bug 1762692: Bump kubectl 1.17

pkg/cli/admin/mustgather/mustgather.go
=> Bug 1755428:  improve error msgs in must-gather in case of must-gather pod not found

glide.lock, glide.yaml, pkg/cli/kubectlwrappers/wrappers.go, vendor/github.com/openshift/library-go/pkg/controller/fileobserver/observer.go, vendor/github.com/openshift/library-go/pkg/controller/fileobserver/observer_polling.go, vendor/github.com/openshift/library-go/pkg/controller/fileobserver/observer_polling_test.go, vendor/github.com/openshift/library-go/pkg/operator/staticpod/certsyncpod/certsync_controller.go, vendor/k8s.io/kubernetes/pkg/kubectl/cmd/config/config.go
This is cherry-pick of #246 and I additionally pinned deps not to bring undesired changes. 
=> Bug 1789869: allow --config and --kubeconfig

go.mod, go.sum, vendor/github.com/mtrmac/gpgme/.appveyor.yml, vendor/github.com/mtrmac/gpgme/.travis.yml, vendor/github.com/mtrmac/gpgme/data.go, vendor/github.com/mtrmac/gpgme/go.mod, vendor/github.com/mtrmac/gpgme/go_gpgme.c, vendor/github.com/mtrmac/gpgme/go_gpgme.h, vendor/github.com/mtrmac/gpgme/gpgme.go, vendor/github.com/mtrmac/gpgme/unset_agent_info.go, vendor/github.com/mtrmac/gpgme/unset_agent_info_windows.go, vendor/modules.txt
=> Bug 1802881:  bump(github.com/mtrmac/gpgme): v0.1.2 

pkg/cli/rsync/rsync.go
=> Fix oc rsync help

pkg/cli/kubectlwrappers/wrappers.go
=> Bug 1809028: replace kubectl with oc in wait's help

Makefile
This is a manual cherry-pick of #250 
/assign @mfojtik
=> Bug 1790954: fix version ldflags

pkg/cli/set/volume.go
This is a followup to #332.
/assign @smarterclayton
=> Remove dead code

pkg/cli/debug/debug.go
The addition of the new flag masked the existing check. Use the new
logic and also exit early (at the correct point).
=> debug: The `--dry-run` flag does not work with debug

Makefile
=> Add make oc target

pkg/cli/requestproject/request_project.go
=> Bug 1821356: fix comment

pkg/cli/admin/policy/modify_roles.go
=> Bug 1827061: add missing newline

pkg/helpers/groupsync/groupsyncer.go
=> Bug 1802719: oc adm groups sync  IsQueryOutOfBoundsError warning,not error

pkg/cli/rollout/rollout.go
=> Bug 1780447: replace kubectl with oc in oc rollout restart help

pkg/cli/serviceaccounts/create_kubeconfig.go
`--context` flag is currently ignored by `oc sa create-kubeconfig`. Although, `oc options` claims all oc options can be passed to any command. Although, it does not say anything about every command honoring the options, in case of `--context`, it makes sense to have `oc sa create-kubeconfig` honor it.
=> bug 1827463: oc sa create-kubeconfig: respect --context flag

pkg/cli/project/project.go, pkg/cli/status/status.go
Backporting:
- https://github.com/openshift/oc/pull/413
- https://github.com/openshift/oc/pull/431
=> bug 1838614: Backport oc status project 4.5 changes

pkg/cli/rsh/rsh.go
=> Bug 1839631: fix validation code for arguments passed

Makefile, go.mod, go.sum, vendor/k8s.io/kubectl/pkg/drain/drain.go, vendor/modules.txt
/assign @sallyom 
This brings in https://github.com/kubernetes/kubernetes/pull/87361
=> [release-4.4] Bug 1835739: Fix oc drain to ignore daemonsets and others 

pkg/cli/admin/release/info.go
=> Fix flag name in the error when invoking oc adm release info

pkg/cli/kubectlwrappers/wrappers.go, pkg/cli/newapp/newapp.go
This has fixes for:
https://bugzilla.redhat.com/show_bug.cgi?id=1841005
https://bugzilla.redhat.com/show_bug.cgi?id=1840591
=> Bug 1841005: fix new-app help to mention deployment and/or dc

pkg/cli/admin/policy/modify_roles.go
The rolebinding modification code was attempting to update all roles
containing the specified role instead of just updating roles that need
updating.
The above would result in printing all rolebindings containing the
specified role if formatting flag was specified and could result
in errors being printed in case the formatting flag was not specified
but the specified role was contained in one of the system rolebindings.
Fixed by passing only the rolebindings that needed changing to the
updating code.
=> Bug 1629524: only print/update changed rolebindings when removing roles

pkg/cli/admin/inspect/inspect.go, pkg/cli/admin/inspect/pod.go, pkg/cli/admin/inspect/port_forward.go, pkg/cli/admin/inspect/util.go, pkg/cli/admin/mustgather/mustgather.go
This enables us to have the filtering page embedded in them.
=> add complete event json to inspect and must-gather results

pkg/cli/image/extract/extract.go, pkg/cli/image/info/info.go
=> Bug 1817145: Improve 'oc adm release info|new' error when given release image does not exist

README.md
/assign @sallyom 
If you think of something worthy adding on top of that, feel free to open a follow-up.
=> Write a proper readme

pkg/cli/login/loginoptions.go, pkg/cli/project/project.go, pkg/helpers/describe/projectstatus.go, pkg/helpers/errors/login.go
This reverts commit f7d2755ed11135de6f40f82ec24ad91a4fd71fad.
=> Bug 1849983: allow switching project even to users outside self-provisioner role (revert)

go.mod, go.sum, vendor/golang.org/x/crypto/openpgp/armor/armor.go, vendor/golang.org/x/crypto/openpgp/elgamal/elgamal.go, vendor/golang.org/x/crypto/ssh/terminal/terminal.go, vendor/golang.org/x/crypto/ssh/terminal/util_windows.go, vendor/modules.txt
=> [release-4.4] Bug 1808174: bump(golang.org/x/crypto|net|sys)

pkg/cli/admin/mustgather/mustgather.go
Looks like these parameters were misplaced.
/assign @tnozicka
=> Bug 1854388: Revert interval and timeout in mustgather so they make sense

go.mod, go.sum, vendor/github.com/mtrmac/gpgme/.appveyor.yml, vendor/golang.org/x/crypto/ed25519/ed25519.go, vendor/golang.org/x/crypto/ed25519/ed25519_go113.go, vendor/golang.org/x/crypto/openpgp/armor/armor.go, vendor/golang.org/x/crypto/openpgp/elgamal/elgamal.go, vendor/golang.org/x/crypto/openpgp/packet/encrypted_key.go, vendor/golang.org/x/crypto/openpgp/packet/private_key.go, vendor/golang.org/x/crypto/ssh/terminal/terminal.go, vendor/golang.org/x/crypto/ssh/terminal/util_windows.go, vendor/modules.txt
=> [release-4.3] Bug 1808221: bump(golang.org/x/crypto|net|sys)

pkg/cli/image/extract/extract.go
The layer extraction functionality requires absolute paths for creating
symlinks. The input normalization process should turn target paths into
absolute paths. Note that if you are extracting an absolute symlink, we
do not remap it (etc/mtab -> /proc/self/mount, when extracted to /tmp/a,
would be /tmp/a/etc/mtab -> /proc/self/mount).
Bug was `oc image extract IMAGE` (which defaults to `--path /:.`) resulting
in an error:
```
error: unable to extract layer sha256:4f88af2d484bc1dc514fb5fb80259c3b8989127ca8c75fc58b4b85e98550835d from quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:f3ba975408deb1df7b4c0b8a3617e339d91e45c08ace87fe529707692df25a9a: invalid symlink "etc/mtab" -> "/proc/self/mounts"
```
=> extract: Make destination paths to absolute to avoid symlink errors

pkg/cli/admin/inspect/event_filter_html.go, pkg/cli/admin/inspect/util.go
This improves the event viewer  with:
* Advanced Search
* Filterable columns
* Fixed event time (if LastSeen is nil, use CreatedTimestamp)
* Fixed fonts
* Sort on each column
=> inspect: improve html event viewer

pkg/cli/debug/debug.go
=> debug: fix dry-run flag parsing

pkg/cli/requestproject/request_project.go
what goes around comes around @adambkaplan 
https://github.com/openshift/oc/pull/170#discussion_r348680799
https://github.com/openshift/oc/pull/170#discussion_r348683479
https://github.com/openshift/oc/pull/170#discussion_r466505686
/assign @adambkaplan 
=> Bug 1866597: use a fips compliant, but officially supported OCP template, with new-project message

pkg/cli/image/manifest/manifest.go, pkg/cli/image/mirror/mirror.go
=> Bug 1859452: Improve help menu when 'oc image mirror' and multi-arch images

pkg/cli/admin/mustgather/mustgather.go
Move `gather` container from init containers into containers so the pod does not stay in `Pending` state until gather container is finished. Otherwise, `KubePodNotReady` alert gets triggered.
Once the gathering phase is finished, must-gather pod drops to NotReady state since `gather` container terminates:
```
NAME                READY   STATUS     RESTARTS   AGE
must-gather-sr295   1/2     NotReady   0          4m18s
```
Having a pod in `NotReady` status might still be better than having it in `Pending`. The copy phase should take less than the gathering one (depending on the network bandwidth).
=> bug 1805891: must-gather: move gather init container under containers

pkg/cli/debug/debug.go
When a defaultNodeSelector is configured in the scheduler, `oc debug node` fails
if the node to debug does not have the matching labels.  To fix this, with
`oc debug node` create a temporary namespace for the debug pod that has an empty
`openshift.io/node-selector: ""` annotation.  Only create the debug ns if
the user hasn't explicitly set the debug-pod namespace with
`--to-namespace` or `--namespace|-n`.
=> Bug 1812813: oc debug node: create debug namespace with empty node-selector annotation

pkg/cli/requestproject/request_project.go
=> Bug 1873275: fix kubectl example

pkg/cli/admin/inspect/inspect.go, pkg/cli/admin/inspect/inspect_test.go, pkg/cli/admin/mustgather/mustgather.go
=> Bug 1798138: add timestamps marking start and end for must-gather and inspect

go.mod, go.sum, vendor/k8s.io/kubectl/pkg/describe/describe.go, vendor/modules.txt
Picking upstream https://github.com/kubernetes/kubernetes/pull/93687
=> bug 1861683: Bump k8s.io/kubectl to pick https://github.com/openshift/kubernetes-kubectl/pull/30

Makefile
/assign @damemi 
you missed one :wink:
=> Bug 1874056: bump deps version'

pkg/cli/admin/mustgather/mustgather.go
- Try to parse the image reference before creating the must-gather pod
- Treat ImagePullBackOff and InvalidImageName the same as ErrImagePull
Bug 1840643
Signed-off-by: Yuval Turgeman <yturgema@redhat.com>
=> Bug 1840643: handle pull errors in must-gather

pkg/cli/admin/mustgather/mustgather.go
=> Bug 1883171: add audit gathering example to help page

pkg/cli/admin/inspect/inspect.go, pkg/cli/admin/inspect/resource.go, pkg/cli/admin/inspect/util.go
This reverts commit 2c5771467d0ec21bad19c0c1bcb006a7c6f35377.
=> Bug 1883635: Revert "run inspect in parallel"

pkg/cli/admin/mustgather/mustgather.go
Signed-off-by: Yuval Turgeman <yturgema@redhat.com>
=> must-gather: fixed typo when using a plug-in image

pkg/cli/logout/logout.go
=> Refactor deletion of hashed session token on user logout

go.mod, go.sum, vendor/k8s.io/kubectl/pkg/cmd/create/create_job.go, vendor/modules.txt
=> [release-4.5] Bug 1884580: Set appropriate owner references when creating a job from cronjob

pkg/cli/login/loginoptions.go
=> Bug 1888657: set command name for LoginOptions

go.mod, go.sum, vendor/k8s.io/kubectl/pkg/cmd/create/create_job.go, vendor/modules.txt
=> [release-4.4] Bug 1884569: Set appropriate owner references when creating a job from cronjob

pkg/cli/admin/release/extract.go
=> Bug 1853116: write to files instead of stdout

pkg/helpers/describe/describer.go
=> Bug 1893645: account for nil in LastTransitionTime in route status

pkg/cli/admin/release/mirror.go
When oc adm release mirror is passed both --to and --to-release flags, only the --to value is used to generate ICSP. This PR adds the --to-release mirrors to the generated ICSP.
=> Bug 1878823: 'oc adm release mirror' add --to-release mirrors to generated ICSP

pkg/cli/admin/release/mirror.go
Retrieve architecture from image release information and use in naming.
=> Bug 1878972: adm release mirror: add architecture information

pkg/cli/image/append/append.go
=> Bug 1905404: fix append example

pkg/cli/debug/debug.go, pkg/helpers/conditions/conditions.go
The logic for waiting for the container to be ready before starting
the attach did not correctly take into account init containers.
The logic in PodContainerRunning is refactored to:
1. Remove the early exit if the pod is pending (pod will be pending
for init containers)
2. Instead of exiting when a container is waiting, print a message
to stderr that indicates what container has not been loaded. The
exit is inappropriate because a transient pull error can happen
at any time.
3. Only check init containers or the requested container name for
waiting - it's irrelevant if another container is 'waiting' when
debugging
4. When the pod is terminal, check init containers and regular
containers and report any container with exit code != 0, not just
regular containers
5. Stop treating unknown pod …
=> Bug 1909289: Should be able to debug an init container

pkg/cli/rollback/rollback.go
=> Bug 1910840: fix help for rollback

pkg/cli/cli.go, pkg/cli/kubectlwrappers/wrappers.go
=> Bug 1908697: use wrapper for diff command

pkg/cli/admin/prune/deployments/deployments.go
=> Bug 1911487: make deployment config explicit for prune deployments

pkg/cli/cli.go
=> Bug 1899575: bump discovery burst to 250

pkg/cli/admin/node/logs.go
=> Bug 1916621: fix oc adm node-logs examples

go.mod, go.sum, pkg/cli/cli.go, vendor/k8s.io/cli-runtime/pkg/genericclioptions/config_flags.go, vendor/modules.txt
Cherry-pick of https://github.com/openshift/oc/pull/696 and https://github.com/openshift/oc/pull/648
/assign @ingvagabund
=> [release-4.6] Bug 1906332: bump discovery burst to 250

pkg/cli/login/login.go
=> Bug 1920427: drop information about prompt for oc login

Makefile, hack/generate-versioninfo.sh, oc.spec
This is a cherry-pick of https://github.com/openshift/oc/pull/623 and https://github.com/openshift/oc/pull/629 for 4.6.
=> [release-4.6] Bug 1891892: Create Windows version information

pkg/cli/requestproject/request_project.go
=> Bug 1919862: fix message after oc new-project

pkg/cli/image/mirror/mirror.go
This commits adds a retry logic when copying a blob from one registry to another in case of "REFUSED_STREAM" error. I have spent a considerable amount of time trying to replicate this behavior together with @hongkailiu without success.
We could see the REFUSED_STREAM error a few times when running the `oc image mirror` command using an image based on the master branch of this repository but we were not so lucky when it comes to see the same error using an image based on this very same branch. 
If it is worthy I can assure the command still works after these changes but I can not assure this will fix the issue, if we manage to get this in we can validate if it actually works by examining the output for some [jobs](https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/branch-ci-openshift …
=> Bug 1907421: Implementing retries during for image mirror

pkg/cli/idle/idle.go
Annotate the service with idle information as we currently do for
endpoints.
We choose to additionally annotate the service because the router in
4.6 has moved to watching endpointslices only. We don't annotate
endpointslices as they are managed by the endpointslice controller and
that doesn't propgagate annotations. The router now only checks the
service to see if it has been idled.
Previous discussion for propgagating annotations in endpointslices:
https://github.com/kubernetes/kubernetes/pull/98379
=> Bug 1900989: idle: also annotate the service

pkg/cli/admin/inspect/inspect.go, pkg/cli/admin/inspect/inspect_test.go, pkg/cli/admin/mustgather/mustgather.go
=> [release-4.5] Bug 1920676: add timestamps marking start and end for must-gather and inspect

pkg/cli/image/serve/serve.go
This is a repeat PR to squash from #674
=> add simple debug for image serve

pkg/helpers/describe/describer.go
This commit resolves
https://bugzilla.redhat.com/show_bug.cgi?id=1925236.
pkg/helpers/describe/describe.go: If a route specifies
a value (integer or string type) for Spec.Port, the router only
serves endpoints that correspond to that port. In this case, `oc
describe route` should output only the endpoints corresponding to
Spec.Port, as to avoid implying that the router is serving more
backend endpoints than it should be.
This change only affects `oc describe route`.
=> Bug 1925236: RouteDescriber: Filter endpoints on route.Spec.Port

pkg/cli/debug/debug.go
The command `oc debug` and `oc debug --image=foo` should be allowed to start foo exactly as if you ran `oc debug istag/foo:latest` or ran `oc debug node/bar`. This allows us to have a minimal command for scenarios where you want to test the
image in the debug setup.
=> Bug 1920024: Allow debug to start with a single `--image` argument

pkg/cli/admin/release/new.go
The code that looks at spec tags when building a new release is
incorrectly assuming that a spec tag trumps the status tag, when in
fact the spec tag generation must be compared to the status tag
generation. Rearrange the code so that spec tags are skipped if the
spec tag is older than the status tag, but still errors if we are
waiting for a spec tag to be imported.
This may change behavior of OpenShift release creation in developer
environments, but the actual release tooling will now match the
behavior of the release. We were not seeing this bug impact us in
the release controller because the release controller clones the
image stream prior to creating a release, so spec/status are always
equal. This currently blocks users from creating releases off ocp/4.8
because there are spec tags …
=> Bug 1937020: `oc adm release new` should look at image stream status tags

contrib/completions/bash/oc, contrib/completions/zsh/oc, pkg/cli/admin/top/imagestreams.go
=> Bug 1949820: Add an alias to imagestreams in top command

pkg/cli/admin/createerrortemplate/create_error_template.go
=> Bug 1942915: pkg/.../create_error_template: fix error page template

pkg/cli/admin/verifyimagesignature/manifest.go, pkg/cli/image/manifest/manifest.go, pkg/cli/registry/info/info.go, pkg/cli/registry/login/login.go, pkg/helpers/newapp/newapptest/newapp_test.go
=> Bug 1968515: set User-Agent when talking with registries

pkg/helpers/newapp/newapptest/newapp_test.go
React to changes from https://github.com/openshift/ruby-hello-world/pull/125
=> Update ruby-hello-world images

pkg/helpers/kubeconfig/smart_merge.go, pkg/helpers/newapp/newapptest/newapp_test.go
Manual cherry-pick of #692 and #860 to fix unit tests.
=> [release-4.7] Bug 1963784: Preserve AuthInfo when switching projects 

pkg/cli/admin/verifyimagesignature/manifest.go, pkg/cli/image/manifest/manifest.go, pkg/cli/registry/info/info.go, pkg/cli/registry/login/login.go
Manual cherrypick of #841 due to conflicts in #849.
/assign @ingvagabund
=> [release-4.6] Bug 1971561: set User-Agent when talking with registries

pkg/cli/image/archive/archive.go
Manual cherry-pick #835
/assign @atiratree
=> [release-4.6] Bug 1969929: exclude security during exctraction

pkg/cli/admin/groups/sync/sync.go
When writing out a list of Group objects, the resulting YAML was unusable and causing issues. Reverting back to an UnstructuredList should resolve issues surrounding missing resource fields.
=> Bug 1989391: Revert to UnstructuredList to fix yaml output

pkg/cli/admin/catalog/mirror.go
With the introduction of file-based configs (aka declarative config), the OLM project is deprecating the use of sqlite-based catalogs.
The `oc adm catalog mirror` tool supports mirroring from sqlite-based images, so we need to log a deprecation warning to inform users that a future release of `oc` will remove support for sqlite-based images.
See https://github.com/operator-framework/enhancements/blob/master/enhancements/declarative-index-config.md#deprecations
Related PR for `opm`: https://github.com/operator-framework/operator-registry/pull/760
=> Bug 1996881: adm catalog mirror: log deprecation message when sqlite-based catalog is in use

pkg/cli/admin/upgrade/upgrade.go
Signed-off-by: Lalatendu Mohanty <lmohanty@redhat.com>
=> Bug 1992680: pkg/cli/admin/upgrade: Changing "Updates" string to "Available Updates"

OWNERS_ALIASES
Replace ecordell with kevinrizza
=> Add kevinrizza as catalog-approver

pkg/cli/startbuild/startbuild.go, pkg/cli/startbuild/startbuild_test.go
In case of a binary build, we want to create for resources `BuildConfig` is expecting to exist, before creating the `Build` object.
This way, we'll save cluster resources by not creating objects that are destined to fail.
=> Bug 1977414: check BuildConfig Secrets and ConfigMaps before start-build creates a build

pkg/cli/admin/policy/policy.go
Fixes https://github.com/openshift/client-go/issues/197
=> Drop policy mentions in oc adm policy help

pkg/cli/admin/policy/modify_roles.go, pkg/cli/admin/policy/policy.go, pkg/cli/admin/policy/remove_from_project.go, pkg/cli/admin/policy/review.go, pkg/cli/admin/policy/subject_review.go, pkg/cli/policy/policy.go
=> Fix docs for oc adm policy add-role-to-user vs oc policy add-role-to-user

pkg/cli/admin/mustgather/mustgather.go
This PR addresses two issues: 
- the bug mentioned in the title, i.:e currently we can't run packet captures using must-gather because we are missing the proper security capability to do so. I am limiting the capability to `CAP_NET_RAW` which will allow a user to perform packet captures, while also not granting too broad permissions.  
- nits from my previous PR: https://github.com/openshift/oc/pull/850 
=> Bug 2020377: add linux capability for host network packet captures

pkg/cli/image/manifest/dockercredentials/auth_resolver.go, pkg/cli/image/manifest/dockercredentials/auth_resolver_test.go, pkg/cli/image/manifest/dockercredentials/credential_store_factory.go, pkg/cli/image/manifest/manifest.go, pkg/cli/registry/login/login.go, pkg/helpers/image/helpers.go
followup to https://github.com/openshift/oc/pull/893
=> fix registry-config messages and imports

README.md
=> Fix documentation issue #937

pkg/cli/admin/mustgather/mustgather.go
This reverts #942 
cc @apoorvajagtap
This reverts commit b4ac3d30b5524f0e84774dbfc2663102b0fba8ec.
This reverts commit 5ad360cf7cc3321afdd35544af2aea1db48c2172.
=> Bug 2033751: Revert "Modified MG pod tolerations"

pkg/cli/registry/login/login.go
fixes https://github.com/openshift/oc/issues/985
- allow empty files in oc registry login
- return support for stdout output in oc registry login 
- add deprecation notices
@soltysh although, this is a regression I would prefer having less validations and passing this change in behaviour / regression to the user. Reasons:
- less complexity
- same behaviour as podman
=> Bug 2036940: allow empty files and stdout in oc registry login

.gitignore
This will ignore any VSCode-specific configuration files from accidentally being added to source control.
=> Ignore VSCode files

pkg/cli/admin/catalog/mirror.go, pkg/cli/admin/catalog/mirror_test.go
Problem: It is possible to set a --max-icsp-size for the oc adm
catalog mirror command that is too small to create a valid icsp.
Solution: If a user sets the max icsp size to less than 1, return
an error. If a single mirror entry exceeds the length of the
provided icsp size limit, return an error.
=> Bug 1972962: Add validation for max-icsp-size flag

pkg/cli/admin/upgrade/upgrade.go
Signed-off-by: Lalatendu Mohanty <lmohanty@redhat.com>
=> Bug 2044140: Updated the error message to include the suggestion

pkg/cli/debug/debug.go
=> Bug 2046319: improve error message for debug

pkg/cli/admin/inspect/inspect.go
=> Show managedFields in inspect

pkg/cli/admin/release/new.go
This PR drops unused 3 methods: 
- `findStatusTagEvents`
- `findStatusTagEvent`
- `findSpecTag`
and replaces that single instance with a pre-existing helper from library-go.
/assign @smarterclayton @wking
=> Remove unused methods and re-use pre-existing ones where needed

.ci-operator.yaml, images/cli-artifacts/Dockerfile.rhel, images/deployer/Dockerfile.rhel, images/recycler/Dockerfile.rhel, images/tools/Dockerfile
Replaces https://github.com/openshift/oc/pull/1040/ and https://github.com/openshift/oc/pull/1045/
=> Update all images to be consistent with ART

pkg/cli/debug/debug.go
=> Add support for batch/v1 CronJob

pkg/cli/admin/upgrade/upgrade.go
Picking #1041 and #1050 back to 4.10.
=> Bug 2051267: pkg/cli/admin/upgrade: Mention --allow-explicit-upgrade next step when appropriate

pkg/cli/admin/inspect/inspect.go, pkg/cli/admin/mustgather/mustgather.go, pkg/cli/admin/mustgather/summary.go
This is manual pick of https://github.com/openshift/oc/pull/1051 and https://github.com/openshift/oc/pull/1013
/assign @deejross 
/cc @deads2k
=> [release-4.10] Bug 2049427: Enhancing the output provided when backup collections are attempted

pkg/cli/version/version.go
In clusters with hosted control planes, neither the OpenShift
apiserver nor its operator are present inside the cluster. Switching the
`oc version` command to work with the ClusterVersion resource instead of
the openshift-apiserver ClusterOperator resource makes it possible for
`oc version` to work with this topology as well.
=> Obtain OpenShift version from ClusterVersion resource

pkg/cli/admin/inspect/inspect.go, pkg/cli/admin/mustgather/mustgather.go, pkg/cli/admin/mustgather/summary.go
This is manual pick of https://github.com/openshift/oc/pull/1051 and https://github.com/openshift/oc/pull/1013
/cc @deads2k
=>  [release-4.9] Bug 2051944: Enhancing the output provided when backup collections are attempted

pkg/cli/admin/mustgather/mustgather.go, pkg/cli/admin/mustgather/mustgather_test.go
One of the OSD SRE teams (MT-SRE) has a requirement that custom `must-gather` images must be run for troubleshooting managed services on OSD. The `must-gather` scripts run against namespaces in which we are admins, but the `oc adm must-gather` command requires dynamic generation of temporary namespaces/clusterRoleBindings to run `must-gather` pods. This is not possible with _namespace scoped_ admin access so this PR seeks to add an optional `namespace` parameter to the `oc adm must-gather` command so that users can specify an existing namespace for `must-gather` pods to run.
=> Enable using existing namespace for must-gather operations

pkg/cli/admin/inspect/inspect.go
Purpose of inspection is to get whatever data it can in best effort.
In case of some resources are not found, inspect still can continue
for other resources.
This PR handles isnotfound error for resources and continues
to inspect. After inspection is completed, it prints error message
to warn user about non-existed resources.
=> Bug 2086459: Continue inspection when some resources are not found

pkg/cli/project/project.go
manual cherry-pick of https://github.com/openshift/oc/pull/1125
=> [release-4.10] Bug 2084429: Fix project command auto completion

pkg/cli/admin/mustgather/mustgather.go
When must-gather pod exits with the value other than 0, it should
pass to terminal and `echo $?` should show that.
This PR handles exit errors and returns `CodeExitError` to achieve that.
=> Bug 2040654: Pass pod exit error codes to user

pkg/cli/admin/release/extract.go, pkg/cli/admin/release/extract_tools.go, pkg/cli/admin/release/mirror.go
=> Bug 2090266: add --filter-by-os support in oc adm release extract and linux/amd64 for getting IS during mirror

pkg/cli/admin/mustgather/mustgather.go
/assign @deejross @atiratree 
/cc @kasturinarra
=> Bug 1999891: bubble errors which happen prior to collection to BackupGathering

Makefile
=> Bug 2090692: fix version from 1.24.0 beta to 1.24.1

pkg/cli/admin/release/extract.go, pkg/cli/admin/release/extract_tools.go, pkg/cli/admin/release/info.go, pkg/cli/image/extract/extract.go
Replaces #1165
/assign @ardaguclu 
@zaneb fyi
=> Bug 1823143: add --icsp-file option to adm release subcommands

pkg/cli/admin/release/new.go
=> Bug 2096855: extract linux/amd64 to read release metadata

pkg/cli/admin/release/new.go
In order to default base image, base digest set in `io.openshift.release.base-image-digest` annotation is used. However, in some cases, this digest can be invalid and can cause failing of `release new` command. Because base digest does not refer to any valid image can be used as base image.
For these cases, we can safely use `from-release` image as base image. This PR adds this.
=> Bug 2100702: Use from-release as based image when base digest is invalid

pkg/cli/login/loginoptions.go
In order to fix that bug https://bugzilla.redhat.com/show_bug.cgi?id=1880865, https://github.com/openshift/oc/pull/746 patch was proposed. However, it was reverted in https://github.com/openshift/oc/pull/757 because of failing in here https://github.com/openshift/oc/blob/f7835631278b03e4388f65145b56e1fd93bf4e37/vendor/k8s.io/client-go/transport/transport.go#L64-L66
The reason of failure is `CAFile` and `CAData` needs to be empty, if `Insecure` flag is set which has already been tackled by here https://github.com/openshift/oc/blob/f712166787e5cce66492d9c6434dfc7d14808cdb/pkg/cli/login/loginoptions.go#L152-L154
To fix the main bug, this PR(continuation of https://github.com/openshift/oc/pull/746) sets `CAFile` and `CAData` empty, if `--insecure-skip-tls-verify` flag is set to true.
=> Bug 1880865: Avoid TLS cert checking when login with --insecure-skip-tls-verify=true

pkg/cli/image/info/info.go
Currently if the passed image is multiarch image, we are throwing error
to force user to use `--filter-by-os` flag with the listed image manifests in
that error.
This PR introduces new `show-multiarch` flag. `oc image info --show-multiarch`
command will continue working exactly the same way as now for single arch images.
However, this command(with new flag) will also show informations of platform specific images
embedded in multiarch image.
This flag supports json and default printing and if the image is multiarch image,
result will be in json array format if output is json.
=> Bug 2111537: (image info): Introduce show-multiarch flag

pkg/cli/admin/inspect/pod.go
Logs for normal pods are located under /var/log/pods/${POD_NAMESPACE}_${POD_NAME}_${POD_UID}.
Logs for static pods are located under /var/log/pods/${POD_NAMESPACE}_${POD_NAME}_${POD_HASH}.
=> OCPBUGS-613: oc adm logs: generate proper path for static pods

go.mod, go.sum, vendor/k8s.io/cli-runtime/pkg/genericclioptions/config_flags.go, vendor/modules.txt
/assign @ardaguclu @ingvagabund
=> OCPBUGS-1638: Increase default value of cache TTL to 6 hours

pkg/cli/extract/extract.go
Currently, `oc extract` command returns error, if target directory is not existed. This PR creates all nested directories prior to extract data.
This will easen usage of `oc extract` command.
=> Bug 2033167: oc extract: Create target directory if not exist

pkg/cli/admin/release/new.go
Add support for `--next` flag like `--previous` while creating new releases. 
This will enable us to not have to repromote release payloads if release team bump a release
Checks done:
=> add support for --next flag in oc adm release new

pkg/cli/admin/inspect/resource.go
Currently, `oc inspect` obtains related objects by extracting them from `.status.relatedObjects` field in resources. However, `Validating|MutatingWebhookConfigurations` do not contain this field, instead they are storing services in `webhook.clientConfig.service` field. If services are in another namespace, `oc inspect` does not inspect those namespaces.
This PR adds ability to gather namespaces in which webhook services are running. That will shed more light on troubleshooting.
=> Bug 2000554: oc inspect: Also gather namespaces in which webhook services are running

go.mod, go.sum, vendor/k8s.io/kubectl/pkg/cmd/debug/debug.go, vendor/k8s.io/kubectl/pkg/cmd/run/run.go, vendor/modules.txt
=> Bug 2015119: bump(k8s.io/kubectl) to pick up k/k#110764

pkg/cli/cli.go
This PR carries the fix in this upstream PR https://github.com/kubernetes/kubernetes/pull/105141
=> Do not try to load plugins for cobra commands

.ci-operator.yaml, go.mod, images/cli-artifacts/Dockerfile.rhel, images/cli/Dockerfile.rhel, pkg/cli/admin/mustgather/summary.go, pkg/cli/admin/node/logs.go, pkg/cli/admin/policy/modify_roles.go, pkg/cli/admin/release/mirror.go, pkg/cli/admin/release/signature.go, pkg/cli/deployer/strategy/support/lifecycle.go, pkg/cli/image/manifest/dockercredentials/auth_resolver.go, pkg/cli/newapp/newapp.go, pkg/cli/rsync/pathspec.go, pkg/helpers/describe/projectstatus.go, pkg/helpers/graph/appsgraph/analysis/dc.go, pkg/helpers/graph/kubegraph/analysis/hpa.go, pkg/helpers/image/credentialprovider/config.go, pkg/helpers/newapp/app/sourcelookup.go, pkg/helpers/newapp/docker/dockerfile/instructions.go, pkg/helpers/source-to-image/timeout/timeout.go, pkg/helpers/term/terminal.go, pkg/helpers/tokencmd/basicauth.go
=> Bump go to 1.19 in go.mod

OWNERS_ALIASES
=> Promote ardaguclu to oc approver

pkg/cli/deployer/strategy/rolling/rolling.go, pkg/cli/deployer/strategy/rolling/rolling_test.go
While chasing a another PR (https://github.com/openshift/kubernetes/pull/1393), I found a repeatable problem with 
> error: couldn't assign source annotation to deployment deployment-simple-2: Operation cannot be fulfilled on replicationcontrollers "deployment-simple-2": the object has been modified; please apply your changes to the latest version and try again
error: couldn't assign source annotation to deployment deployment-simple-2: Operation cannot be fulfilled on replicationcontrollers "deployment-simple-2": the object has been modified; please apply your changes to the latest version and try again
Using server-side apply we can avoid the conflict. I haven't yet figured out if or how the original PR is causing conflicts, but this is a net-good either way.
=> switch the deployer pod to use apply client to avoid conflicts

pkg/cli/admin/mustgather/mustgather.go
This is manual cherrypick of this https://github.com/openshift/oc/pull/1187
=> [release-4.10] OCPBUGS-3968: set proper pod security ns labels

pkg/cli/admin/mustgather/mustgather.go
This is manual cherrypick of this https://github.com/openshift/oc/pull/1187
=> [release-4.9] OCPBUGS-3969: set proper pod security ns labels

pkg/cli/admin/mustgather/mustgather.go
This is manual cherrypick of this https://github.com/openshift/oc/pull/1187
=> [release-4.8] OCPBUGS-3970: set proper pod security ns labels

pkg/cli/debug/debug.go
/assign @sanchezl @ardaguclu 
This will unblock the rebase PR, but I think @ardaguclu we need to revisit this bit of code to be a bit smarter when dealing with failures from creating debug pods. This change is coming from k8s 1.26, so I'd suggest to re-visit it once 1.26 lands. 
1.26 PR: https://github.com/openshift/kubernetes/pull/1432
=> Update errors when debug pod fails

pkg/cli/admin/mustgather/mustgather.go
Currently, when user passes `--run-namespace` flag, must-gather pod becomes stale and is not removed after it completes.
The reason is that `copy` container in the pod is set sleeping infinite, thus pod never falls into `completed` status to be collected by garbage collector.
One option is setting to a precise duration for sleeping and wait until garbage collector removes pods in `completed` status. But that also means that we will delay pod removal to a certain time which is presumably long(2 hours maybe?).
Other option is removing the must-gather pod manually.
This PR applies second option because we know when task is completed and there might be no need to delay this removal.
=> OCPBUGS-5010: Remove must-gather pod after it completes when explicit namespace is used

Makefile, hack/verify-kube-version.sh
This PR changes the kube version to correct version.
=> OCPBUGS-6011: Fix kube version from 1.24.1 to 1.25.2

pkg/cli/requestproject/request_project.go
/assign @ardaguclu 
ref https://groups.google.com/a/kubernetes.io/g/dev/c/kgWu5q6h8fs/m/ANmnNAatAQAJ
=> Use registry.k8s.io and update image version

tools/gendocs/gen_openshift_docs.go, tools/gendocs/gendocs/gendocs.go, tools/gendocs/gendocs/microshift.go
/assign @ardaguclu @ShaunaDiaz
=> Microshift command docs

pkg/cli/admin/catalog/mirror.go, pkg/cli/admin/catalog/mirror_test.go
story: https://issues.redhat.com/browse/OCPNODE-1581
This PR migrates oc adm catalog mirror command to use IDMS: mark icsp flags as deprecated.
add corresponding flags for idms
oc adm catalog mirror generate ImageContentSourcePolicy file currnetly. Update the comment to generate ImageDigestMirrorSet yaml file.
After this patch:
```
$ ./oc adm catalog mirror -a=config.json --insecure=true --max-icsp-size=19000 --icsp-scope=repository  localhost:5000/olm-mirror/my-redhat-operator-index:v4.7 quay.io/qiwanredhat/my-redhat-operator-index:v4.7
Flag --max-icsp-size has been deprecated, support for it will be removed in a future release. Use --max-idms-size instead.
Flag --icsp-scope has been deprecated, support for it will be removed in a future release.Use --idms-scope instead.
```
generated …
=> [OCPNODE-1581] adm catalog mirror generates idms manifest

pkg/helpers/groupsync/grouplister.go
=> OCPBUGS-11123: oc adm groups sync: fix the annotation key

pkg/helpers/groupsync/grouplister.go
=> OCPBUGS-11123: oc adm groups sync: all groups: print warning before caching

pkg/helpers/newapp/app/dockerimagelookup.go
Discussed with @Prashanth684 and @pravin-dsilva 
Prashanth identified the code is unable to see the manifest listed config. 
We pick off the first entry in the manifest, and pick the exposed port. 
Added mappings per discussion with @Prashanth684
=> OCPBUGS-12793: adds a mapping for exposed ports to DockerConfig when manifest listed

pkg/cli/clusteroperator/pernodepod/runtime.go
=> pernodepod: percent works like this

images/cli/Dockerfile.rhel
=> [4.10] Use rhel 8 builder to match the base image

pkg/cli/admin/release/extract_tools.go
@jupierce @soltysh @cgwalters ptal.
=> Add extraction for rhel7 oc

pkg/cli/observe/observe.go
Correct incorrect command in observe command
=> Correct incorrect command in observe command

images/cli-artifacts/Dockerfile.rhel, images/cli/Dockerfile.rhel
@jupierce @soltysh @deads2k 
Backport of https://github.com/openshift/oc/pull/1489 and https://github.com/openshift/oc/pull/1488
=> [4.9] Fix oc builds 

images/cli-artifacts/Dockerfile.rhel, images/cli/Dockerfile.rhel
=> [4.8] Fix oc builds 

images/cli-artifacts/Dockerfile.rhel, images/cli/Dockerfile.rhel
=> [4.7] Fix oc builds 

images/cli-artifacts/Dockerfile.rhel, images/cli/Dockerfile.rhel
=> [4.6] Fix oc builds 

pkg/cli/admin/node/logs.go
=> Fix typo in /var/log folder

pkg/cli/admin/ocpcertificates/regeneratemco/command.go, pkg/cli/admin/ocpcertificates/regeneratemco/rotatecerts.go, pkg/cli/admin/ocpcertificates/regeneratemco/updatesecrets.go
Superceding https://github.com/openshift/oc/pull/1503
=> [release-4.10] OCPBUGS-16060: mcs cert: account for environments that use IP directly

pkg/cli/admin/ocpcertificates/regeneratemco/command.go, pkg/cli/admin/ocpcertificates/regeneratemco/rotatecerts.go, pkg/cli/admin/ocpcertificates/regeneratemco/updatesecrets.go
Doing a manual pick here since the bot-PR doesn't work for 4.11/4.10
=> [release-4.11] OCPBUGS-16059: mcs cert: account for environments that use IP directly

pkg/cli/debug/debug.go
Allows oc debug to be ran against a Windows node. Adds Windows specific fields to the pod spec, if the node is detected to be Windows.
When debugging a Windows node the image option is required as we cannot ship Windows images as part of the OpenShift payload. This means we cannot set a default image, and the user must provide their own.
=> WINC-692: Add Windows node functionality to debug command

pkg/cli/admin/copytonode/command.go, pkg/cli/admin/restartkubelet/command.go, pkg/cli/admin/waitforstable/command.go, pkg/cli/image/mirror/mirror.go
=> OCPBUGS-20500: Fix some commands incorrect examples

pkg/cli/admin/restartkubelet/command.go
=> OCPBUGS-20500: Add directive example to kubelet-restart command

pkg/cli/admin/mustgather/mustgather.go, pkg/cli/registry/login/login.go
/assign @ardaguclu @ingvagabund
=> NO-JIRA: Drop the experimental info for registry login and must-gather commands

pkg/cli/admin/mustgather/mustgather.go
Since must-gather pod has to run on master node(because it requires to gather
information from the critical components, in case worker nodes are not accessible),
must-gather pods should not affect the functionality of the critical components
such as API server, controller manager, etc.
Currently, must-gather pod uses an emptydir to store all gathered information and
`copy` container copies this to local from the same mounted emptydir. However,
in some rare cases, must-gather pod may fill the entire emptydir allocated by
master node and cause issues for the other components residing in master node
also needs to use storage.
This PR introduces a new flag to limit the volume size usage percentage with
respect to the total volume size allocated for must-gather pod. 
This PR adds a new volume …
=> WRKLDS-860: Add volume usage percentage checker script in must-gather's gather container

pkg/cli/admin/inspect/inspect.go, pkg/cli/image/serve/serve.go, pkg/cli/registry/info/info.go, pkg/cli/set/data.go, pkg/cli/set/imagelookup.go
=> WRKLDS-908: Promote some experimental commands, deprecate others

pkg/cli/admin/mustgather/summary.go
/assign @oarribas 
Sample output looks like:
```
Reprinting Cluster State:
When opening a support case, bugzilla, or issue please include the following summary data along with any other requested information:
ClusterID: fc1339d9-8905-4353-ab48-30ba10b308b2
ClientVersion: v4.2.0-alpha.0-2063-g1d4a9af  <- this is new here
ClusterVersion: Stable at "4.15.0-0.nightly-2023-11-25-110147"
...
```
=> NO-JIRA: Add client version in must-gather summary

pkg/cli/admin/upgrade/status/controlplane.go, pkg/cli/admin/upgrade/status/controlplane_test.go, pkg/cli/admin/upgrade/status/examples/4.15.0-ec2-b02-cos-not-annotated-co.yaml, pkg/cli/admin/upgrade/status/examples/4.15.0-ec2-b02-cos-not-annotated-cv.yaml, pkg/cli/admin/upgrade/status/examples/4.15.0-ec2-b02-cos-not-annotated.output, pkg/cli/admin/upgrade/status/examples/4.15.0-ec2-early-co.yaml, pkg/cli/admin/upgrade/status/examples/4.15.0-ec2-early-cv.yaml, pkg/cli/admin/upgrade/status/examples/4.15.0-ec2-early.output, pkg/cli/admin/upgrade/status/status.go
=> OTA-1035: `adm upgrade status` Add control plane update status

pkg/cli/admin/inspect/resource.go
If a custom resource has a `status.relatedObject` list with items that are not `ObjectReference`s, then the `inspect` command would have an error while trying to gather that resource. Now, those invalid items are skipped.
Refs:
- https://issues.redhat.com/browse/ACM-7713
For example, in open-cluster-management.io, we have a ConfigurationPolicy custom resource which is currently un-gatherable via `oc adm inspect`, because its related objects [are not ObjectReferences](https://github.com/stolostron/config-policy-controller/blob/f94c875ae12c0b158be788f0d6cdae737e59b49b/api/v1/configurationpolicy_types.go#L276).
=> ACM-7713: Skip related objects which are invalid

pkg/cli/admin/prune/images/images.go
=> NO-JIRA: oc adm prune images: fix --certificate-authority flag name in validation code

pkg/cli/admin/mustgather/mustgather.go
This needs to be tested with https://github.com/openshift/must-gather/pull/400.
1. Get the code from https://github.com/openshift/must-gather/pull/400
2. Build it:
```
QUAY_USER="fmissi"
podman build -t quay.io/${QUAY_USER}/must-gather -f Dockerfile.rhel7 .
podman push quay.io/${QUAY_USER}/must-gather
```
```
QUAY_USER="fmissi"
oc project openshift
oc import-image my-must-gather --from=quay.io/${QUAY_USER}/must-gather --confirm
```
1. Get the code from this PR
2. Run the must-gather using the new `--since` OR `--since-time` options:
```
go run ./cmd/oc adm must-gather --since-time=2024-01-11T09:00:00Z --image-stream=openshift/my-must-gather:latest
go run ./cmd/oc adm must-gather --since=2h --image-stream=openshift/my-must-gather:latest
```
=> WRKLDS-950: add since and since-time flags to limit log collection on must-gather

pkg/cli/admin/upgrade/status/health.go
This client-side code is early stage experimental work we do mostly to obtain more knowledge about how exactly an eventual API should look like. Some decisions are made without the scrutiny we would give to a proper API. Take notes, in the form of TODOs, of these decisions, so that we remember to revise them when we start working server-side.
=> NO-JIRA: adm update status: add TODOs to remind us to revise early decisions

pkg/cli/admin/mustgather/mustgather.go, pkg/cli/admin/mustgather/mustgather_test.go
This PR is based on the discussions in https://github.com/openshift/enhancements/pull/1487.
=> CNV-37284: Add --all-images flag to must-gather

Makefile
Just use whatever the OS in question sets.
=> Do not force the ancient OS version dist tag.

pkg/cli/admin/copytonode/command.go, pkg/cli/admin/ocpcertificates/certregen/command.go, pkg/cli/admin/ocpcertificates/regeneratemco/command.go, pkg/cli/admin/ocpcertificates/trustpurge/command.go
This PR updates the incorrect examples. Changes in here aligns with the incorrect example findings in https://github.com/openshift/openshift-docs/pull/71213
=> OCPBUGS-29210: Update some commands incorrect examples

pkg/cli/admin/release/info.go
In order to better track which images' kubectl versions need to be bumped, this PR adds
image names into the kubectl version mismatch warning message in addition to the version list.
Output;
```sh
$ ./oc adm release info registry.ci.openshift.org/ocp/release:4.16.0-0.ci-2024-03-04-212119
warning: multiple versions reported for the kubectl: 1.29.1 (cli, cli-artifacts, deployer, tools), 1.28.2 (must-gather), 1.29.0 (network-tools)
```
=> OCPBUGS-30244: Add images mismatching kubectl version into warning to track

pkg/cli/idle/idle.go
In the past, oc idle command annotates the **endpoint** resource by modifying it after marking the deployments (or deploymentconfigs or replicasets) as idled.
However, same behavior can be satisfied by annotating the **service** resource (that was added by https://github.com/openshift/oc/pull/720) and this PR removes the endpoint resource modification which is already an unwanted behavior.
=> WRKLDS-1076: oc idle: Remove redundant endpoint resource modification

go.mod, go.sum, pkg/cli/admin/release/info_diff_writer.go, vendor/github.com/openshift/library-go/pkg/features/feature_diff_summary.go, vendor/github.com/openshift/library-go/pkg/features/summarizer.go, vendor/github.com/openshift/library-go/pkg/operator/resource/resourceread/admission.go, vendor/modules.txt
This hides the "new disabled field", shortens some text, adds hard line breaks to make a prettier table.
/assign @bradmwilliams
=> make output table slightly easier to read

pkg/cli/admin/upgrade/status/examples/4.14.1-degraded.output, pkg/cli/admin/upgrade/status/examples/4.14.1-paused-worker-pool.output, pkg/cli/admin/upgrade/status/examples/4.14.1-workers-started-updating-multiple-pools-node.yaml, pkg/cli/admin/upgrade/status/examples/4.14.1-workers-started-updating-multiple-pools.output, pkg/cli/admin/upgrade/status/examples/4.15.0-ec2-b02-cos-not-annotated.output, pkg/cli/admin/upgrade/status/examples/4.15.0-ec2-early.output, pkg/cli/admin/upgrade/status/examples/4.15.0-ec2-unavailable-mco-20m.output, pkg/cli/admin/upgrade/status/examples/4.16.0-ec2-control-plane-updated-pdb-prohibits-draining.output, pkg/cli/admin/upgrade/status/status.go, pkg/cli/admin/upgrade/status/workerpool.go
This pull request is a follow up to the https://github.com/openshift/oc/pull/1731
The PR refactors the code for the `oc adm upgrade status` command.
This pull request references https://issues.redhat.com/browse/OTA-1036
=> OTA-1036: `adm update status`: Refactor node status

pkg/cli/admin/mustgather/mustgather.go
Normally, only logs pulled from gather containers have the timestamp added. However, when the must-gather image pull fails, the fallback invokes `oc adm inspect` code directly. Without printing the timestamps. Thus, the code is updated to change this fact.
Before the changes:
```
[must-gather      ] OUT Using must-gather plug-in image: ...
When opening a support case, bugzilla, or issue please include the following summary data along with any other requested information:
...
[must-gather      ] OUT namespace/openshift-must-gather-spkvr created
[must-gather      ] OUT clusterrolebinding.rbac.authorization.k8s.io/must-gather-x7mrf created
Warning: [pod-must-have-label-foo] you must provide labels: {"foo"}
[must-gather      ] OUT pod for plug-in image ... created
[must-gather-6mpsw] OUT …
```
=> WRKLDS-1190: oc adm must-gather: print timestamp when logging in fallback mode

pkg/cli/admin/upgrade/status/controlplane.go, pkg/cli/admin/upgrade/status/controlplane_test.go, pkg/cli/admin/upgrade/status/examples/4.14.1-degraded.detailed-output, pkg/cli/admin/upgrade/status/examples/4.14.1-degraded.output, pkg/cli/admin/upgrade/status/examples/4.14.1-paused-worker-pool.detailed-output, pkg/cli/admin/upgrade/status/examples/4.14.1-paused-worker-pool.output, pkg/cli/admin/upgrade/status/examples/4.14.1-workers-started-updating-multiple-pools.detailed-output, pkg/cli/admin/upgrade/status/examples/4.14.1-workers-started-updating-multiple-pools.output, pkg/cli/admin/upgrade/status/examples/4.15.0-ec2-b02-cos-not-annotated.detailed-output, pkg/cli/admin/upgrade/status/examples/4.15.0-ec2-b02-cos-not-annotated.output, pkg/cli/admin/upgrade/status/examples/4.15.0-ec2-early.detailed-output, pkg/cli/admin/upgrade/status/examples/4.15.0-ec2-early.output, pkg/cli/admin/upgrade/status/examples/4.15.0-ec2-unavailable-mco-20m.detailed-output, pkg/cli/admin/upgrade/status/examples/4.15.0-ec2-unavailable-mco-20m.output, pkg/cli/admin/upgrade/status/examples/4.16.0-ec2-control-plane-updated-pdb-prohibits-draining.detailed-output, pkg/cli/admin/upgrade/status/examples/4.16.0-ec2-control-plane-updated-pdb-prohibits-draining.output
This pull request references https://issues.redhat.com/browse/OTA-1155
=> OTA-1155: `update status`: Simplify CO status line

pkg/cli/admin/release/extract_tools.go
=> OCPBUGS-32786: Improve error message when binary is not in target list

pkg/helpers/newapp/newapptest/newapp_test.go
This is manual cherry-pick of https://github.com/openshift/oc/pull/1717
=> [release-4.15] OCPBUGS-31726: Remove some of newapp unit tests relying on external deprecated images

pkg/cli/admin/prune/deployments/data.go
Due to the ongoing migration processes from deploymentconfig to deployment, people may fall into the situation where deployment object in reality points to replicationcontroller instead of replicaset. `oc adm prune` command panicks in that cases during the object casting. This PR handles this gracefully by ignoring these resources for prune.
=> OCPBUGS-34877: Ignore pruning when deployment points to replicationcontroller

pkg/cli/admin/prune/renderedmachineconfigs/renderedmachineconfigs.go
The old wording like:
```console
$ oc adm prune renderedmachineconfigs
Dry run enabled - no modifications will be made. Add --confirm to remove rendered machine configs.
Error deleting rendered MachineConfig rendered-master-3fff60688940de967f8aa44e5aa0e87e: deleting rendered MachineConfig rendered-master-3fff60688940de967f8aa44e5aa0e87e failed: machineconfigs.machineconfiguration.openshift.io "rendered-master-3fff60688940de967f8aa44e5aa0e87e" is forbidden: User "wking" cannot delete resource "machineconfigs" in API group "machineconfiguration.openshift.io" at the cluster scope
...
```
and:
```console
$ oc --as system:admin adm prune renderedmachineconfigs
Dry run enabled - no modifications will be made. Add --confirm to remove rendered machine configs.
DRY RUN: Deleted rendered …
```
=> OCPBUGS-36183: pkg/cli/admin/prune/renderedmachineconfigs: 'Error dry-run deleting'

pkg/cli/admin/mustgather/mustgather.go
=> WRKLDS-1310: pkg/cli/admin/mustgather: GA since and since-time flags

hack/verify-kube-version.sh
=> no-jira: Extend the kube version check for images/tools/Dockerfile

pkg/cli/admin/upgrade/status/status.go, pkg/cli/admin/upgrade/status/status_test.go
https://issues.redhat.com/browse/OTA-1291
/assign @petr-muller @Davoska
=> OTA-1291: upgrade status: removes custom nodes from the worker pool

pkg/cli/admin/upgrade/status/examples/4.14.1-degraded.detailed-output, pkg/cli/admin/upgrade/status/examples/4.14.1-degraded.output, pkg/cli/admin/upgrade/status/examples/4.14.1-paused-worker-pool.detailed-output, pkg/cli/admin/upgrade/status/examples/4.14.1-paused-worker-pool.output, pkg/cli/admin/upgrade/status/examples/4.14.1-workers-started-updating-multiple-pools.detailed-output, pkg/cli/admin/upgrade/status/examples/4.14.1-workers-started-updating-multiple-pools.output, pkg/cli/admin/upgrade/status/examples/4.15.0-ec2-b02-cos-not-annotated-mcp.yaml, pkg/cli/admin/upgrade/status/examples/4.15.0-ec2-b02-cos-not-annotated.detailed-output, pkg/cli/admin/upgrade/status/examples/4.15.0-ec2-b02-cos-not-annotated.output, pkg/cli/admin/upgrade/status/examples/4.15.0-ec2-early.detailed-output, pkg/cli/admin/upgrade/status/examples/4.15.0-ec2-early.output, pkg/cli/admin/upgrade/status/examples/4.15.0-ec2-unavailable-mco-20m.detailed-output, pkg/cli/admin/upgrade/status/examples/4.15.0-ec2-unavailable-mco-20m.output, pkg/cli/admin/upgrade/status/examples/4.16.0-ec2-control-plane-updated-pdb-prohibits-draining.detailed-output, pkg/cli/admin/upgrade/status/examples/4.16.0-ec2-control-plane-updated-pdb-prohibits-draining.output, pkg/cli/admin/upgrade/status/status.go, pkg/cli/admin/upgrade/status/workerpool.go
https://issues.redhat.com/browse/OTA-1277
=> OTA-1274,OTA-1277: upgrade status: use a table to represent node pools

pkg/cli/admin/nodeimage/monitor.go
The monitoring command can often times fail prematurely if it has trouble reading the node-joiner-monitor container logs.
Example:
E0801 11:18:52.520562 3198099 monitor.go:169] monitoring never finished: http2: server sent GOAWAY and closed the connection; LastStreamID=23, ErrCode=NO_ERROR, debug=""
In such cases, the command should not exit but retry.
Also added retry for initial Pod fetch in
waitForMonitoringToComplete and additional logging to aid in debugging.
=> WRKLDS-1316: Retry and do not fail when logs cannot be updated

pkg/cli/admin/nodeimage/create.go, pkg/cli/admin/nodeimage/create_test.go
Adds a guardrail for node-image commands which is supported only for Openshift version 4.17+
=> WRKLDS-1429: Adds a guardrail for node-image commands which is supported only for Openshift version 4.17+

pkg/cli/admin/policy/modify_roles.go
…m-* so they show in the CLI docs
https://issues.redhat.com/browse/OCPBUGS-32053
=> OCPBUGS-32053: Add examples for some oc adm policy commands

pkg/cli/admin/upgrade/status/controlplane.go, pkg/cli/admin/upgrade/status/examples/4.16.0-ec2-control-plane-updated-pdb-prohibits-draining.detailed-output, pkg/cli/admin/upgrade/status/examples/4.16.0-ec2-control-plane-updated-pdb-prohibits-draining.output, pkg/cli/admin/upgrade/status/workerpool.go
=> OTA-1212: Hide or condense control plane sections once successfully updated

pkg/cli/admin/nodeimage/create.go, pkg/cli/admin/nodeimage/create_test.go
Currently the `oc adm node-image create` command ignored the cluster-wide proxy settings when running the node-joiner pod, thus the command will fail in a scenario where a proxy is defined but the cluster does not have internet access (to fetch / inspect the release image).
This patch fixes the issue by configuring properly the node-joiner pod when the cluster-wide proxy `cluster` resource was found in the target cluster.
=> OCPBUGS-38990: use proxy settings when required

pkg/cli/admin/upgrade/status/examples/4.16.0-compact.detailed-output, pkg/cli/admin/upgrade/status/examples/4.16.0-compact.output, pkg/cli/admin/upgrade/status/examples/4.16.0-single-node.detailed-output, pkg/cli/admin/upgrade/status/examples/4.16.0-single-node.output, pkg/cli/admin/upgrade/status/status.go
Follow up https://issues.redhat.com/browse/OTA-1309?focusedId=25427314&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-25427314
/cc @petr-muller @evakhoni
=> OTA-1309: hide the empty "Worker Upgrade" section

pkg/cli/admin/upgrade/status/controlplane.go, pkg/cli/admin/upgrade/status/examples/4.14.1-degraded.detailed-output, pkg/cli/admin/upgrade/status/examples/4.14.1-degraded.output, pkg/cli/admin/upgrade/status/examples/4.14.1-paused-worker-pool.detailed-output, pkg/cli/admin/upgrade/status/examples/4.14.1-paused-worker-pool.output, pkg/cli/admin/upgrade/status/examples/4.14.1-workers-started-updating-multiple-pools.detailed-output, pkg/cli/admin/upgrade/status/examples/4.14.1-workers-started-updating-multiple-pools.output, pkg/cli/admin/upgrade/status/examples/4.15.0-ec2-b02-cos-not-annotated.detailed-output, pkg/cli/admin/upgrade/status/examples/4.15.0-ec2-b02-cos-not-annotated.output, pkg/cli/admin/upgrade/status/examples/4.15.0-ec2-early.detailed-output, pkg/cli/admin/upgrade/status/examples/4.15.0-ec2-early.output, pkg/cli/admin/upgrade/status/examples/4.15.0-ec2-unavailable-mco-20m.detailed-output, pkg/cli/admin/upgrade/status/examples/4.15.0-ec2-unavailable-mco-20m.output, pkg/cli/admin/upgrade/status/examples/4.16.0-compact.detailed-output, pkg/cli/admin/upgrade/status/examples/4.16.0-compact.output, pkg/cli/admin/upgrade/status/examples/4.16.0-single-node.detailed-output, pkg/cli/admin/upgrade/status/examples/4.16.0-single-node.output
Follow up https://issues.redhat.com/browse/OTA-1153?focusedId=25438486&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-25438486
"Operator Health" is the more accurate title.
/cc @petr-muller @evakhoni
=> OTA-1153: update-status: re-title "Operator Health" 

OWNERS_ALIASES
This PR updates the root-aproovers of oc.
=> NO-JIRA: Update root-approvers of oc

pkg/cli/admin/nodeimage/create.go
Required by https://github.com/openshift/installer/pull/9066
=> AGENT-966: additional rbac policy rules

pkg/cli/admin/nodeimage/create.go, pkg/cli/admin/nodeimage/create_test.go
Adds --pxe flag to "oc adm node-image create".
This causes the command to generate PXE files in place of the ISO.
=> WRKLDS-1320: Support PXE files with "node-image create"

pkg/cli/admin/nodeimage/create.go
Added a retry mechanism to make the command more resilient in case of temporary image pull errors.
From the (fixed) add-nodes job logs:
```
2024-11-08 15:38:12 +(./agent/07_agent_add_node.sh:36): oc adm node-image create --dir ocp/ostest/add-node/ --registry-config /opt/dev-scripts/pull_secret.json --loglevel=2
2024-11-08 15:38:14 I1108 15:38:14.268791   85770 create.go:406] Starting command in pod node-joiner-4n6mq
2024-11-08 15:38:14 I1108 15:38:14.287785   85770 create.go:826] Waiting for pod
...
2024-11-08 15:38:49 I1108 15:38:49.279518   85770 create.go:836] Unable to pull image (ErrImagePull), retrying
2024-11-08 15:38:54 I1108 15:38:54.299369   85770 create.go:826] Waiting for pod
2024-11-08 15:38:54 I1108 15:38:54.299395   85770 create.go:836] Unable to pull image (ErrImagePull), …
```
=> OCPBUGS-44388: add retry in case of image pull error

pkg/cli/admin/upgrade/status/examples/4.14.1-degraded.detailed-output, pkg/cli/admin/upgrade/status/examples/4.14.1-degraded.output, pkg/cli/admin/upgrade/status/examples/4.14.1-paused-worker-pool.detailed-output, pkg/cli/admin/upgrade/status/examples/4.14.1-paused-worker-pool.output, pkg/cli/admin/upgrade/status/examples/4.14.1-workers-started-updating-multiple-pools.detailed-output, pkg/cli/admin/upgrade/status/examples/4.14.1-workers-started-updating-multiple-pools.output, pkg/cli/admin/upgrade/status/examples/4.15.0-ec2-b02-cos-not-annotated.detailed-output, pkg/cli/admin/upgrade/status/examples/4.15.0-ec2-b02-cos-not-annotated.output, pkg/cli/admin/upgrade/status/examples/4.15.0-ec2-early.detailed-output, pkg/cli/admin/upgrade/status/examples/4.15.0-ec2-early.output, pkg/cli/admin/upgrade/status/examples/4.15.0-ec2-unavailable-mco-20m.detailed-output, pkg/cli/admin/upgrade/status/examples/4.15.0-ec2-unavailable-mco-20m.output, pkg/cli/admin/upgrade/status/examples/4.16.0-ec2-control-plane-updated-pdb-prohibits-draining.detailed-output, pkg/cli/admin/upgrade/status/examples/4.16.0-ec2-control-plane-updated-pdb-prohibits-draining.output, pkg/cli/admin/upgrade/status/workerpool.go
- Move Outdated and Total to COMPLETION
- Hide zero non-happy values: Degraded/Excluded
=> OTA-1224: status: simplify worker status line

pkg/cli/admin/upgrade/recommend/examples/4.12.16-longest-not-recommended.output, pkg/cli/admin/upgrade/recommend/examples/4.12.16-longest-not-recommended.show-outdated-releases-output, pkg/cli/admin/upgrade/recommend/examples/4.12.16-longest-not-recommended.version-4.12.51-output, pkg/cli/admin/upgrade/recommend/examples/4.12.16-longest-recommended.output, pkg/cli/admin/upgrade/recommend/examples/4.12.16-longest-recommended.show-outdated-releases-output, pkg/cli/admin/upgrade/recommend/examples/4.12.16-longest-recommended.version-4.12.51-output, pkg/cli/admin/upgrade/recommend/examples/4.14.1-all-recommended.output, pkg/cli/admin/upgrade/recommend/examples/4.14.1-all-recommended.show-outdated-releases-output, pkg/cli/admin/upgrade/recommend/recommend.go
Some unrelated cleanups bundled together to address @JianLi-RH 's [feedback][1]:
```console
$ git log --format='%h %s' origin/master..
6607f194 pkg/cli/admin/upgrade/recommend: Fix "no updates to <MAJOR>.<MINOR> available" error message
8dc61654 pkg/cli/admin/upgrade/recommend: Expand "URL" to "Release URL"
a46897a5 pkg/cli/admin/upgrade/recommend: "no known issues" placeholder
```
See the commit messages for more on each pivot.
[1]: https://issues.redhat.com/browse/OTA-1273?focusedId=26029621&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-26029621
=> NO-ISSUE: pkg/cli/admin/upgrade/recommend: "no known issues" placeholder, etc.

pkg/cli/admin/upgrade/status/controlplane.go, pkg/cli/admin/upgrade/status/controlplane_test.go, pkg/cli/admin/upgrade/status/examples/4.14.1-degraded.detailed-output, pkg/cli/admin/upgrade/status/examples/4.14.1-degraded.output, pkg/cli/admin/upgrade/status/examples/4.14.1-workers-started-updating-multiple-pools.detailed-output, pkg/cli/admin/upgrade/status/examples/4.14.1-workers-started-updating-multiple-pools.output, pkg/cli/admin/upgrade/status/examples/4.15.0-ec2-early.detailed-output, pkg/cli/admin/upgrade/status/examples/4.15.0-ec2-early.output, pkg/cli/admin/upgrade/status/examples/4.15.0-ec2-unavailable-mco-20m.detailed-output, pkg/cli/admin/upgrade/status/examples/4.15.0-ec2-unavailable-mco-20m.output, pkg/cli/admin/upgrade/status/examples/4.16.0-single-node.detailed-output, pkg/cli/admin/upgrade/status/examples/4.16.0-single-node.output, pkg/cli/admin/upgrade/status/health.go, pkg/cli/admin/upgrade/status/health_test.go, pkg/cli/admin/upgrade/status/status.go
https://issues.redhat.com/browse/OTA-1340
/cc @petr-muller @Davoska
=> OTA-1340: upgrade status: show updating cluster operator names in the output

pkg/cli/admin/inspect/inspect.go, pkg/cli/admin/inspect/namespace.go
=> Revert "OCPBUGS-37344: Skip inspection of the daemonset pods running on data plane"

pkg/cli/admin/upgrade/status/controlplane.go, pkg/cli/admin/upgrade/status/controlplane_test.go, pkg/cli/admin/upgrade/status/status.go
To address https://github.com/openshift/oc/pull/1920#discussion_r1854439651
/cc @petr-muller @DavidHurta
=> OTA-1393: status: compute mcoImagePullSpec only once

pkg/cli/admin/upgrade/status/controlplane.go, pkg/cli/admin/upgrade/status/controlplane_test.go, pkg/cli/admin/upgrade/status/examples/to-multi-arch.detailed-output, pkg/cli/admin/upgrade/status/examples/to-multi-arch.output
Address https://github.com/openshift/oc/pull/1920#discussion_r1854386003 and https://github.com/openshift/oc/pull/1920#discussion_r1859123180
/cc @petr-muller @DavidHurta
=> OTA-1393: status: recognize multi-arch in target version

pkg/cli/admin/release/new.go
Previously the check for `image-references` file presence was done by a `takeFileByName` (not a very good name) function which also removed the corresponding `FileInfo` from `contents` as a sideeffect,, so it is not iterated later when the manifests are processed. The file existence can be checked directly, and the file can be easily skipped when doing substitution. While I believe the code is clearer this way, I still added a comment saying why the presence of the file is checked.
/cc @DavidHurta @hongkailiu @wking
=> NO-JIRA: adm release: simplify `image-references` check

pkg/cli/admin/release/new.go
Rename variables to use `src` and `dst` more clearly
/cc @DavidHurta @wking @hongkailiu
=> NO-JIRA: adm release: clarify manifest processing

pkg/cli/admin/release/new.go
Reverts openshift/oc#2000
The change was reverted during investigation of a release building regression in Konflux, which timewise correlated to when the original change was merged. It was found to be unrelated to the regression (details in [Slack](https://redhat-internal.slack.com/archives/C06Q309QUDV/p1743183670944419)) so I would like to merge it again.
=> NO-JIRA: `adm release new`: simplify `writePayload`

images/tools/Dockerfile, images/tools/sos.conf
Adding `sos.conf` file with default configuration for `sos` as discussed in [WRKLDS-1103](https://issues.redhat.com//browse/WRKLDS-1103).
cc @ingvagabund
=> WRKLDS-1103: Adding sos.conf file for default sos config into the tools image

pkg/cli/admin/upgrade/recommend/recommend.go
As part of the `--accepted-risk` feature (#2017), because listing unaccepted risk names gives us a way to say "we have more problems we think you should consider" for folks who just want a short summary before deciding whether they want more details.  I'm keeping the chatty version as the default, because historically we have had users who don't want to look at the details, and instead hope that waiting will be enough for the issues to resolve.
For "there was a regression, and Red Hat will ship a fix", waiting will eventually work.  But for "your cluster is alerting, and you should look into that", waiting is unlikely to help.  And even for the regression situation, it is the user's responsibility to weigh the risk of updating into the known regression against the risk of remaining on an …
=> OTA-1539: pkg/cli/admin/upgrade/recommend: Add a --quiet option

pkg/cli/admin/mustgather/mustgather.go
=> OCPBUGS-57635: Revert "OCPBUGS-56691: Rely on overall available disk space of the mounted volume"
